import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useApi } from '../../hooks/useApi';
export default function CustomerPortalPage(){const {token}=useParams(); const api=useApi(); const [data,setData]=useState(null); const [message,setMessage]=useState(''); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
useEffect(()=>{api.get(`/customer-portal/${token}`).then(r=>{if(r.success)setData(r.data?.data);else setMsg(r.error||'Invalid or expired token.'); setLoading(false);});},[token]);
if(loading) return <div className='min-h-screen bg-slate-100 p-6 text-slate-700'>Loading portal…</div>;
if(!data) return <div className='min-h-screen bg-slate-100 p-6'><div className='mx-auto max-w-3xl rounded-3xl border bg-white p-6'><h1 className='text-2xl font-black text-slate-950'>Portal unavailable</h1><p className='text-slate-700'>{msg||'This link is invalid or expired.'}</p></div></div>;
return <div className='min-h-screen bg-slate-100 p-6'><div className='mx-auto max-w-5xl rounded-3xl border bg-white p-6 shadow-sm'><h1 className='text-2xl font-black text-slate-950'>{data.business_name||'Customer Portal'}</h1><p className='text-slate-700'>Welcome {data.customer_name||'Customer'}</p>{msg&&<p className='mt-2 text-sm text-slate-700'>{msg}</p>}
<div className='mt-4 grid gap-3 md:grid-cols-2'>{(data.quotes||[]).map((q,idx)=><div key={idx} className='rounded-2xl border p-3'><p className='font-bold'>{q.title||'Quote'}</p><p className='text-sm text-slate-700'>Total: {q.total||'-'}</p>{q.public_url&&<a className='text-sm text-blue-700' href={q.public_url}>Open quote</a>}</div>)}{(data.invoices||[]).map((i,idx)=><div key={idx} className='rounded-2xl border p-3'><p className='font-bold'>{i.title||'Invoice'}</p><p className='text-sm text-slate-700'>Total: {i.total||'-'}</p>{(i.payment_url||i.payment_link)&&<a className='text-sm text-blue-700' href={i.payment_url||i.payment_link}>Pay now</a>}</div>)}</div>
<textarea className='mt-4 w-full rounded-xl border p-2' placeholder='Message/request callback' value={message} onChange={(e)=>setMessage(e.target.value)}/><button className='mt-2 rounded-xl bg-blue-600 px-4 py-2 text-white' onClick={async()=>{const r=await api.post(`/customer-portal/${token}/message`,{message}); setMsg(r.success?'Message sent.':'Could not send message.');}}>Send message</button></div></div>;}
