import React,{useEffect,useState}from"react";import{Link,useLocation,useParams}from"react-router-dom";import{Briefcase,LogOut,MapPin,MessageCircle,Navigation,RefreshCw,UserRound}from"lucide-react";import{toast}from"sonner";import{useApi}from"@/hooks/useApi";import{useAuth}from"@/context/AuthContext";import"./WorkerSimplePages.css";
const c=v=>String(v||"").replace(/\s+/g," ").trim(),arr=v=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:Array.isArray(v?.jobs)?v.jobs:Array.isArray(v?.items)?v.items:Array.isArray(v?.results)?v.results:[],oid=v=>!v?"":typeof v==="string"||typeof v==="number"?String(v):typeof v==="object"?oid(v.$oid||v.id||v._id||v.job_id||""):"";
const id=j=>oid(j?.id||j?._id||j?.job_id),name=j=>c(j?.title||j?.job_name||j?.service_type||"Job"),who=j=>c(j?.client_name||j?.customer_name||j?.client||"Customer"),where=j=>c(j?.address||j?.site_address||j?.service_address||j?.location||""),what=j=>c(j?.worker_instructions||j?.instructions||j?.description||j?.notes||"No instructions."),day=j=>c(j?.scheduled_date||j?.date||j?.start).slice(0,10),time=j=>c(j?.scheduled_time||j?.time),done=j=>/complete|done|finished|cancelled/.test(c(j?.status).toLowerCase()),today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10),map=a=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a)}`;
function useJobs(){const{get}=useApi(),[jobs,setJobs]=useState([]),[load,setLoad]=useState(true);async function go(){setLoad(true);try{const r=await get("/jobs");setJobs(arr(r?.data||r).filter(x=>id(x)).sort((a,b)=>`${day(a)} ${time(a)}`.localeCompare(`${day(b)} ${time(b)}`)))}catch{setJobs([])}setLoad(false)}useEffect(()=>{go()},[]);return{jobs,load,go}}
async function beacon(post,j,state){try{await post("/onsite/worker-beacon",{state,source:state==="stop"?"finish-job":"start-job",job_id:id(j),job_title:name(j),address:where(j),location:where(j)})}catch{}}
function Shell({tab,title,sub,children}){return <main className="simpleWorkerApp"><section className="swHero"><span>{tab}</span><h1>{title}</h1><p>{sub}</p></section><section className="swBody">{children}</section><nav className="swNav">{[["Today","/worker/today"],["Jobs","/worker/jobs"],["Messages","/worker/ops"],["Help","/worker/help"],["Me","/worker/settings"]].map(([x,h])=><Link key={x} className={x===tab?"active":""} to={h}>{x}</Link>)}</nav></main>}
function Card({j}){const a=where(j);return <article className="swCard swJob"><span>{time(j)||day(j)||"Ready"}</span><h2>{name(j)}</h2><p>{who(j)}</p>{a?<small><MapPin size={15}/>{a}</small>:null}<Link className="swPrimary" to={`/worker/jobs/${id(j)}`}>Open job</Link></article>}
function Alerts(){const[ok,setOk]=useState(typeof Notification==="undefined"||Notification.permission==="granted");async function turnOn(){if(typeof Notification==="undefined"){setOk(true);return}const p=await Notification.requestPermission();setOk(p==="granted")}return ok?null:<section className="swCard"><span>Alerts</span><h2>Turn on job alerts</h2><p>So you do not miss job changes.</p><button className="swPrimary" onClick={turnOn}>Turn on alerts</button></section>}
export function NoFussToday(){const{jobs,load}=useJobs();const t=jobs.filter(j=>!done(j)&&day(j)===today()),show=t.length?t:jobs.filter(j=>!done(j)).slice(0,3);return <Shell tab="Today" title="Today" sub="Your schedule."><Alerts/>{load?<section className="swEmpty"><RefreshCw className="spin"/>Loading jobs</section>:null}{!load&&show.map(j=><Card key={id(j)} j={j}/>) }{!load&&!show.length?<section className="swEmpty"><Briefcase/>No jobs today.</section>:null}</Shell>}
export function NoFussJobs(){const{jobs,load,go}=useJobs(),show=jobs.filter(j=>!done(j));return <Shell tab="Jobs" title="Jobs" sub="Open jobs."><button className="swLight" onClick={go}>Refresh</button>{load?<section className="swEmpty"><RefreshCw className="spin"/>Loading jobs</section>:null}{show.map(j=><Card key={id(j)} j={j}/>)}</Shell>}
export function NoFussJob(){const{ id:jid}=useParams(),{get,post,patch}=useApi(),[j,setJ]=useState(null),[started,setStarted]=useState(false),[finish,setFinish]=useState(false),[note,setNote]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{(async()=>{let f=null;try{const r=await get(`/jobs/${jid}`);f=r?.data?.job||r?.data?.data||r?.data}catch{}if(!f||!id(f)){const r=await get("/jobs");f=arr(r?.data||r).find(x=>id(x)===jid)}setJ(f);setStarted(/progress|started/.test(c(f?.status).toLowerCase()));setNote(c(f?.worker_notes||""))})()},[jid]);async function act(){if(!j)return;if(started&&!finish){setFinish(true);return}setBusy(true);const end=started;await beacon(post,j,end?"stop":"start");try{await patch(`/worker/jobs/${jid}/field-update`,{status:end?"completed":"in_progress",worker_status:end?"completed":"started",worker_notes:note})}catch{}setBusy(false);if(end){toast.success("Sent");window.location.assign("/worker/today")}else{setStarted(true);toast.success("Started")}}if(!j)return <Shell tab="Jobs" title="Loading" sub="Job details."><section className="swEmpty">Loading</section></Shell>;const a=where(j);return <Shell tab="Jobs" title={name(j)} sub={who(j)}><section className="swCard"><span>Where</span><h2>{a||"No address"}</h2>{a?<a className="swPrimary" href={map(a)} target="_blank" rel="noreferrer"><Navigation size={16}/>Directions</a>:null}</section><section className="swCard"><span>Do this</span><p>{what(j)}</p></section><section className="swCard"><span>{finish?"Before finish":"Note"}</span>{finish?<h2>Need to add anything?</h2>:null}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={finish?"Add proof or note if needed":"Optional note"}/>{finish?<button className="swLight" onClick={()=>setNote(note||"No extra proof needed.")}>No, finish job</button>:null}</section><button className={`swBig ${started?"finish":""}`} disabled={busy} onClick={act}>{busy?"Saving":started?(finish?"Send to office":"Finish job"):"Start job"}</button></Shell>}
export function NoFussMessages(){const[t,setT]=useState("");return <Shell tab="Messages" title="Messages" sub="Message office."><section className="swCard"><MessageCircle/><h2>Office</h2><textarea value={t} onChange={e=>setT(e.target.value)} placeholder="Type message"/><button className="swPrimary" onClick={()=>{setT("");toast.success("Message sent")}}>Send</button></section></Shell>}
export function NoFussHelp(){return <Shell tab="Help" title="Help" sub="Message office if stuck."><section className="swCard"><h2>Need help?</h2><p>Wrong address, unclear job, customer issue, or unsafe work.</p><Link className="swPrimary" to="/worker/ops">Message office</Link></section></Shell>}
export function NoFussMe(){const{user,logout}=useAuth();return <Shell tab="Me" title="Me" sub="Profile."><section className="swCard"><UserRound/><h2>{c(user?.name||user?.email||"Worker")}</h2><p>{c(user?.email)}</p></section><button className="swPrimary danger" onClick={logout}><LogOut size={16}/>Log out</button></Shell>}
export default function NoFussRoute(){const l=useLocation();if(l.pathname==="/worker/jobs")return <NoFussJobs/>;if(l.pathname==="/worker/ops")return <NoFussMessages/>;if(l.pathname==="/worker/help")return <NoFussHelp/>;if(l.pathname==="/worker/settings")return <NoFussMe/>;return <NoFussToday/>}
