import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { RefreshCw } from "lucide-react";
import { useApi } from "@/hooks/useApi";

const FILTERS = ["all", "today", "assigned", "acknowledged", "in_progress", "paused", "completed", "overdue"];
const badge = (s) => ({ assigned:"bg-slate-100 text-slate-800", acknowledged:"bg-indigo-100 text-indigo-800", in_progress:"bg-blue-100 text-blue-800", paused:"bg-amber-100 text-amber-800", completed:"bg-emerald-100 text-emerald-800", cancelled:"bg-red-100 text-red-800" }[s] || "bg-slate-100 text-slate-800");
const norm = (s) => String(s||"assigned").toLowerCase();

export default function WorkerJobsPage(){
  const { get } = useApi();
  const [jobs,setJobs]=useState([]); const [loading,setLoading]=useState(true); const [err,setErr]=useState(""); const [filter,setFilter]=useState("all"); const [updated,setUpdated]=useState(null);
  const load = useCallback(async()=>{ setErr(""); setLoading(true); const [a,b]=await Promise.allSettled([get("/worker/jobs"), get("/jobs")]); const pick=(r)=>r?.value?.success?r.value.data:[]; const raw=[...([pick(a)].flat()),...([pick(b)].flat())][0]||pick(a)||pick(b); const arr=Array.isArray(raw)?raw:(Array.isArray(raw?.data)?raw.data:(Array.isArray(raw?.jobs)?raw.jobs:[])); setJobs(arr); if(!arr.length && !pick(a)?.success && !pick(b)?.success) setErr("Could not load jobs."); setUpdated(new Date()); setLoading(false); },[get]);
  useEffect(()=>{load();},[load]);
  const today = new Date().toISOString().slice(0,10);
  const filtered=useMemo(()=>jobs.filter((j)=>{const st=norm(j.status); const d=String(j.scheduled_date||"").slice(0,10); if(filter==="all") return true; if(filter==="today") return d===today; if(filter==="overdue") return d && d<today && !["completed","cancelled"].includes(st); return st===filter;}),[jobs,filter,today]);
  const summary=useMemo(()=>({today:jobs.filter(j=>String(j.scheduled_date||"").slice(0,10)===today).length,in_progress:jobs.filter(j=>norm(j.status)==="in_progress").length,paused:jobs.filter(j=>norm(j.status)==="paused").length,completed:jobs.filter(j=>norm(j.status)==="completed").length,upcoming:jobs.filter(j=>String(j.scheduled_date||"").slice(0,10)>today).length}),[jobs,today]);

  return <div className="cx-page pb-24"><div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-slate-950">My Jobs</h1><p className="text-sm font-semibold text-slate-700">Assigned work for today and upcoming jobs.</p><p className="text-xs text-slate-700">Last updated: {updated?updated.toLocaleTimeString():"-"}</p></div><button onClick={load} className="rounded-xl bg-blue-600 p-3 text-white"><RefreshCw className="h-4 w-4"/></button></div></div>
  <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(summary).map(([k,v])=><div key={k} className="rounded-3xl border bg-white p-3"><p className="text-xs font-bold text-slate-700 uppercase">{k.replace("_"," ")}</p><p className="text-xl font-black text-slate-950">{v}</p></div>)}</div>
  <div className="mt-3 flex flex-wrap gap-2">{FILTERS.map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-2xl border px-3 py-2 text-sm font-bold ${filter===f?"bg-slate-900 text-white":"bg-white text-slate-900"}`}>{f.replace("_"," ")}</button>)}</div>
  {loading?<div className="mt-4 rounded-3xl border bg-white p-6 text-slate-800">Loading…</div>:err?<div className="mt-4 rounded-3xl border bg-white p-6 text-red-700">{err} <button onClick={load} className="underline">Retry</button></div>:jobs.length===0?<div className="mt-4 rounded-3xl border bg-white p-6 text-slate-800">No jobs assigned.</div>:filtered.length===0?<div className="mt-4 rounded-3xl border bg-white p-6 text-slate-800">No jobs for selected filter.</div>:<div className="mt-4 space-y-3">{filtered.map(j=>{const id=j.id||j._id;const st=norm(j.status);return <div key={id} className="rounded-3xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="text-lg font-black text-slate-950">{j.title||"Untitled job"}</p><p className="text-sm font-semibold text-slate-700">{j.client_name||j.customer_name||"Client"}</p><p className="text-sm text-slate-800">{j.address||"Address not set"}</p><p className="text-sm text-slate-800">{String(j.scheduled_date||"").slice(0,16)} {j.scheduled_time||""}</p><p className="text-sm text-slate-800">Est: {j.estimated_duration||0} mins</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge(st)}`}>{st.replace("_"," ")}</span></div><div className="mt-3 flex gap-2"><Link to={`/worker/jobs/${id}`} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Open job</Link>{st==="assigned"&&<Link to={`/worker/jobs/${id}`} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-900">Acknowledge</Link>}{["paused","in_progress"].includes(st)&&<Link to={`/worker/jobs/${id}`} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-900">Continue</Link>}</div></div>})}</div>}
  </div>;
}
