import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useApi } from "@/hooks/useApi";

const norm=(s)=>String(s||"assigned").toLowerCase();
const badge=(s)=>({assigned:"bg-slate-100 text-slate-800",acknowledged:"bg-indigo-100 text-indigo-800",in_progress:"bg-blue-100 text-blue-800",paused:"bg-amber-100 text-amber-800",completed:"bg-emerald-100 text-emerald-800",cancelled:"bg-red-100 text-red-800"}[s]||"bg-slate-100 text-slate-800");

export default function WorkerJobDetailPage(){
  const {id}=useParams(); const {get,post}=useApi();
  const [job,setJob]=useState(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[act,setAct]=useState(false),[note,setNote]=useState(""),[savingNote,setSavingNote]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState([]),[lightbox,setLightbox]=useState("");
  const load=useCallback(async()=>{setLoading(true);setErr(""); const r=await get(`/worker/jobs/${id}`); if(r.success){setJob(r.data);setNote(r.data?.worker_notes||"");} else {setErr(r.error||"Failed");} setLoading(false);},[get,id]);
  useEffect(()=>{load();},[load]);
  const run=async(ep,ok)=>{setAct(true);setMsg("");setErr("");const r=await post(ep,{}); if(r.success){setMsg(ok);await load();} else setErr(r.error||"Action failed"); setAct(false);};
  const onNote=async()=>{setSavingNote(true); const r=await post(`/jobs/${id}/worker-notes`,{note}); if(r.success){setMsg("Note saved."); await load();} else setErr(r.error||"Failed to save note"); setSavingNote(false);};
  const onUpload=async()=>{ if(!files.length) return; setUploading(true); const photos=[]; for (const f of files){const b=await new Promise((res)=>{const rd=new FileReader(); rd.onload=()=>res(rd.result); rd.readAsDataURL(f);}); photos.push(b);} const r=await post(`/jobs/${id}/photos`,{photos}); if(r.success){setMsg("Photo upload complete.");setFiles([]);await load();} else setErr(r.error||"Upload failed"); setUploading(false);};
  const st=norm(job?.status);
  const actions=useMemo(()=> st==="assigned"?[{k:"ack",t:"Acknowledge job",ep:`/jobs/${id}/acknowledge`}]:st==="acknowledged"?[{k:"start",t:"Start job",ep:`/jobs/${id}/start`}]:st==="in_progress"?[{k:"pause",t:"Pause job",ep:`/jobs/${id}/pause`},{k:"complete",t:"Complete job",ep:`/jobs/${id}/complete`}]:st==="paused"?[{k:"resume",t:"Resume job",ep:`/jobs/${id}/resume`},{k:"complete",t:"Complete job",ep:`/jobs/${id}/complete`}]:[],[id,st]);
  if(loading) return <div className="cx-page">Loading…</div>;
  if(err.includes("403")) return <div className="cx-page">You do not have access to this job.</div>;
  if(err.includes("404")||!job) return <div className="cx-page">Job not found or no longer assigned.</div>;
  return <div className="cx-page pb-24"><div className="rounded-3xl border bg-white p-5 shadow-sm"><Link to="/worker/jobs" className="text-blue-600 font-bold">← Back to My Jobs</Link><div className="mt-2 flex items-start justify-between"><div><h1 className="text-2xl font-black text-slate-950">{job.title||"Untitled Job"}</h1><p className="text-sm text-slate-800">{job.job_type||"General"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge(st)}`}>{st.replace("_"," ")}</span></div><p className="text-sm text-slate-800 mt-2">{job.scheduled_date||""} {job.scheduled_time||""}</p><p className="text-sm text-slate-800">{job.client_name||job.customer_name||""}</p><p className="text-sm text-slate-800">{job.address||""} · <a className="text-blue-600 font-bold" href={`https://maps.google.com/?q=${encodeURIComponent(job.address||"")}`}>Open map</a></p><button onClick={load} className="mt-2 rounded-xl border px-3 py-2 text-sm font-bold">Refresh</button></div>
  <div className="mt-3 rounded-3xl border bg-white p-5"><h2 className="text-lg font-black text-slate-950">Job details</h2><p className="text-sm text-slate-800">{job.notes||"No details provided."}</p><p className="text-sm text-slate-800 mt-1">Estimated duration: {job.estimated_duration||0} mins</p><p className="text-sm text-slate-800">Assigned worker: {job.assigned_worker_name||"-"}</p></div>
  <div className="mt-3 rounded-3xl border bg-white p-5"><h2 className="text-lg font-black text-slate-950">Actions</h2><div className="mt-2 flex flex-wrap gap-2">{actions.map(a=><button disabled={act} key={a.k} onClick={()=>run(a.ep,`${a.t} recorded.`)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">{a.t}</button>)}{st==="completed"&&<p className="text-emerald-700 font-bold">Completed.</p>}</div><p className="mt-2 text-sm text-slate-800">Started: {job.started_at||"-"} · Paused: {job.paused_at||"-"} · Completed: {job.completed_at||"-"}</p>{msg&&<p className="text-blue-700 text-sm mt-2">{msg}</p>}{err&&<p className="text-red-700 text-sm mt-2">{err}</p>}</div>
  <div className="mt-3 rounded-3xl border bg-white p-5"><h2 className="text-lg font-black text-slate-950">Upload job photos</h2><input type="file" accept="image/*" capture="environment" multiple onChange={(e)=>setFiles(Array.from(e.target.files||[]))} className="mt-2"/><div className="mt-2 flex flex-wrap gap-2">{files.map((f)=> <span key={f.name} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold">{f.name}</span>)}</div><button disabled={uploading||!files.length} onClick={onUpload} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">{uploading?"Uploading...":"Upload"}</button><div className="mt-3 grid grid-cols-3 gap-2">{(job.photos||[]).map((p,i)=><button key={i} onClick={()=>setLightbox(p)} className="overflow-hidden rounded-xl border"><img src={p} alt="job" className="h-24 w-full object-cover"/></button>)}</div></div>
  <div className="mt-3 rounded-3xl border bg-white p-5"><h2 className="text-lg font-black text-slate-950">Worker notes</h2><textarea value={note} onChange={(e)=>setNote(e.target.value)} className="mt-2 w-full rounded-xl border p-3 text-slate-900" rows={4} placeholder="Add a job note"/><button disabled={savingNote} onClick={onNote} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Save note</button></div>
  {lightbox&&<div className="fixed inset-0 z-50 bg-black/80 p-4" onClick={()=>setLightbox("")}><img src={lightbox} alt="preview" className="mx-auto max-h-full max-w-full rounded-xl"/></div>}
  </div>;
}
