import React,{useEffect,useMemo,useState}from"react";
import{Link,useLocation,useParams}from"react-router-dom";
import{AlertTriangle,Briefcase,HelpCircle,LogOut,MapPin,Navigation,RefreshCw,UserRound}from"lucide-react";
import{toast}from"sonner";
import{useApi}from"@/hooks/useApi";
import{useAuth}from"@/context/AuthContext";
import"./WorkerSimplePages.css";
const c=v=>String(v||"").replace(/\s+/g," ").trim();
const a=v=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:Array.isArray(v?.jobs)?v.jobs:Array.isArray(v?.items)?v.items:Array.isArray(v?.results)?v.results:Array.isArray(v?.data?.jobs)?v.data.jobs:[];
const o=v=>!v?"":typeof v==="string"||typeof v==="number"?String(v):typeof v==="object"?o(v.$oid||v.oid||v.id||v._id||v.job_id||""):"";
const id=j=>o(j?.id||j?._id||j?.job_id||j?.uuid),ttl=j=>c(j?.title||j?.job_name||j?.job_title||j?.service_type||j?.description||"Job"),cli=j=>c(j?.client_name||j?.customer_name||j?.client||j?.customer||"Customer"),addr=j=>c(j?.address||j?.site_address||j?.service_address||j?.job_address||j?.location||""),note=j=>c(j?.worker_instructions||j?.instructions||j?.description||j?.notes||"No special instructions."),st=j=>c(j?.status||j?.job_status||j?.workflow_status||"assigned").toLowerCase().replaceAll(" ","_"),dt=j=>c(j?.scheduled_date||j?.date||j?.start||j?.due_date).slice(0,10),tm=j=>c(j?.scheduled_time||j?.time||j?.start_time||"");
const done=j=>/complete|completed|done|finished|cancelled|archived/.test(st(j));
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const maps=s=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s||"")}`;
function useJobs(){const{get}=useApi();const[j,setJ]=useState([]),[l,setL]=useState(true),[e,setE]=useState("");async function load(){setL(true);setE("");try{const r=await get("/jobs");setJ(a(r?.data||r).filter(x=>id(x)).sort((x,y)=>`${dt(x)||"9999"} ${tm(x)||"99"}`.localeCompare(`${dt(y)||"9999"} ${tm(y)||"99"}`)))}catch{setE("Could not load jobs");setJ([])}setL(false)}useEffect(()=>{load()},[]);return{jobs:j,loading:l,error:e,reload:load}}
async function live(post,job,state,source){try{await post("/onsite/worker-beacon",{state,source,job_id:id(job),job_title:ttl(job),address:addr(job),location:addr(job)})}catch{}}
function Shell({active,title,sub,children}){return <main className="simpleWorkerApp"><section className="swHero"><span>{active}</span><h1>{title}</h1><p>{sub}</p></section><section className="swBody">{children}</section><nav className="swNav">{[["Today","/worker/today"],["Jobs","/worker/jobs"],["Proof","/worker/ops"],["Help","/worker/help"],["Me","/worker/settings"]].map(([x,h])=><Link key={x} className={x===active?"active":""} to={h}>{x}</Link>)}</nav></main>}
function Card({job}){const s=addr(job);return <article className="swCard swJob"><span>{tm(job)||dt(job)||"Ready"}</span><h2>{ttl(job)}</h2><p>{cli(job)}</p>{s?<small><MapPin size={15}/>{s}</small>:<small><AlertTriangle size={15}/>No address</small>}<Link className="swPrimary" to={`/worker/jobs/${id(job)}`}>Open job</Link></article>}
export function DailyToday(){const{jobs,loading,error,reload}=useJobs();const d=useMemo(()=>jobs.filter(x=>!done(x)&&dt(x)===today()),[jobs]);const show=d.length?d:jobs.filter(x=>!done(x)).slice(0,3);return <Shell active="Today" title="Today" sub="Jobs for the day.">{loading?<section className="swEmpty"><RefreshCw className="spin"/>Loading jobs…</section>:null}{error?<section className="swEmpty danger"><AlertTriangle/>{error}<button onClick={reload}>Retry</button></section>:null}{!loading&&show.map(x=><Card key={id(x)} job={x}/>) }{!loading&&!show.length?<section className="swEmpty"><Briefcase/>No jobs today.</section>:null}</Shell>}
export function DailyJobs(){const{jobs,loading,error,reload}=useJobs();const show=jobs.filter(x=>!done(x));return <Shell active="Jobs" title="Jobs" sub="All open jobs."><button className="swLight" onClick={reload}><RefreshCw size={16}/>Refresh</button>{loading?<section className="swEmpty"><RefreshCw className="spin"/>Loading jobs…</section>:null}{error?<section className="swEmpty danger"><AlertTriangle/>{error}</section>:null}{show.map(x=><Card key={id(x)} job={x}/>) }{!loading&&!show.length?<section className="swEmpty"><Briefcase/>No open jobs.</section>:null}</Shell>}
export function DailyJob(){const{id:jid}=useParams();const{get,post,patch}=useApi();const[job,setJob]=useState(null),[loading,setLoading]=useState(true),[started,setStarted]=useState(false),[n,setN]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{(async()=>{setLoading(true);let f=null;try{const r=await get(`/jobs/${encodeURIComponent(jid)}`);f=r?.data?.job||r?.data?.data||r?.data||null}catch{}if(!f||!id(f)){try{const r=await get("/jobs");f=a(r?.data||r).find(x=>id(x)===String(jid))}catch{}}setJob(f||null);setStarted(/progress|started/.test(st(f||{})));setN(c(f?.worker_notes||""));setLoading(false)})()},[jid]);async function act(){if(!job)return;setBusy(true);const fin=started;await live(post,job,fin?"stop":"start",fin?"finish-job":"start-job");try{await patch(`/worker/jobs/${encodeURIComponent(jid)}/field-update`,{status:fin?"completed":"in_progress",worker_status:fin?"completed":"started",worker_notes:n})}catch{}setBusy(false);if(fin){toast.success("Job sent");window.location.assign("/worker/jobs")}else{setStarted(true);toast.success("Job started")}}if(loading)return <Shell active="Jobs" title="Loading" sub="Getting job."><section className="swEmpty"><RefreshCw className="spin"/>Loading…</section></Shell>;if(!job)return <Shell active="Jobs" title="Not found" sub="Could not open job."><Link className="swPrimary" to="/worker/jobs">Back to jobs</Link></Shell>;const s=addr(job);return <Shell active="Jobs" title={ttl(job)} sub={cli(job)}><section className="swCard"><span>Where</span><h2>{s||"No address"}</h2>{s?<a className="swPrimary" href={maps(s)} target="_blank" rel="noreferrer"><Navigation size={16}/>Directions</a>:null}</section><section className="swCard"><span>Do this</span><p>{note(job)}</p></section><section className="swCard"><span>Note</span><textarea value={n} onChange={e=>setN(e.target.value)} placeholder="Optional note for boss…"/></section><button className={`swBig ${started?"finish":""}`} disabled={busy} onClick={act}>{busy?"Saving…":started?"Finish job":"Start job"}</button></Shell>}
export function DailyProof(){const{jobs,loading}=useJobs();const j=jobs.filter(x=>!done(x))[0];return <Shell active="Proof" title="Proof" sub="Open the job to add proof.">{loading?<section className="swEmpty"><RefreshCw className="spin"/>Loading…</section>:null}{!loading&&j?<Card job={j}/>:<section className="swEmpty"><Briefcase/>No job ready.</section>}</Shell>}
export function DailyHelp(){return <Shell active="Help" title="Help" sub="Keep it simple."><section className="swCard"><HelpCircle/><h2>Need help?</h2><p>Open the job, write the problem in the note, then finish/send it. For urgent problems, call the boss.</p></section><Link className="swPrimary" to="/worker/jobs">Open jobs</Link></Shell>}
export function DailyMe(){const{user,logout}=useAuth();return <Shell active="Me" title="Me" sub="Profile."><section className="swCard"><UserRound/><h2>{c(user?.name||user?.email||"Worker")}</h2><p>{c(user?.email)}</p></section><button className="swPrimary danger" onClick={logout}><LogOut size={16}/>Log out</button></Shell>}
export default function DailyRoute(){const l=useLocation();if(l.pathname==="/worker/jobs")return <DailyJobs/>;if(l.pathname==="/worker/ops")return <DailyProof/>;if(l.pathname==="/worker/help")return <DailyHelp/>;if(l.pathname==="/worker/settings")return <DailyMe/>;return <DailyToday/>}
