import React from "react";
import "../churvox-clean/ChurvoxCleanApp.css";
import "../churvox-clean/ChurvoxCleanDensity.css";
import "../churvox-clean/ChurvoxCleanPremium.css";

const nav = ["AI Guide", "Command", "Jobs", "Clients", "Quotes", "Invoices", "Team", "Payroll", "Workers", "Xero", "Settings", "Plans", "Support"];
const cleanKey = (value) => String(value || "").toLowerCase().replace(/\s+/g, "");
const aliases = { "": "aiguide", dashboard: "aiguide", smart: "aiguide", hub: "aiguide", today: "aiguide", guide: "aiguide", ai: "aiguide", setup: "aiguide", setupassistant: "aiguide", firstrun: "aiguide", commanddesk: "command", aioperator: "command", quickcreateai: "command", automation: "command", approvals: "command", planday: "jobs", recurring: "jobs", schedule: "jobs", calendar: "jobs", photos: "jobs", proof: "jobs", customers: "clients", documents: "clients", quoteai: "quotes", invoicecheck: "invoices", payments: "invoices", reports: "invoices", profit: "invoices", expenses: "invoices", staff: "team", people: "team", time: "payroll", timesheets: "payroll", dispatch: "workers", routes: "workers", areas: "workers", worker: "workers", accounting: "xero", sync: "xero", integrations: "xero", launchcontrol: "settings", security: "settings", businessbranding: "settings", billing: "plans", help: "support" };
const titles = {
  aiguide: ["AI Guide", "This week, needs attention, quick actions, messages and quiet admin rules."],
  command: ["Command", "Owner approval desk. Approve, edit or park prepared admin."],
  jobs: ["Jobs", "Job cards, prices, dates, workers, recurring work, proof and job notes."],
  clients: ["Clients", "Client records, service memory, saved prices and job history."],
  quotes: ["Quotes", "Draft quotes, scopes, prices, terms, follow-ups and owner-approved sending."],
  invoices: ["Invoices", "Draft invoices, line items, evidence, paid status and guarded accounting handoff."],
  team: ["Team", "People, roles, access, invites and worker app status."],
  payroll: ["Payroll", "Timesheets, worker slips and pay-period review. No tax filing. No bank payout files."],
  workers: ["Workers", "Map, clock status, proof, messages, route view and daily slips."],
  xero: ["Xero", "Draft sync only. Owner-approved accounting handoff."],
  settings: ["Settings", "Business profile, GST, branding, imports, security and account controls."],
  plans: ["Plans", "Locked Churvox pricing and add-ons."],
  support: ["Support", "Setup help, short guides and contact options."],
};
const options = { repeat: ["One-off", "Weekly", "Fortnightly", "Monthly", "Custom"], status: ["Assigned", "Acknowledged", "In progress", "Proof ready", "Completed", "Needs check", "Quote draft"], quoteStatus: ["Draft", "Sent", "Viewed", "Accepted", "Follow-up due"], invoiceStatus: ["Draft", "Due today", "Overdue", "Paid", "Ready draft"], service: ["Lawn mowing", "Hedge trimming", "Garden tidy", "Property reset", "Cleanup", "Quote visit", "Other"], billing: ["Fixed price", "Hourly", "Fixed + extras", "Hourly + extras", "Package price", "Quote required"], role: ["Owner", "Manager", "Worker", "Subcontractor", "Payroll only"], access: ["Full access", "Jobs only", "Worker app", "Payroll review", "No access"] };
const metrics = [["Today", "4 jobs", "Two ready, one issue, one complete"], ["This week", "$1,480", "Draft work Churvox can prepare"], ["Needs attention", "5", "Owner decisions only"], ["Invoices", "2 drafts", "No automatic sending"]];
const commandRecords = [
  { type: "command", title: "Approve garden reset quote", client: "Robert K", price: "$190", amount: "$190", status: "Approval", date: "Today", worker: "Howard", repeat: "One-off", service: "Property reset", billing: "Fixed price", evidence: "Scope prepared, customer asked for green waste included.", owner: "Approve", note: "Scope and price prepared. Owner can approve, edit the slip, or park it.", slip: ["Client confirmed overgrown reset", "Green waste included", "Photos required before invoice"] },
  { type: "command", title: "Review invoice draft", client: "Lisa M", price: "$85", amount: "$85", status: "Approval", date: "Due today", worker: "Worker account", repeat: "Fortnightly", service: "Lawn mowing", billing: "Fixed price", evidence: "Worker proof ready. Invoice stays draft until approved.", owner: "Approve", note: "Ready to send after owner check. Churvox will not send this automatically.", slip: ["Mow, edges, blower tidy", "Before and after photos attached", "Draft invoice only"] },
  { type: "command", title: "Changed job price", client: "Garden tidy", price: "$140", amount: "$140", status: "Edit needed", date: "Today", worker: "Howard", repeat: "One-off", service: "Garden tidy", billing: "Fixed + extras", evidence: "Original price was $120. Green waste was added.", owner: "Edit", note: "Churvox found a price change and sent it here instead of hiding it in Jobs.", slip: ["Original price was $120", "Green waste added", "Needs owner decision"] },
  { type: "message", title: "Worker message needs answer", client: "Mere H", price: "$120", amount: "$120", status: "Message", date: "This afternoon", worker: "Worker account", repeat: "Monthly", channel: "Worker app", priority: "Owner decision", detail: "Should I trim the side hedge as well or just the front?", draft: "Please do the front hedge only for now. I will confirm the side hedge with the customer.", note: "Worker asked whether to trim the side hedge. Reply or park for later.", slip: ["Message from worker", "Customer is home after 2pm", "Decision required before starting"] },
  { type: "command", title: "Recurring date conflict", client: "Naenae regular", price: "$65", amount: "$65", status: "Schedule", date: "Friday", worker: "Unassigned", repeat: "Fortnightly", service: "Lawn mowing", billing: "Fixed price", owner: "Park", evidence: "Fortnightly cycle clashes with a booked reset.", note: "The next repeat clashes with another job. Command keeps the owner in control.", slip: ["Fortnightly cycle detected", "Worker unavailable", "Move date or assign another worker"] },
];
const jobs = [
  { type: "job", title: "Lawn care - Birchville", client: "Lisa M", price: "$85", amount: "$85", status: "Ready", date: "Today", time: "10:30", duration: "1.5h", worker: "Worker account", repeat: "Fortnightly", address: "Birchville, Lower Hutt, New Zealand", service: "Lawn mowing", billing: "Fixed price", proof: "Before/after photos required before complete", issue: "No issue", note: "Mow, edges, blower tidy. Worker proof required before invoice draft." },
  { type: "job", title: "Garden tidy - Naenae", client: "Robert K", price: "$140", amount: "$140", status: "Needs approval", date: "Tomorrow", time: "9:00", duration: "2h", worker: "Howard", repeat: "One-off", address: "Naenae, Lower Hutt, New Zealand", service: "Garden tidy", billing: "Fixed + extras", proof: "Photos needed because price changed", issue: "Price change sent to Command", note: "Green waste and garden reset. Price change has been sent to Command." },
  { type: "job", title: "Hedge trim - Wainuiomata", client: "Mere H", price: "$120", amount: "$120", status: "Booked", date: "Friday", time: "1:00", duration: "2h", worker: "Worker account", repeat: "Monthly", address: "Wainuiomata, Lower Hutt, New Zealand", service: "Hedge trimming", billing: "Fixed price", proof: "Before and after photos required", issue: "Side hedge question waiting in Command", note: "Before and after photos required. Customer prefers afternoon." },
  { type: "job", title: "Regular mow - Belmont", client: "Sam T", price: "$65", amount: "$65", status: "Assigned", date: "Monday", time: "11:00", duration: "1h", worker: "Cam", repeat: "Fortnightly", address: "Belmont, Lower Hutt, New Zealand", service: "Lawn mowing", billing: "Fixed price", proof: "Complete photo before invoice", issue: "No issue", note: "Saved service memory: mow, line trim, blow paths, text when complete." },
];
const clients = [
  { type: "client", title: "Lisa M", client: "Birchville", name: "Lisa M", phone: "Not added yet", email: "Not added yet", price: "$85 saved", status: "Active", date: "Fortnightly", worker: "Worker account", repeat: "Fortnightly", address: "Birchville, Lower Hutt, New Zealand", service: "Lawn mowing", note: "Lawn mow + edges. Saved price, service memory and invoice history.", history: ["Last job completed", "Invoice draft ready", "Next job booked"] },
  { type: "client", title: "Robert K", client: "Naenae", name: "Robert K", phone: "Not added yet", email: "Not added yet", price: "$190 quote", status: "Quote ready", date: "One-off", worker: "Howard", repeat: "One-off", address: "Naenae, Lower Hutt, New Zealand", service: "Property reset", note: "Garden tidy, green waste and reset notes. Waiting in Command.", history: ["Quote prepared", "Price change flagged", "Owner decision needed"] },
  { type: "client", title: "Mere H", client: "Wainuiomata", name: "Mere H", phone: "Not added yet", email: "Not added yet", price: "$120 saved", status: "Active", date: "Monthly", worker: "Worker account", repeat: "Monthly", address: "Wainuiomata, Lower Hutt, New Zealand", service: "Hedge trimming", note: "Hedge trim, tidy and photo proof before complete.", history: ["Monthly service", "Customer prefers afternoons", "Proof required"] },
];
const quotes = [
  { type: "quote", title: "Garden reset quote", client: "Robert K", price: "$190", amount: "$190", status: "Draft", date: "Prepared today", worker: "Howard", repeat: "One-off", scope: "Overgrown reset, green waste, tidy and photo proof.", terms: "Owner approval before sending. Quote valid for 14 days.", followUp: "Follow up tomorrow if not accepted.", next: "Send to Command for approval", note: "Scope, price and follow-up are ready for Command approval." },
  { type: "quote", title: "Monthly maintenance", client: "Mere H", price: "$120", amount: "$120", status: "Viewed", date: "Follow-up due", worker: "Worker account", repeat: "Monthly", scope: "Monthly hedge trim and tidy.", terms: "Monthly service, owner approval before follow-up.", followUp: "Polite follow-up prepared.", next: "Owner approves follow-up", note: "Churvox prepared a polite follow-up. Owner approves before sending." },
  { type: "quote", title: "Commercial tidy", client: "Focus Landscaping", price: "$420", amount: "$420", status: "Draft", date: "This week", worker: "Cam", repeat: "Weekly", scope: "Weekly site tidy, photos and simple completion notes.", terms: "Weekly schedule. First job owner approved.", followUp: "Check after first visit.", next: "Prepare job after acceptance", note: "Weekly site tidy quote with scope, dates and owner approval required." },
];
const invoices = [
  { type: "invoice", title: "INV-1042", client: "Lisa M", job: "Lawn care - Birchville", price: "$85", amount: "$85", status: "Draft", date: "Due today", due: "7 days", worker: "Worker account", repeat: "Fortnightly", line: "Lawn mowing, edging and blower tidy", evidence: "Worker proof ready", sync: "Waiting for owner approval before draft sync", note: "Review before sending. No automatic invoice sending." },
  { type: "invoice", title: "INV-1041", client: "Straightforward Lawn Care", job: "Regular mow - Belmont", price: "$65", amount: "$65", status: "Paid", date: "Paid after refresh", due: "Paid", worker: "Howard", repeat: "Fortnightly", line: "Regular mowing service", evidence: "Accounting refresh confirmed paid", sync: "Paid confirmed by accounting refresh", note: "Only marked paid after accounting refresh confirms paid." },
  { type: "invoice", title: "INV-1040", client: "Mere H", job: "Hedge trim - Wainuiomata", price: "$120", amount: "$120", status: "Ready draft", date: "Friday", due: "7 days after approval", worker: "Worker account", repeat: "Monthly", line: "Monthly hedge trim and tidy", evidence: "Proof required before draft sync", sync: "Draft only, no auto-send", note: "Draft created from job slip after proof is checked by owner." },
];
const team = [
  { type: "person", title: "Howard", client: "Owner", name: "Howard", email: "hello@churvox.com", price: "Full access", status: "Active", date: "Command access", worker: "Owner", role: "Owner", access: "Full access", app: "Owner app", payroll: "Owner review", repeat: "N/A", note: "Command, settings, billing, approvals and accounting controls." },
  { type: "worker", title: "Worker account", client: "Field worker", name: "Worker account", email: "worker@example.com", price: "Worker app", status: "Invited", date: "Mobile access", worker: "Worker", role: "Worker", access: "Worker app", app: "Invite sent", payroll: "Clock proof required", repeat: "N/A", note: "Jobs, proof, messages, clock status and daily slips only." },
  { type: "worker", title: "Cam", client: "Subcontractor", name: "Cam", email: "cam@example.com", price: "Limited", status: "Pending", date: "Invite ready", worker: "Field worker", role: "Subcontractor", access: "Jobs only", app: "Pending invite", payroll: "Pending invite", repeat: "N/A", note: "Can see assigned jobs only after invite is accepted." },
];
const workerSlips = [
  { type: "worker", title: "Birchville daily slip", client: "Lisa M", price: "$85", status: "Clocked in", date: "10:30", worker: "Worker account", name: "Worker account", role: "Worker", access: "Worker app", repeat: "Fortnightly", address: "Birchville, Lower Hutt, New Zealand", gps: "Birchville, Lower Hutt, New Zealand", start: "10:30", end: "Still working", breakTime: "Not set", timesheet: "1.2h so far", proof: "Before photo required, after photo pending", messages: "Side gate locked, customer messaged", slip: "Feeds payroll review", note: "GPS near site. Photos required before complete. Message thread open." },
  { type: "worker", title: "Naenae issue slip", client: "Robert K", price: "$140", status: "Sent to Command", date: "Tomorrow", worker: "Howard", name: "Howard", role: "Owner", access: "Full access", repeat: "One-off", address: "Naenae, Lower Hutt, New Zealand", gps: "Naenae, Lower Hutt, New Zealand", start: "9:00 planned", end: "Not started", breakTime: "N/A", timesheet: "No time yet", proof: "Photos required because price changed", messages: "Price change parked in Command", slip: "Waiting for owner decision", note: "Issue goes to Command. Jobs stays clean and the owner decides." },
];
const messages = [
  { type: "message", title: "Side hedge question", from: "Worker account", client: "Mere H", job: "Hedge trim - Wainuiomata", channel: "Worker app", priority: "Owner decision", status: "Waiting", date: "Today", detail: "Should I trim the side hedge as well or just the front?", draft: "Please do the front hedge only for now. I will confirm the side hedge with the customer.", history: "Worker asked from site before starting.", note: "Message is in Command so the job page stays clean." },
  { type: "message", title: "Customer wants tomorrow", from: "Lisa M", client: "Lisa M", job: "Lawn care - Birchville", channel: "Customer message", priority: "Schedule", status: "Draft reply", date: "Today", detail: "Could you come tomorrow instead of today?", draft: "No problem, I can move the lawn care to tomorrow morning.", history: "Recurring customer, fortnightly mow.", note: "Churvox prepares the reply, owner approves before sending." },
];
const payrollRows = [["Howard", "18.5h", "$0 draft", "Owner review", "2 adjusted slips"], ["Worker account", "22.0h", "$0 draft", "Clock proof", "5 photo slips"], ["Cam", "6.0h", "$0 draft", "Pending invite", "1 assigned job"]];
const plans = [["Start", "$39", "For a solo owner starting clean.", ["Clients", "Jobs", "Quotes", "Invoices"]], ["Crew", "$89", "For a small crew that needs jobs, clients and workers.", ["Team access", "Worker slips", "Recurring jobs", "Command basics"]], ["Operator", "$149", "Most Popular. Churvox prepares more admin for approval.", ["AI admin preparation", "Approval desk", "Follow-ups", "Better daily control"]], ["Command", "$299", "Full approval desk, scale and accounting handoff.", ["Xero/MYOB draft sync", "Advanced controls", "Scale features", "Owner guardrails"]], ["Growth Pack", "$99", "Adds 50 active team members and extra capacity.", ["50 active team members", "Extra job capacity", "More AI actions", "More automation capacity"]], ["Accounting Add-on", "$39", "For non-Command tiers that need accounting handoff.", ["Draft sync only", "No auto-send", "No tax filing", "No payout files"]]];
const actionSets = { command: ["Approve selected", "Edit selected", "Park selected", "Limit waiting list to 5"], jobs: ["Add job", "Recurring setup", "Assign worker", "Open editable form"], clients: ["Add client", "CSV import", "Open client form", "View job history"], quotes: ["Create quote", "Follow up", "Convert to job", "Send after approval"], invoices: ["Create invoice", "Review draft", "Sync draft", "Refresh paid status"], team: ["Add person", "Invite worker", "Set access", "Worker app status"], payroll: ["Weekly", "Fortnightly", "Monthly", "CSV export"], workers: ["Open map", "Send message", "Review proof", "Daily slips"], xero: ["Check status", "Draft sync", "Refresh payments", "Disconnect"], settings: ["Save profile", "Upload logo", "Import clients", "Security"], plans: ["Choose plan", "Add growth pack", "Accounting add-on"], support: ["Setup guide", "Contact help", "Report issue"] };
function startPage(){ if(typeof window === "undefined") return "aiguide"; const path = window.location.pathname.replace(/^\/+/, "").split("/")[0].toLowerCase(); const hash = window.location.hash.replace(/^#/, "").toLowerCase(); const raw = hash || path; return aliases[raw] || (nav.map(cleanKey).includes(raw) ? raw : "aiguide"); }
function ActionStrip({ page, items }) { const list = items || actionSets[page] || []; return <div className="cvxActions">{list.map((item, index) => <button key={item} type="button"><b>{index === 0 ? "+" : index === 1 ? "✓" : "•"}</b>{item}</button>)}</div>; }
function Panel({ eyebrow, title, children, wide, className }) { return <section className={`cvxPanel ${wide ? "cvxWide" : ""} ${className || ""}`}><p className="cvxEyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>; }
function Metrics({ items }) { return <div className="cvxMetrics">{items.map(([label, value, text]) => <article key={label}><span>{label}</span><b>{value}</b><small>{text}</small></article>)}</div>; }
function RecordCard({ item, onOpen }) { return <button className="cvxRecordCard" type="button" onClick={() => onOpen(item)}><span className="cvxPill">{item.status}</span><h3>{item.title}</h3><p>{item.note}</p><div className="cvxRecordMeta"><b>{item.client || item.from}</b><strong>{item.price || item.amount || ""}</strong><small>{item.date}</small><small>{item.repeat || item.channel || item.access}</small></div></button>; }
function RecordGrid({ items, onOpen, limited }) { return <div className={`cvxRecordGrid ${limited ? "cvxLimited" : ""}`}>{items.map((item) => <RecordCard key={`${item.title}-${item.client || item.from}`} item={item} onOpen={onOpen} />)}</div>; }
function MiniList({ items }) { return <div className="cvxMiniList">{items.map((item) => <div key={Array.isArray(item) ? item.join("-") : item}><b>{Array.isArray(item) ? item[0] : item}</b>{Array.isArray(item) && <span>{item.slice(1).join(" · ")}</span>}</div>)}</div>; }
function FieldForm({ fields, button }) { return <div className="cvxFormGrid">{fields.map(([label, value, type, choices]) => <label key={label}>{label}{type === "textarea" ? <textarea defaultValue={value} /> : type === "select" ? <select defaultValue={value}>{(choices || options.repeat).map((choice) => <option key={choice}>{choice}</option>)}</select> : <input defaultValue={value} />}</label>)}<button type="button">{button || "Save locally"}</button></div>; }
function GoogleMap({ query, label = "Google Maps" }) { const q = query || "Lower Hutt Wellington New Zealand"; const src = `https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`; const search = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`; return <div className="cvxGoogleMap"><iframe title={label} src={src} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><a href={search} target="_blank" rel="noreferrer">Open in Google Maps</a></div>; }
function ProofGrid(){ return <div className="cvxProofGrid"><article><b>Before photo</b><span>Required before completing selected jobs.</span></article><article><b>After photo</b><span>Attached to job, invoice and client history.</span></article><article><b>Issue photo</b><span>Anything unclear goes to Command for owner decision.</span></article></div>; }
function detailFields(item){ const type = item?.type || "record"; if(type === "client") return [["title","Name","text"],["phone","Phone","text"],["email","Email","text"],["address","Address","text"],["service","Preferred service","select",options.service],["price","Saved price","text"],["repeat","Preferred schedule","select",options.repeat],["note","Access notes","textarea"]]; if(type === "worker" || type === "person") return [["name","Worker / person","text"],["role","Role","select",options.role],["access","Access","select",options.access],["email","Phone / email","text"],["status","Clock status","text"],["title","Current job","text"],["gps","GPS / location","text"],["start","Clock in","text"],["end","Clock out","text"],["breakTime","Break","text"],["proof","Proof / photos","text"],["messages","Worker messages","text"],["timesheet","Timesheet","text"],["slip","Slip / payroll status","text"],["note","Day notes","textarea"]]; if(type === "quote") return [["title","Quote","text"],["client","Client","text"],["amount","Amount","text"],["status","Status","select",options.quoteStatus],["scope","Scope","textarea"],["terms","Terms","textarea"],["followUp","Follow-up","text"],["next","Next step","text"],["note","Notes","textarea"]]; if(type === "invoice") return [["title","Invoice","text"],["client","Client","text"],["job","Job","text"],["amount","Amount","text"],["due","Due date","text"],["status","Status","select",options.invoiceStatus],["sync","Xero/MYOB status","text"],["line","Line item","textarea"],["evidence","Evidence","textarea"],["note","Notes","textarea"]]; if(type === "message") return [["from","From","text"],["channel","Channel","text"],["client","Client","text"],["job","Job","text"],["title","Subject","text"],["priority","Priority","text"],["history","History","textarea"],["detail","Message","textarea"],["draft","Drafted reply","textarea"],["note","Owner note","textarea"]]; if(type === "command") return [["title","Record","text"],["client","Client","text"],["amount","Amount","text"],["status","Prepared status","text"],["owner","Recommended action","select",["Approve","Edit","Park"]],["service","Service","select",options.service],["billing","Billing","select",options.billing],["evidence","Evidence checked","textarea"],["note","What Churvox filled","textarea"]]; return [["title","Job name","text"],["client","Client","text"],["address","Site address","text"],["service","Service","select",options.service],["worker","Assigned worker","text"],["date","Scheduled date","text"],["time","Start time","text"],["duration","Estimated duration","text"],["amount","Price NZD","text"],["billing","Billing type","select",options.billing],["repeat","Frequency","select",options.repeat],["status","Status","select",options.status],["proof","Proof/photos","text"],["issue","Issue status","text"],["note","Job notes","textarea"]]; }
function Drawer({ item, page, onClose }) { const [form, setForm] = React.useState(item || {}); React.useEffect(() => setForm(item || {}), [item]); if(!item) return null; const fields = detailFields(item); const commandMode = page === "command" || item.type === "command" || item.type === "message"; const set=(field,value)=>setForm((current)=>({...current,[field]:value})); return <aside className="cvxDrawer"><button className="cvxClose" type="button" onClick={onClose}>Close</button><p className="cvxEyebrow">{commandMode ? "Owner decision slip" : "Editable record form"}</p><h2>{form.title || form.name}</h2><div className="cvxDrawerFields">{fields.map(([key,label,type,choices])=><label key={key} className={type === "textarea" ? "cvxFullField" : ""}>{label}{type === "textarea" ? <textarea value={form[key] || ""} onChange={(event)=>set(key,event.target.value)} /> : type === "select" ? <select value={form[key] || ""} onChange={(event)=>set(key,event.target.value)}><option value="">Select</option>{(choices || []).map((choice)=><option key={choice} value={choice}>{choice}</option>)}</select> : <input value={form[key] || ""} onChange={(event)=>set(key,event.target.value)} />}</label>)}</div>{(form.slip || form.history) && <div className="cvxSlipBox"><b>{form.slip ? "Prepared slip" : "History"}</b><ul>{(form.slip || form.history || []).map((line)=><li key={line}>{line}</li>)}</ul></div>}<div className="cvxDrawerActions">{commandMode ? <><button type="button">Approve</button><button type="button">Edit</button><button type="button">Park</button></> : <><button type="button">Save form</button><button type="button">Send issue to Command</button></>}</div><small>Clean frontend only. Backend wiring comes after these screens are approved.</small></aside>; }
function AIGuide(){ return <div className="cvxPageGrid"><Panel eyebrow="This week" title="Business pulse" wide><Metrics items={metrics} /></Panel><Panel eyebrow="Needs attention" title="Owner decisions"><MiniList items={[["Quote","Robert K reset quote needs approval"],["Invoice","Lisa M draft ready to review"],["Worker","Side hedge question sent to Command"],["Recurring","Friday conflict needs moving"]]} /></Panel><Panel eyebrow="Quick actions" title="Start the admin"><ActionStrip items={["Add job","Add client","Create quote","Create invoice","Open Command","Import clients"]} /></Panel><Panel eyebrow="Messages" title="Worker and customer threads"><MiniList items={messages.map((message)=>[message.title,message.client,message.status])} /></Panel><Panel eyebrow="Proof" title="Photos and evidence"><ProofGrid /></Panel><Panel eyebrow="Quiet admin rules" title="Churvox does the admin. You approve."><ul className="cvxRules"><li>Issues go to Command, not hidden inside Jobs.</li><li>Draft quotes and invoices wait for owner approval.</li><li>Recurring work is saved on the job form.</li><li>Paid is only updated after accounting refresh confirms paid.</li></ul></Panel></div>; }
function CommandPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="Decision desk" title="Waiting for owner" wide><RecordGrid items={commandRecords} onOpen={open} limited /></Panel><Panel eyebrow="Command controls" title="Approve, edit or park"><ActionStrip page="command" /><p className="cvxNotice">Only Command shows approval actions. Other pages send issues here.</p></Panel><Panel eyebrow="Prepared slip" title="What the owner sees"><FieldForm button="Save prepared slip locally" fields={[["Client","Lisa M"],["Job","Lawn care - Birchville"],["Price","$85"],["Date","Today"],["Time","10:30"],["Worker","Worker account"],["Repeat","Fortnightly","select",options.repeat],["Evidence","Before and after photos attached","textarea"]]} /></Panel><Panel eyebrow="Messages" title="Replies waiting for approval" wide><RecordGrid items={messages} onOpen={open} /></Panel></div>; }
function JobsPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="Job board" title="Saved jobs" wide><RecordGrid items={jobs} onOpen={open} /></Panel><Panel eyebrow="Add / edit job" title="Full job form"><FieldForm button="Save job locally" fields={[["Client","Lisa M"],["Job title","Lawn care - Birchville"],["Service","Lawn mowing","select",options.service],["Billing","Fixed price","select",options.billing],["Price","$85"],["Date","Today"],["Time","10:30"],["Duration","1.5h"],["Worker","Worker account"],["Repeat","Fortnightly","select",options.repeat],["Proof/photos","Before and after required"],["Notes","Mow, edges, blower tidy","textarea"]]} /></Panel><Panel eyebrow="Proof" title="Photos and issue flow"><ProofGrid /></Panel><Panel eyebrow="Rules" title="Keep Jobs clean"><ul className="cvxRules"><li>Jobs is for the work, not owner problems.</li><li>Any price, proof, message or schedule issue goes to Command.</li><li>Recurring stays on the job form: weekly, fortnightly, monthly or custom.</li></ul></Panel></div>; }
function ClientsPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="Client records" title="Saved clients" wide><RecordGrid items={clients} onOpen={open} /></Panel><Panel eyebrow="Add client" title="Client form"><FieldForm button="Save client locally" fields={[["Name","New client"],["Phone",""] ,["Email",""] ,["Address",""] ,["Preferred service","Lawn mowing","select",options.service],["Default price",""] ,["Default repeat","Fortnightly","select",options.repeat],["Access notes","","textarea"]]} /></Panel><Panel eyebrow="CSV import" title="Bring clients in"><p className="cvxNotice">Import area stays visible here so it does not get lost.</p><ActionStrip items={["Choose CSV","Check headers","Import clients"]} /></Panel><Panel eyebrow="Job history" title="Client memory" wide><MiniList items={clients.map((client)=>[client.title,...(client.history || [])])} /></Panel></div>; }
function QuotesPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="Quote drafts" title="Ready for owner" wide><RecordGrid items={quotes} onOpen={open} /></Panel><Panel eyebrow="Create quote" title="Scope, terms and price"><FieldForm button="Prepare quote" fields={[["Client","Robert K"],["Scope","Garden reset","textarea"],["Price","$190"],["Terms","Valid for 14 days","textarea"],["Follow-up date","Tomorrow"],["Convert repeat","One-off","select",options.repeat]]} /></Panel><Panel eyebrow="Follow-up" title="Churvox prepares it"><MiniList items={[["Draft reply","Polite follow-up waits for owner approval"],["Convert to job","Only after quote is accepted"],["Send rule","No automatic sending"]]} /></Panel></div>; }
function InvoicesPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="Invoice drafts" title="Review before sending" wide><RecordGrid items={invoices} onOpen={open} /></Panel><Panel eyebrow="Create invoice" title="From job slip"><FieldForm button="Prepare invoice" fields={[["Client","Lisa M"],["Job","Lawn care - Birchville"],["Amount","$85"],["Line item","Lawn mowing, edges and blower tidy","textarea"],["Evidence","Worker proof ready","textarea"],["Due date","7 days"],["Status","Draft","select",options.invoiceStatus]]} /></Panel><Panel eyebrow="Paid guardrail" title="No false paid status"><ul className="cvxRules"><li>No automatic invoice sending.</li><li>No paid marking from a button alone.</li><li>Paid only after Xero/MYOB refresh confirms paid.</li><li>Draft sync only after owner approval.</li></ul></Panel></div>; }
function TeamPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="People" title="Team and access" wide><RecordGrid items={team} onOpen={open} /></Panel><Panel eyebrow="Invite" title="Add worker"><FieldForm button="Send invite locally" fields={[["Name","New worker"],["Email",""] ,["Role","Worker","select",options.role],["Access","Worker app","select",options.access],["Phone",""] ,["Notes","","textarea"]]} /></Panel><Panel eyebrow="Access rules" title="Keep roles simple"><MiniList items={[["Owner","Command, settings, billing, approvals"],["Worker","Assigned jobs, photos, messages, clock"],["Payroll","Pay review only, no reports unless allowed"]]} /></Panel></div>; }
function PayrollPage(){ return <div className="cvxPageGrid"><Panel eyebrow="Pay period" title="Review only"><ActionStrip page="payroll" /><p className="cvxNotice">Payroll is review/export only. No tax filing and no bank payout files.</p></Panel><Panel eyebrow="This period" title="Worker hours" wide><div className="cvxTable">{payrollRows.map(([name,hours,pay,status,proof])=><div key={name}><b>{name}</b><span>{hours}</span><span>{pay}</span><small>{status}</small><small>{proof}</small></div>)}</div></Panel><Panel eyebrow="Worker slips" title="Clock proof feeds payroll" wide><RecordGrid items={workerSlips} onOpen={() => {}} /></Panel></div>; }
function WorkersPage({ open }){ return <div className="cvxPageGrid"><Panel eyebrow="GPS map" title="Worker route view" wide><GoogleMap query="Birchville Naenae Wainuiomata Belmont Lower Hutt New Zealand" label="Churvox worker route map" /></Panel><Panel eyebrow="Daily slips" title="Clock, proof and messages" wide><RecordGrid items={workerSlips} onOpen={open} /></Panel><Panel eyebrow="Proof" title="Photos before complete"><ProofGrid /></Panel><Panel eyebrow="Messages" title="Sent to Command"><MiniList items={[["Issue","Worker questions become owner decisions"],["Photos","Before and after proof stays with the job"],["Clock","Start, pause, resume and complete feeds payroll review"]]} /></Panel></div>; }
function XeroPage(){ return <div className="cvxPageGrid"><Panel eyebrow="Guarded sync" title="Xero / MYOB handoff"><ActionStrip page="xero" /><ul className="cvxRules"><li>Draft invoice sync only.</li><li>Owner approval required.</li><li>No automatic invoice sending.</li><li>No tax filing.</li><li>No bank payout files.</li></ul></Panel><Panel eyebrow="Payment refresh" title="Paid only when confirmed"><p className="cvxNotice">Paid status only changes after accounting refresh confirms paid.</p><Metrics items={[["Connection","Later","Frontend first"],["Draft sync","Guarded","Owner approved"],["Paid status","Refresh","Accounting confirms"],["Safety","Locked","No auto-send"]]} /></Panel></div>; }
function SettingsPage(){ return <div className="cvxPageGrid"><Panel eyebrow="Business profile" title="Brand and defaults" wide><FieldForm button="Save settings locally" fields={[["Business name","Churvox"],["Owner email","hello@churvox.com"],["GST rate","15"],["Country","NZ"],["Default repeat","Fortnightly","select",options.repeat],["Default billing","Fixed price","select",options.billing],["Logo","Not uploaded"],["Notifications","On"]]} /></Panel><Panel eyebrow="Imports" title="CSV and records"><MiniList items={[["Clients CSV","Visible from Settings and Clients"],["Team CSV","Invite workers from a file later"],["Invoice export","Bookkeeper CSV stays guarded"]]} /></Panel><Panel eyebrow="Security" title="Account controls"><MiniList items={[["Email verification","Required before live use"],["Forgot password","Email service wiring later"],["Delete account","Control comes back when backend wiring starts"],["Business isolation","Each business stays separate"]]} /></Panel></div>; }
function PlansPage(){ return <div className="cvxPlans">{plans.map(([name,price,text,bullets])=><section key={name} className={name === "Operator" ? "cvxPopularPlan" : ""}>{name === "Operator" && <em>Most Popular</em>}<p className="cvxEyebrow">{name}</p><h2>{price}<small>/month + GST</small></h2><span>{text}</span><ul>{bullets.map((line)=><li key={line}>{line}</li>)}</ul></section>)}</div>; }
function SupportPage(){ return <div className="cvxPageGrid"><Panel eyebrow="Help" title="Churvox setup"><MiniList items={[["Start","Add clients and jobs"],["Command","Approve what Churvox prepares"],["Workers","Use slips, map, proof and messages"],["Accounting","Keep draft sync guarded"]]} /></Panel><Panel eyebrow="Contact" title="hello@churvox.com"><p className="cvxNotice">Support wiring comes after the clean frontend is stable.</p></Panel><Panel eyebrow="Guides" title="What each page is for"><ul className="cvxRules"><li>AI Guide shows the business pulse.</li><li>Command is the owner approval desk.</li><li>Jobs and Clients hold the real work forms.</li><li>Workers is where map, proof and messages live.</li></ul></Panel></div>; }
function Page({ page, open }){ if(page === "aiguide") return <AIGuide />; if(page === "command") return <CommandPage open={open} />; if(page === "jobs") return <JobsPage open={open} />; if(page === "clients") return <ClientsPage open={open} />; if(page === "quotes") return <QuotesPage open={open} />; if(page === "invoices") return <InvoicesPage open={open} />; if(page === "team") return <TeamPage open={open} />; if(page === "payroll") return <PayrollPage />; if(page === "workers") return <WorkersPage open={open} />; if(page === "xero") return <XeroPage />; if(page === "settings") return <SettingsPage />; if(page === "plans") return <PlansPage />; return <SupportPage />; }
export default function FreshApp(){ const [page,setPage]=React.useState(startPage); const [selected,setSelected]=React.useState(null); const [title,sub]=titles[page] || titles.aiguide; React.useEffect(()=>{ const onHash=()=>setPage(startPage()); window.addEventListener("hashchange",onHash); return ()=>window.removeEventListener("hashchange",onHash); },[]); const go=(next)=>{ setPage(next); setSelected(null); if(typeof window !== "undefined") window.history.replaceState({},"",`/dashboard#${next}`); }; return <main className="cvxClean"><div className="cvxCleanShell"><header className="cvxCleanTop"><div className="cvxCleanHead"><div className="cvxCleanBrand"><span className="cvxCleanMark" /><span><b>Churvox</b><small>does the admin</small></span></div><div className="cvxCleanTitle"><h1>{title}</h1><p>{sub}</p></div><a className="cvxCleanLogout" href="/login">Log out</a></div><nav className="cvxCleanNav" aria-label="Churvox pages">{nav.map((item)=>{ const next=cleanKey(item); return <button key={item} type="button" className={page === next ? "active" : ""} onClick={()=>go(next)}>{item}</button>; })}</nav></header><section className="cvxCleanWork"><Page page={page} open={setSelected} /></section></div><Drawer item={selected} page={page} onClose={()=>setSelected(null)} /></main>; }
