import React from "react";
import { useApi } from "../hooks/useApi";
import "../churvox-clean/ChurvoxSpecificPages.css";
import "../churvox-clean/ChurvoxHeaderIdentity.css";

const nav = ["AI Guide", "Command", "Jobs", "Clients", "Quotes", "Invoices", "Team", "Payroll", "Workers", "Xero", "Settings", "Plans", "Support"];
const aliases = { dashboard: "aiguide", smart: "aiguide", today: "aiguide", approvals: "command", automation: "command", recurring: "jobs", calendar: "jobs", schedule: "jobs", customers: "clients", payments: "invoices", reports: "invoices", staff: "team", people: "team", timesheets: "payroll", dispatch: "workers", routes: "workers", accounting: "xero", sync: "xero", billing: "plans", help: "support" };
const pageInfo = {
  aiguide: ["AI Guide", "Owner pulse, messages, money due and what Churvox prepared."],
  command: ["Command", "Owner approval desk. Approve, edit or park prepared admin."],
  jobs: ["Jobs", "Job board, schedule, recurring work, proof and job form."],
  clients: ["Clients", "Client database, saved services, prices, CSV import and history."],
  quotes: ["Quotes", "Quote pipeline, scope, terms, follow-up and convert-to-job."],
  invoices: ["Invoices", "Drafts, evidence, line items, paid guardrails and accounting status."],
  team: ["Team", "People, roles, access, invites and worker app status."],
  payroll: ["Payroll", "Timesheets, worker slips and pay review. No tax or payout files."],
  workers: ["Workers", "Map, GPS, clock status, proof, messages and daily slips."],
  xero: ["Xero", "Draft sync only. Owner-approved accounting handoff."],
  settings: ["Settings", "Business profile, branding, GST, imports, security and controls."],
  plans: ["Plans", "Locked Churvox pricing, packs and Accounting Sync add-on."],
  support: ["Support", "Setup help, short guides and contact options."],
};
const choices = { repeat: ["One-off", "Weekly", "Fortnightly", "Monthly", "Custom"], service: ["Lawn mowing", "Hedge trimming", "Garden tidy", "Property reset", "Cleaning", "Pest control", "Other"], billing: ["Fixed price", "Hourly", "Fixed + extras", "Hourly + extras", "Quote required"], role: ["Owner", "Manager", "Worker", "Subcontractor", "Payroll only"], access: ["Full access", "Jobs only", "Worker app", "Payroll review", "No access"], quote: ["Draft", "Sent", "Viewed", "Accepted", "Follow-up due"], invoice: ["Draft", "Sent", "Due", "Overdue", "Paid"] };
const planRows = [
  ["Start", "$39", "Solo owner starting clean.", ["Jobs", "Clients", "Quotes", "Invoices", "Recurring jobs", "Command basics"]],
  ["Crew", "$89", "Small crew and worker flow.", ["Team access", "Worker slips", "Proof/photos", "Time approval", "Recurring jobs"]],
  ["Operator", "$149", "Most Popular. Churvox prepares admin for approval.", ["AI Operator Actions", "Draft quote follow-ups", "Draft invoice prep", "Admin debt/follow-ups", "Owner approval desk"]],
  ["Command", "$299", "Full approval desk, scale and accounting handoff.", ["Accounting Sync included", "Payroll workspace", "Advanced roles", "Imports/exports/reports", "Up to 50 active team members"]],
  ["Command Growth Pack", "$99", "Adds scale when Command grows.", ["Adds 50 active team members", "Extra job capacity", "Extra AI Operator Actions", "More automation capacity"]],
  ["Accounting Sync Add-on", "$39", "For non-Command tiers, where available.", ["Xero or MYOB draft sync", "Owner approved only", "No automatic sending", "No tax filing", "No bank payout files"]],
];
const fallback = {
  jobs: [{ type: "job", title: "Lawn care - Birchville", client: "Lisa M", status: "Ready", price: "$85", date: "Today", time: "10:30", repeat: "Fortnightly", worker: "Worker account", service: "Lawn mowing", billing: "Fixed price", address: "Birchville, Lower Hutt", proof: "Before/after photos required", note: "Mow, edges, blower tidy. Worker proof required before invoice draft." }],
  clients: [{ type: "client", title: "Lisa M", client: "Birchville", status: "Active", price: "$85 saved", date: "Fortnightly", repeat: "Fortnightly", phone: "", email: "", address: "Birchville, Lower Hutt", service: "Lawn mowing", note: "Saved price, service memory and invoice history.", history: ["Last job completed", "Invoice draft ready", "Next job booked"] }],
  quotes: [{ type: "quote", title: "Garden reset quote", client: "Robert K", status: "Draft", price: "$190", date: "Prepared today", scope: "Overgrown reset, green waste and tidy.", terms: "Owner approval before sending.", followUp: "Follow up tomorrow.", note: "Scope, price and follow-up are ready for Command approval." }],
  invoices: [{ type: "invoice", title: "INV-1042", client: "Lisa M", status: "Draft", price: "$85", date: "Due today", job: "Lawn care - Birchville", line: "Lawn mowing, edging and blower tidy", evidence: "Worker proof ready", sync: "Waiting for owner approval before draft sync", note: "Review before sending. No automatic invoice sending." }],
  team: [{ type: "worker", title: "Worker account", client: "Field worker", status: "Invited", price: "Worker app", role: "Worker", access: "Worker app", app: "Invite sent", payroll: "Clock proof required", note: "Jobs, proof, messages, clock status and daily slips only." }],
  messages: [{ type: "message", title: "Side hedge question", client: "Mere H", from: "Worker account", status: "Waiting", channel: "Worker app", detail: "Should I trim the side hedge as well?", draft: "Please do the front hedge only for now.", note: "Message is in Command so the job page stays clean." }],
  command: [{ type: "command", title: "Approve garden reset quote", client: "Robert K", status: "Approval", price: "$190", owner: "Approve", evidence: "Scope prepared from job/client records.", note: "Owner can approve, edit the slip, or park it." }],
};
function k(v) { return String(v || "").toLowerCase().replace(/\s+/g, ""); }
function pageFromUrl() { if (typeof window === "undefined") return "aiguide"; const raw = String(window.location.hash || window.location.pathname || "dashboard").replace("#", "").replace(/^\/+/, "").split("/")[0].toLowerCase(); return aliases[raw] || (nav.map(k).includes(raw) ? raw : "aiguide"); }
function txt(...vals) { for (const v of vals) if (v !== undefined && v !== null && String(v).trim()) return String(v).trim(); return ""; }
function idOf(x) { const v = x?.id || x?._id || x?.job_id || x?.client_id || x?.quote_id || x?.invoice_id || x?.user_id || ""; if (typeof v === "object") return String(v.$oid || v.oid || v.id || v._id || ""); return String(v || ""); }
function dollars(v) { if (typeof v === "string" && v.includes("$")) return v; const n = Number(v || 0); return n ? n.toLocaleString("en-NZ", { style: "currency", currency: "NZD", maximumFractionDigits: 0 }) : ""; }
function rows(res, keyName) { const body = res?.data?.data || res?.data || res; if (Array.isArray(body)) return body; if (Array.isArray(body?.[keyName])) return body[keyName]; for (const key of ["items", "records", "results", "data", "jobs", "clients", "quotes", "invoices", "workers", "team", "messages", "actions", "notifications"]) if (Array.isArray(body?.[key])) return body[key]; return []; }
function job(r, i) { const amount = r.price ?? r.amount ?? r.total; return { ...r, id: idOf(r) || `job-${i}`, type: "job", title: txt(r.title, r.job_title, r.job_name, `Job ${i + 1}`), client: txt(r.client_name, r.customer_name, r.client?.name, r.client, "No client"), status: txt(r.status, r.job_status, "Assigned"), price: dollars(amount), date: txt(r.scheduled_date, r.date, "Not scheduled"), time: txt(r.scheduled_time, r.start_time, r.time, ""), repeat: txt(r.recurring, r.frequency, r.repeat, "One-off"), worker: txt(r.assigned_worker_name, r.worker_name, r.worker?.name, "Unassigned"), service: txt(r.service, r.service_type, "Other"), billing: txt(r.billing, r.billing_type, "Fixed price"), address: txt(r.address, r.site_address, r.location, ""), proof: txt(r.proof, r.photo_status, r.evidence, "Proof not attached"), note: txt(r.notes, r.note, r.description, "Open the form to review this job.") }; }
function client(r, i) { return { ...r, id: idOf(r) || `client-${i}`, type: "client", title: txt(r.name, r.client_name, r.customer_name, `Client ${i + 1}`), client: txt(r.suburb, r.area, r.address, "Client"), status: txt(r.status, "Active"), price: txt(r.default_price, r.saved_price, r.price, ""), date: txt(r.schedule, r.frequency, r.repeat, ""), repeat: txt(r.schedule, r.frequency, r.repeat, "One-off"), phone: txt(r.phone, r.mobile, ""), email: txt(r.email, ""), address: txt(r.address, r.site_address, ""), service: txt(r.service, r.preferred_service, "Other"), note: txt(r.notes, r.note, "Saved client record."), history: ["Job history", "Quotes", "Invoices"] }; }
function quote(r, i) { const amount = r.amount ?? r.total ?? r.price; return { ...r, id: idOf(r) || `quote-${i}`, type: "quote", title: txt(r.title, r.quote_number, r.number, `Quote ${i + 1}`), client: txt(r.client_name, r.customer_name, r.client?.name, r.client, "No client"), status: txt(r.status, "Draft"), price: dollars(amount), date: txt(r.date, r.created_at, "Prepared"), scope: txt(r.scope, r.description, r.notes, "Scope ready for review."), terms: txt(r.terms, "Owner approval before sending."), followUp: txt(r.follow_up, r.followUp, ""), note: txt(r.notes, r.note, r.description, "Quote ready for owner review.") }; }
function invoice(r, i) { const amount = r.amount ?? r.total ?? r.price; return { ...r, id: idOf(r) || `invoice-${i}`, type: "invoice", title: txt(r.invoice_number, r.number, r.title, `Invoice ${i + 1}`), client: txt(r.client_name, r.customer_name, r.client?.name, r.client, "No client"), status: txt(r.status, "Draft"), price: dollars(amount), date: txt(r.due_date, r.date, r.created_at, ""), job: txt(r.job_title, r.job, r.description, ""), line: txt(r.line_item, r.description, r.notes, "Invoice line item"), evidence: txt(r.evidence, r.proof, "Owner review required"), sync: txt(r.accounting_status, r.sync, r.xero_status, "Draft sync only"), note: txt(r.notes, r.note, r.description, "Invoice draft ready for review.") }; }
function worker(r, i) { return { ...r, id: idOf(r) || `worker-${i}`, type: "worker", title: txt(r.name, r.full_name, r.email, r.title, `Worker ${i + 1}`), client: txt(r.role, r.access, "Worker"), status: txt(r.status, r.clock_status, r.invite_status, "Active"), price: txt(r.payroll_status, r.payroll, ""), date: txt(r.current_job, r.job_title, r.app_status, "Worker app"), role: txt(r.role, "Worker"), access: txt(r.access, r.role, "Worker app"), app: txt(r.app_status, r.invite_status, "Worker app"), payroll: txt(r.payroll_status, r.payroll, "Review"), gps: txt(r.gps, r.location, r.address, ""), timesheet: txt(r.timesheet, r.hours_today, r.duration, "0h"), proof: txt(r.proof, r.photo_status, "No proof yet"), messages: txt(r.messages, r.message_status, r.issue, "No messages"), note: txt(r.notes, r.note, "Worker record.") }; }
function message(r, i) { return { ...r, id: idOf(r) || `message-${i}`, type: "message", title: txt(r.subject, r.title, `Message ${i + 1}`), from: txt(r.from, r.type, "Churvox"), client: txt(r.client, r.client_name, "Business"), status: txt(r.status, r.read ? "Read" : "Waiting"), channel: txt(r.channel, "Owner notification"), detail: txt(r.detail, r.message, r.body, "Owner update ready."), draft: txt(r.draft, r.reply, "Review in Command if needed."), note: txt(r.note, r.message, "Message ready for review.") }; }
function command(r, i) { const amount = r.amount ?? r.total ?? r.payload?.amount ?? r.payload?.price; return { ...r, id: idOf(r) || `command-${i}`, type: r.type === "message" ? "message" : "command", title: txt(r.title, r.summary, r.label, "Prepared admin item"), client: txt(r.client, r.client_name, r.customer_name, r.payload?.client_name, "Business"), status: txt(r.status, "Review"), price: dollars(amount), owner: txt(r.owner, r.recommended_action, "Approve"), evidence: txt(r.evidence, r.reason, "Prepared from live business records."), note: txt(r.filled, r.description, r.summary, "Prepared for owner review.") }; }
function useData(api) { const [data, setData] = React.useState({ ...fallback, xero: {}, backend: "loading" }); React.useEffect(() => { let alive = true; async function load() { const res = await Promise.allSettled([api.get("/jobs"), api.get("/clients"), api.get("/quotes"), api.get("/invoices"), api.get("/team"), api.get("/messages"), api.get("/ai/actions"), api.get("/xero/status")]); const next = { jobs: rows(res[0]?.value, "jobs").map(job), clients: rows(res[1]?.value, "clients").map(client), quotes: rows(res[2]?.value, "quotes").map(quote), invoices: rows(res[3]?.value, "invoices").map(invoice), team: rows(res[4]?.value, "team").map(worker), messages: rows(res[5]?.value, "messages").map(message), command: rows(res[6]?.value, "actions").map(command), xero: res[7]?.value?.data?.data || res[7]?.value?.data || {}, backend: "live" }; for (const key of ["jobs", "clients", "quotes", "invoices", "team", "messages", "command"]) if (!next[key].length) next[key] = fallback[key] || []; next.command = [...next.command, ...next.messages.filter((m) => /waiting|unread|draft/i.test(m.status || ""))].slice(0, 12); next.workerSlips = next.team.length ? next.team : next.jobs.map((j, i) => worker({ ...j, id: `slip-${i}`, name: j.worker, title: `${j.client} daily slip`, gps: j.address, timesheet: j.time, proof: j.proof, messages: j.note }, i)); if (alive) setData(next); } load(); return () => { alive = false; }; }, [api]); return data; }
function Panel({ eyebrow, title, children, className = "" }) { return <section className={`chxPanel ${className}`}><div className="chxPanelHead"><small>{eyebrow}</small><h2>{title}</h2></div><div className="chxPanelBody">{children}</div></section>; }
function Mini({ title, text }) { return <div className="chxMini"><b>{title}</b><span>{text}</span></div>; }
function ActionStrip({ items }) { return <div className="chxMiniGrid">{items.map((x) => <button className="chxBtn soft" type="button" key={x}>{x}</button>)}</div>; }
function RecordCard({ item, onOpen }) { return <button type="button" className="chxCard" onClick={() => onOpen(item)}><span className="chxPill">{item.status}</span><h3>{item.title}</h3><p>{item.note}</p><div className="chxMeta"><span>{item.client || item.from}</span><strong>{item.price}</strong><span>{item.date}</span><span>{item.repeat || item.channel || item.access}</span></div></button>; }
function Row({ item, onOpen }) { return <button type="button" className="chxRow" onClick={() => onOpen(item)}><div className="chxRowMain"><span className="chxPill">{item.status}</span><h3>{item.title}</h3><p>{item.note}</p></div><div className="chxRowAside"><strong>{item.price}</strong><span>{item.date || item.repeat}</span></div></button>; }
function Fields({ rows }) { return <div className="chxFields">{rows.map(([label, value, type, list]) => <label key={label} className={type === "textarea" ? "chxFull" : ""}>{label}{type === "select" ? <select defaultValue={value}>{(list || []).map((x) => <option key={x}>{x}</option>)}</select> : type === "textarea" ? <textarea defaultValue={value} /> : <input defaultValue={value || ""} />}</label>)}</div>; }
function Map({ query }) { const q = query || "Lower Hutt New Zealand"; return <div className="chxMap"><iframe title="Worker map" src={`https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`} target="_blank" rel="noreferrer">Open Maps</a></div>; }
function Drawer({ item, onClose }) { if (!item) return null; return <aside className="chxDrawer"><div className="chxDrawerTop"><div><span className="chxPill">{item.type}</span><h2>{item.title}</h2></div><button type="button" className="chxClose" onClick={onClose}>Close</button></div><Fields rows={Object.entries(item).filter(([k, v]) => ["title","client","status","price","date","time","repeat","worker","service","billing","address","proof","evidence","sync","note"].includes(k) && typeof v !== "object").map(([k, v]) => [k, v, k === "note" || k === "evidence" ? "textarea" : "text"])} /><div className="chxDrawerActions"><button className="chxBtn">Save form</button><button className="chxBtn soft">Send issue to Command</button></div><small>Live backend records appear here when available. Command keeps owner approval actions.</small></aside>; }
function Layout({ page, data, open }) { if (page === "aiguide") return <Ai data={data} open={open} />; if (page === "command") return <Command data={data} open={open} />; if (page === "jobs") return <Jobs data={data} open={open} />; if (page === "clients") return <Clients data={data} open={open} />; if (page === "quotes") return <Quotes data={data} open={open} />; if (page === "invoices") return <Invoices data={data} open={open} />; if (page === "team") return <Team data={data} open={open} />; if (page === "payroll") return <Payroll data={data} open={open} />; if (page === "workers") return <Workers data={data} open={open} />; if (page === "xero") return <Xero data={data} />; if (page === "settings") return <Settings />; if (page === "plans") return <Plans />; return <Support />; }
function Ai({ data, open }) { const drafts = data.invoices.filter((x) => /draft|ready/i.test(x.status || "")).length; return <div className="chxScreen chxAi"><Panel eyebrow="Owner pulse" title="Today at a glance" className="pulsePanel"><div className="chxMiniGrid chxPulse"><Mini title={`${data.jobs.length} jobs`} text="Live jobs / today work" /><Mini title={`${data.command.length}`} text="Owner decisions" /><Mini title={`${drafts} drafts`} text="Invoices waiting review" /><Mini title={`${data.messages.length}`} text="Messages surfaced" /></div></Panel><Panel eyebrow="Prepared by Churvox" title="Approval queue"><div className="chxScroll chxCardGrid">{data.command.map((x) => <RecordCard key={x.id} item={x} onOpen={open} />)}</div></Panel><Panel eyebrow="Messages" title="Worker/customer threads"><div className="chxScroll chxRows">{data.messages.map((x) => <Row key={x.id} item={x} onOpen={open} />)}</div></Panel><Panel eyebrow="Quiet rules" title="Churvox does the admin. You approve."><div className="chxMiniGrid"><Mini title="Command owns decisions" text="Approve, edit and park stay in Command." /><Mini title="Draft sync only" text="No auto-send, no tax filing, no payout files." /><Mini title="Proof before invoice" text="Photos/evidence stay with the job and invoice." /></div></Panel></div>; }
function Command({ data, open }) { return <div className="chxScreen chxCommand"><Panel eyebrow="Decision desk" title="Waiting for owner" className="queue"><div className="chxScroll chxCardGrid">{data.command.map((x) => <RecordCard key={x.id} item={x} onOpen={open} />)}</div></Panel><Panel eyebrow="Owner controls" title="Approve, edit or park"><ActionStrip items={["Approve selected", "Edit selected", "Park selected", "Review messages"]} /><p className="chxNotice">Command is the only page with approval actions. Other pages keep work clean.</p></Panel><Panel eyebrow="Messages" title="Needs owner reply"><div className="chxScroll chxRows">{data.messages.map((x) => <Row key={x.id} item={x} onOpen={open} />)}</div></Panel></div>; }
function Jobs({ data, open }) { const today = data.jobs.slice(0, 8), recurring = data.jobs.filter((x) => !/one-off/i.test(x.repeat || "")), upcoming = data.jobs.slice(8); return <div className="chxScreen chxJobs"><Panel eyebrow="Job board" title="Today / Upcoming / Recurring" className="board"><div className="chxJobColumns"><Lane title="Today" rows={today} open={open} /><Lane title="Upcoming" rows={upcoming.length ? upcoming : data.jobs} open={open} /><Lane title="Recurring" rows={recurring.length ? recurring : data.jobs} open={open} /></div></Panel><Panel eyebrow="Job form" title="Add or edit job"><Fields rows={[["Client",""],["Service","Lawn mowing","select",choices.service],["Billing","Fixed price","select",choices.billing],["Price",""],["Date",""],["Time",""],["Worker",""],["Repeat","Fortnightly","select",choices.repeat],["Notes","","textarea"]]} /><button className="chxBtn">Save job</button></Panel><Panel eyebrow="Proof/issues" title="Before invoice"><div className="chxMiniGrid"><Mini title="Before photo" text="Required for selected work." /><Mini title="After photo" text="Feeds invoice evidence." /><Mini title="Issue" text="Quietly routes to Command." /></div></Panel></div>; }
function Lane({ title, rows, open }) { return <div className="chxJobLane"><h3>{title}</h3><div className="chxScroll chxRows">{rows.map((x) => <Row key={`${title}-${x.id}`} item={x} onOpen={open} />)}</div></div>; }
function Clients({ data, open }) { const first = data.clients[0] || {}; return <div className="chxScreen chxClients"><Panel eyebrow="Client database" title="Saved clients" className="clientList"><div className="chxScroll chxClientListRows">{data.clients.map((x) => <button key={x.id} type="button" className="chxRow chxClientRow" onClick={() => open(x)}><div className="chxRowMain"><span className="chxPill">{x.status}</span><h3>{x.title}</h3><p>{x.address || x.note}</p></div><div className="chxRowAside"><strong>{x.price}</strong><span>{x.repeat}</span></div></button>)}</div></Panel><Panel eyebrow="Selected client" title="Client profile"><Fields rows={[["Name", first.title], ["Phone", first.phone], ["Email", first.email], ["Address", first.address], ["Service", first.service, "select", choices.service], ["Saved price", first.price], ["Repeat", first.repeat, "select", choices.repeat], ["Notes", first.note, "textarea"]]} /><button className="chxBtn">Save client</button></Panel><Panel eyebrow="Import/tools" title="CSV and saved work"><div className="chxMiniGrid"><button className="chxBtn soft">Choose CSV</button><button className="chxBtn soft">Check headers</button><button className="chxBtn soft">Import clients</button><Mini title="Saved service" text={first.service || "Service memory"} /><Mini title="Saved price" text={first.price || "Default price"} /></div></Panel><Panel eyebrow="History" title="Jobs, quotes and invoices" className="clientHistory"><div className="chxScroll chxMiniGrid">{data.clients.map((x) => <Mini key={x.id} title={x.title} text={(x.history || [x.service, x.price]).join(" · ")} />)}</div></Panel></div>; }
function Quotes({ data, open }) { return <Pipeline page="chxQuotes" main="pipeline" eyebrow="Quote pipeline" title="Draft / Sent / Viewed / Accepted" rows={data.quotes} open={open} sideTitle="Create quote" sideFields={[["Client",""],["Scope","","textarea"],["Price",""],["Terms","Valid for 14 days","textarea"],["Follow-up",""]]} bottom={<MiniGrid rows={[["Follow-up", "Owner approves before sending."], ["Convert", "Accepted quotes can become jobs."], ["Send rule", "No automatic sending."]]} />} />; }
function Invoices({ data, open }) { return <Pipeline page="chxInvoices" main="invoiceList" eyebrow="Invoice desk" title="Drafts / Due / Paid" rows={data.invoices} open={open} sideTitle="Invoice detail" sideFields={[["Client",""],["Job",""],["Amount",""],["Line item","","textarea"],["Evidence","","textarea"],["Status","Draft","select",choices.invoice]]} bottom={<div className="chxNotice">No automatic invoice sending. Paid only after Xero/MYOB refresh confirms paid.</div>} />; }
function Pipeline({ page, main, eyebrow, title, rows, open, sideTitle, sideFields, bottom }) { return <div className={`chxScreen ${page}`}><Panel eyebrow={eyebrow} title={title} className={main}><div className="chxLanes"><Lane title="Draft" rows={rows.filter((x)=>/draft|ready/i.test(x.status || "")) || rows} open={open} /><Lane title="Sent / Viewed" rows={rows.filter((x)=>/sent|viewed/i.test(x.status || ""))} open={open} /><Lane title="Accepted / Paid" rows={rows.filter((x)=>/accepted|paid/i.test(x.status || ""))} open={open} /><Lane title="Follow-up / Due" rows={rows.filter((x)=>/follow|due|overdue/i.test(x.status || x.date || ""))} open={open} /></div></Panel><Panel eyebrow="Work form" title={sideTitle}><Fields rows={sideFields} /><button className="chxBtn">Prepare for approval</button></Panel><Panel eyebrow="Rules" title="Owner controlled">{bottom}</Panel></div>; }
function Team({ data, open }) { return <div className="chxScreen chxTeam"><Panel eyebrow="People" title="Team and access" className="peopleList"><div className="chxScroll chxCardGrid">{data.team.map((x)=><RecordCard key={x.id} item={x} onOpen={open}/>)}</div></Panel><Panel eyebrow="Invite" title="Add worker"><Fields rows={[["Name",""],["Email",""],["Role","Worker","select",choices.role],["Access","Worker app","select",choices.access],["Notes","","textarea"]]} /><button className="chxBtn">Send invite</button></Panel><Panel eyebrow="Rules" title="Role clarity"><MiniGrid rows={[["Owner","Full Command/settings/billing access"],["Worker","Assigned jobs, proof, messages, clock"],["Payroll","Review only unless allowed"]]} /></Panel></div>; }
function Payroll({ data, open }) { const slips = data.workerSlips || data.team; return <div className="chxScreen chxPayroll"><Panel eyebrow="Pay period" title="Review only"><ActionStrip items={["Weekly","Fortnightly","Monthly","CSV export"]}/><p className="chxNotice">No tax filing. No bank payout files.</p></Panel><Panel eyebrow="This period" title="Worker hours" className="hoursPanel"><div className="chxScroll chxTable">{slips.map((x)=><div className="chxTableRow" key={x.id}><b>{x.title}</b><span>{x.timesheet || "0h"}</span><span>{x.price || "Review"}</span><small>{x.status}</small><small>{x.proof}</small></div>)}</div></Panel><Panel eyebrow="Slips" title="Clock proof feeds payroll" className="slipsPanel"><div className="chxScroll chxCardGrid">{slips.map((x)=><RecordCard key={x.id} item={x} onOpen={open}/>)}</div></Panel></div>; }
function Workers({ data, open }) { const query = data.jobs.map((x)=>x.address).filter(Boolean).slice(0,5).join(" ") || "Lower Hutt New Zealand"; return <div className="chxScreen chxWorkers"><Panel eyebrow="GPS map" title="Field control" className="mapPanel"><Map query={query}/></Panel><Panel eyebrow="Daily slips" title="Clock, proof and messages" className="slipsPanel"><div className="chxScroll chxCardGrid">{(data.workerSlips || data.team).map((x)=><RecordCard key={x.id} item={x} onOpen={open}/>)}</div></Panel><Panel eyebrow="Proof" title="Before complete" className="proofPanel"><MiniGrid rows={[["Before photo","Required where set"],["After photo","Feeds job/invoice evidence"],["Issue photo","Routes to Command"]]} /></Panel><Panel eyebrow="Messages" title="Worker updates" className="messagePanel"><div className="chxScroll chxRows">{data.messages.map((x)=><Row key={x.id} item={x} onOpen={open}/>)}</div></Panel></div>; }
function Xero({ data }) { const connected = Boolean(data.xero?.connected || data.xero?.xero_connected); return <div className="chxScreen chxXero"><Panel eyebrow="Guarded sync" title="Accounting handoff"><div className="chxMiniGrid"><Mini title={connected ? "Connected" : "Not connected"} text={data.xero?.tenant_name || "Xero/MYOB where available"}/><Mini title="Draft sync only" text="Owner approval required"/><Mini title="Payment refresh" text="Paid only after accounting confirms"/></div><p className="chxNotice">No automatic invoice sending. No tax filing. No bank payout files.</p></Panel><Panel eyebrow="Sync queue" title="Draft invoices ready"><div className="chxScroll chxCardGrid">{data.invoices.map((x)=><RecordCard key={x.id} item={x} onOpen={()=>{}}/>)}</div></Panel></div>; }
function Settings() { return <div className="chxScreen chxSettings"><Panel eyebrow="Business profile" title="Brand and defaults"><Fields rows={[["Business name","Churvox"],["Owner email","hello@churvox.com"],["GST rate","15"],["Country","NZ"],["Default repeat","Fortnightly","select",choices.repeat],["Default billing","Fixed price","select",choices.billing],["Logo","Not uploaded"],["Notifications","On"]]} /><button className="chxBtn">Save settings</button></Panel><Panel eyebrow="Imports" title="CSV and records"><MiniGrid rows={[["Clients CSV","Visible from Settings and Clients"],["Team CSV","Invite workers later"],["Bookkeeper pack","CSV export stays guarded"]]} /></Panel><Panel eyebrow="Security" title="Account controls"><MiniGrid rows={[["Email verification","Required before live use"],["Forgot password","Email service wiring"],["Delete account","Controlled account action"],["Business isolation","Each business separate"]]} /></Panel></div>; }
function Plans() { return <div className="chxScreen chxPlans"><div className="chxPlansGrid">{planRows.map(([name, price, text, bullets]) => <section key={name} className={`chxPlan ${name === "Operator" ? "popular" : ""}`}>{name === "Operator" && <em>Most Popular</em>}<span className="chxPill">{name}</span><h2>{price}<small>/month + GST</small></h2><p>{text}</p><ul>{bullets.map((b)=><li key={b}>{b}</li>)}</ul></section>)}</div></div>; }
function Support() { return <div className="chxScreen chxSupport"><Panel eyebrow="Help" title="Setup guide"><MiniGrid rows={[["Start","Add clients and jobs"],["Command","Approve what Churvox prepares"],["Workers","Map, proof, messages and slips"],["Accounting","Keep draft sync guarded"]]} /></Panel><Panel eyebrow="Contact" title="hello@churvox.com"><p className="chxNotice">Support, setup help and short guides.</p></Panel><Panel eyebrow="Guides" title="What each page is for"><MiniGrid rows={[["AI Guide","Owner pulse"],["Jobs","Job board"],["Clients","Database"],["Command","Approval desk"]]} /></Panel></div>; }
function MiniGrid({ rows }) { return <div className="chxMiniGrid">{rows.map(([a,b])=><Mini key={a} title={a} text={b}/>)}</div>; }
export default function FreshAppSpecific(){ const api = useApi(); const data = useData(api); const [page,setPage] = React.useState(pageFromUrl); const [drawer,setDrawer] = React.useState(null); const [title,subtitle] = pageInfo[page] || pageInfo.aiguide; React.useEffect(()=>{ const refresh=()=>setPage(pageFromUrl()); window.addEventListener("hashchange", refresh); window.addEventListener("popstate", refresh); return ()=>{ window.removeEventListener("hashchange", refresh); window.removeEventListener("popstate", refresh); }; },[]); function go(next){ setPage(next); setDrawer(null); window.history.replaceState({},"",`/dashboard#${next}`); } return <main className="chxApp"><div className="chxShell"><header className="chxTop"><div className="chxHead"><div className="chxBrand"><span className="chxMark"/><span><b>Churvox</b><small>does the admin</small></span></div><div className="chxTitle"><h1>{title}</h1><p>{subtitle}</p></div><a className="chxLogout" href="/login">Log out</a></div><nav className="chxNav">{nav.map((item)=>{ const next=k(item); return <button key={item} type="button" className={page===next?"active":""} onClick={()=>go(next)}>{item}</button>; })}</nav></header><section className="chxStage"><Layout page={page} data={data} open={setDrawer}/></section></div><Drawer item={drawer} onClose={()=>setDrawer(null)}/></main>; }
