import React from "react";
import "../churvox-clean/ChurvoxCleanApp.css";

const nav = ["AI Guide", "Command", "Jobs", "Clients", "Quotes", "Invoices", "Team", "Payroll", "Workers", "Xero", "Settings", "Plans", "Support"];
const key = (v) => String(v || "").toLowerCase().replace(/\s+/g, "");
const titles = {
  aiguide: ["AI Guide", "Set up the business, then approve what Churvox prepares."],
  command: ["Command", "Owner approval desk. Approve, edit or park prepared admin."],
  jobs: ["Jobs", "Job cards, prices, dates, workers, recurring work and notes."],
  clients: ["Clients", "Client records, service memory, saved prices and history."],
  quotes: ["Quotes", "Draft quotes, scopes, prices, follow-ups and owner-approved sending."],
  invoices: ["Invoices", "Draft invoices, due work, paid status and accounting handoff controls."],
  team: ["Team", "People, roles, access and worker app status."],
  payroll: ["Payroll", "Pay-period review only. No tax filing. No bank payout files."],
  workers: ["Workers", "Map, clock status, proof, messages and daily slips."],
  xero: ["Xero", "Draft sync only. Owner-approved accounting handoff."],
  settings: ["Settings", "Business profile, GST, branding, imports and account controls."],
  plans: ["Plans", "Locked Churvox pricing and add-ons."],
  support: ["Support", "Setup help, short guides and contact options."]
};
const data = {
  command: [
    { title: "Approve garden reset quote", client: "Robert K", price: "$190", status: "Approval", date: "Today", note: "Scope and price prepared. Owner can approve, edit or park." },
    { title: "Review invoice draft", client: "Lisa M", price: "$85", status: "Approval", date: "Due today", note: "Ready to send after owner check. No automatic invoice sending." },
    { title: "Changed job price", client: "Garden tidy", price: "$140", status: "Edit", date: "Today", note: "Churvox found a price change and parked it here." }
  ],
  jobs: [
    { title: "Lawn care - Birchville", client: "Lisa M", price: "$85", status: "Ready", date: "Today 10:30", repeat: "Fortnightly", worker: "Unassigned", note: "Mow, edges, blower tidy. Worker proof required." },
    { title: "Garden tidy - Naenae", client: "Robert K", price: "$140", status: "Needs approval", date: "Tomorrow 9:00", repeat: "One-off", worker: "Howard", note: "Green waste and garden reset. Price needs owner check." },
    { title: "Hedge trim - Wainuiomata", client: "Mere H", price: "$120", status: "Booked", date: "Friday 1:00", repeat: "Monthly", worker: "Worker account", note: "Before and after photos required." }
  ],
  clients: [
    { title: "Lisa M", client: "Birchville", price: "$85", status: "Active", date: "Fortnightly", note: "Lawn mow + edges. Saved price and service memory." },
    { title: "Robert K", client: "Naenae", price: "$140", status: "Quote ready", date: "One-off", note: "Garden tidy, green waste and reset notes." },
    { title: "Mere H", client: "Wainuiomata", price: "$120", status: "Active", date: "Monthly", note: "Hedge trim, tidy, photos before complete." }
  ],
  quotes: [
    { title: "Garden reset quote", client: "Robert K", price: "$190", status: "Draft", date: "Prepared today", note: "Scope, price and follow-up ready for Command." },
    { title: "Monthly maintenance", client: "Mere H", price: "$120", status: "Viewed", date: "Follow-up due", note: "Churvox prepared a polite follow-up." }
  ],
  invoices: [
    { title: "INV-1042", client: "Lisa M", price: "$85", status: "Draft", date: "Due today", note: "Review before sending. No automatic sending." },
    { title: "INV-1041", client: "Straightforward Lawn Care", price: "$65", status: "Paid", date: "Paid", note: "Only marked paid after accounting refresh confirms paid." }
  ],
  team: [
    { title: "Howard", client: "Owner", price: "", status: "Active", date: "Full access", note: "Command, settings, billing and approval access." },
    { title: "Worker account", client: "Field worker", price: "", status: "Invited", date: "Worker app", note: "Jobs, proof, messages, clock status and daily slips." }
  ]
};
const actions = {
  command: ["Approve selected", "Edit selected", "Park selected"], jobs: ["Add job", "Recurring setup", "Assign worker"], clients: ["Add client", "CSV import", "Open client form"], quotes: ["Create quote", "Follow up", "Convert to job"], invoices: ["Create invoice", "Review draft", "Mark paid after refresh"], team: ["Add person", "Invite worker", "Access roles"], payroll: ["Weekly", "Fortnightly", "Monthly"], workers: ["Open map", "Send message", "Review proof"], xero: ["Check status", "Draft sync", "Refresh payments"], settings: ["Save profile", "Upload logo", "Import clients"], plans: ["Choose plan", "Add growth pack", "Accounting add-on"], support: ["Setup guide", "Contact help", "Report issue"]
};
function startPage(){ if(typeof window==="undefined") return "aiguide"; const raw=String(window.location.hash||window.location.pathname||"").replace("#","").replace("/","").toLowerCase(); const alias={dashboard:"aiguide",smart:"aiguide",guide:"aiguide",setup:"aiguide",help:"support",accounting:"xero"}; return alias[raw] || (nav.map(key).includes(raw)?raw:"aiguide"); }
function Toolbar({page}){ const list=actions[page]||[]; return list.length ? <div className="cvxCleanStats">{list.map((a,i)=><span key={a}><b>{i===0?"+":i===1?"✓":"•"}</b>{a}</span>)}</div> : null; }
function Card({item,onOpen}){ return <button className="cvxCleanCard" type="button" onClick={()=>onOpen(item)}><em>{item.status}</em><h3>{item.title}</h3><p>{item.note}</p><div><b>{item.client}</b><strong>{item.price}</strong><small>{item.date}</small></div></button>; }
function Drawer({item,onClose}){ const [form,setForm]=React.useState(item||{}); React.useEffect(()=>setForm(item||{}),[item]); if(!item) return null; const set=(k,v)=>setForm((c)=>({...c,[k]:v})); return <aside className="cvxCleanDrawer"><button className="cvxCleanClose" type="button" onClick={onClose}>Close</button><p className="cvxCleanKicker">Editable form</p><h2>{form.title}</h2><label>Title<input value={form.title||""} onChange={(e)=>set("title",e.target.value)}/></label><label>Client / person<input value={form.client||""} onChange={(e)=>set("client",e.target.value)}/></label><label>Date / time<input value={form.date||""} onChange={(e)=>set("date",e.target.value)}/></label><label>Worker<input value={form.worker||""} onChange={(e)=>set("worker",e.target.value)}/></label><label>Price<input value={form.price||""} onChange={(e)=>set("price",e.target.value)}/></label><label>Repeat<select value={form.repeat||"One-off"} onChange={(e)=>set("repeat",e.target.value)}><option>One-off</option><option>Weekly</option><option>Fortnightly</option><option>Monthly</option><option>Custom</option></select></label><label>Status<input value={form.status||""} onChange={(e)=>set("status",e.target.value)}/></label><label>Notes<textarea value={form.note||""} onChange={(e)=>set("note",e.target.value)}/></label><div className="cvxCleanDrawerActions"><button type="button">Approve</button><button type="button">Edit saved locally</button><button type="button">Park in Command</button></div><small>Clean frontend only. Backend wiring comes later, one feature at a time.</small></aside>; }
function Guide(){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>Start here</p><h2>Next setup</h2><ol><li>Add your first client</li><li>Create your first job</li><li>Review in Command</li><li>Approve before sending</li></ol></section><section className="cvxCleanPanel"><p>Today</p><h2>Business pulse</h2><div className="cvxCleanStats"><span><b>3</b>Jobs</span><span><b>2</b>Drafts</span><span><b>3</b>Approvals</span><span><b>Live</b>Command</span></div></section><section className="cvxCleanPanel"><p>Guardrails</p><h2>Quiet admin rules</h2><ul><li>No automatic invoice sending</li><li>No tax filing</li><li>No bank payout files</li><li>Only mark paid after accounting refresh confirms paid</li></ul></section></div>; }
function CardsPage({page,open}){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>{titles[page][0]} actions</p><h2>Working controls</h2><Toolbar page={page}/></section><section className="cvxCleanPanel"><p>Records</p><h2>{page==="command"?"Waiting for owner":`Saved ${titles[page][0].toLowerCase()}`}</h2><div className="cvxCleanCards">{(data[page]||[]).map((item)=><Card key={item.title} item={item} onOpen={open}/>)}</div></section></div>; }
function Workers({open}){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>GPS</p><h2>Worker map</h2><div className="cvxCleanMap">Google Maps / route view connects here</div></section><section className="cvxCleanPanel"><p>Worker slips</p><h2>Clock, proof and messages</h2><div className="cvxCleanCards">{data.jobs.slice(0,2).map((item)=><Card key={item.title} item={item} onOpen={open}/>)}</div></section><section className="cvxCleanPanel"><p>Messages</p><h2>Sent to Command</h2><ul><li>Job issue goes to Command, not buried in Jobs</li><li>Worker photos stay attached to the job</li><li>Clock status supports payroll review</li></ul></section></div>; }
function Payroll(){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>Pay period</p><h2>Review only</h2><Toolbar page="payroll"/><ul><li>Timesheets from worker clock data</li><li>Manual review before export</li><li>No tax filing</li><li>No bank payout files</li></ul></section><section className="cvxCleanPanel"><p>This period</p><h2>Payroll summary</h2><div className="cvxCleanStats"><span><b>2</b>People</span><span><b>0h</b>Waiting</span><span><b>CSV</b>Later</span><span><b>Safe</b>Review</span></div></section></div>; }
function Xero(){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>Guarded sync</p><h2>Xero / MYOB handoff</h2><Toolbar page="xero"/><ul><li>Draft invoice sync only</li><li>Owner approval required</li><li>No automatic invoice sending</li><li>Paid status only after accounting refresh confirms paid</li></ul></section><section className="cvxCleanPanel"><p>Connection</p><h2>Backend later</h2><p className="cvxCleanNotice">Buttons are intentionally local until the clean frontend is approved.</p></section></div>; }
function Settings(){ return <div className="cvxCleanGrid"><section className="cvxCleanForm">{[["Business name","churvox"],["Owner email","hello@churvox.com"],["GST rate","15"],["Country","NZ"],["Notifications","On"],["Logo","Not uploaded"],["Client CSV","Ready"],["Default repeat","Fortnightly"]].map(([a,b])=><label key={a}>{a}<input defaultValue={b}/></label>)}<button type="button">Save locally</button></section><section className="cvxCleanPanel"><p>Controls</p><h2>Import and account</h2><ul><li>Client CSV import placeholder</li><li>Business branding placeholder</li><li>Delete account control later</li></ul></section></div>; }
function Plans(){ return <div className="cvxCleanPlans">{[["Start","$39","Solo owner starting clean."],["Crew","$89","Jobs, clients and small team."],["Operator","$149","Most popular. Churvox prepares more admin."],["Command","$299","Approval desk, scale and accounting handoff."],["Growth Pack","$99","Adds 50 active team members and extra capacity."],["Accounting Add-on","$39","For non-Command tiers."]].map(([a,b,c])=><section key={a}><p>{a}</p><h2>{b}<small>/month + GST</small></h2><span>{c}</span></section>)}</div>; }
function Support(){ return <div className="cvxCleanGrid"><section className="cvxCleanPanel"><p>Help</p><h2>Churvox setup</h2><ul><li>Start with clients and jobs</li><li>Use Command for approval decisions</li><li>Keep accounting guarded</li></ul></section><section className="cvxCleanPanel"><p>Contact</p><h2>hello@churvox.com</h2><p className="cvxCleanNotice">Support wiring comes after this frontend is stable.</p></section></div>; }
function Page({page,open}){ if(page==="aiguide") return <Guide/>; if(["command","jobs","clients","quotes","invoices","team"].includes(page)) return <CardsPage page={page} open={open}/>; if(page==="workers") return <Workers open={open}/>; if(page==="payroll") return <Payroll/>; if(page==="xero") return <Xero/>; if(page==="settings") return <Settings/>; if(page==="plans") return <Plans/>; return <Support/>; }
export default function FreshApp(){ const [page,setPage]=React.useState(startPage); const [selected,setSelected]=React.useState(null); const [title,sub]=titles[page]||titles.aiguide; const go=(next)=>{setPage(next);setSelected(null); if(typeof window!=="undefined") window.history.replaceState({},"",`/dashboard#${next}`);}; return <main className="cvxClean"><div className="cvxCleanShell"><header className="cvxCleanTop"><div className="cvxCleanHead"><div className="cvxCleanBrand"><span className="cvxCleanMark"/><span><b>Churvox</b><small>does the admin</small></span></div><div className="cvxCleanTitle"><h1>{title}</h1><p>{sub}</p></div><a className="cvxCleanLogout" href="/login">Log out</a></div><nav className="cvxCleanNav">{nav.map((n)=><button key={n} type="button" className={page===key(n)?"active":""} onClick={()=>go(key(n))}>{n}</button>)}</nav></header><section className="cvxCleanWork"><Page page={page} open={setSelected}/></section></div><Drawer item={selected} onClose={()=>setSelected(null)}/></main>; }
