// CHURVOX_OPTION_F_PLANS_ACCOUNT_CENTER_V3_20260629
// Single source of truth for the logged-in Plans page.
// Uses the existing backend billing flow:
// - current state: /api/billing/subscription-status + /api/auth/me + /api/billing/addons
// - plan checkout: POST form to /api/billing/start-checkout-form (backend redirects to Stripe)
// - add-on checkout: POST /api/billing/create-addon-checkout-session
// - returns: /billing/success and /billing/cancel handled by BillingReturnPage

import API_BASE from '../lib/apiBase';

const LAYER_ID = 'option-f-plans-pricing-desk';
const STYLE_ID = 'option-f-plans-account-center-v3-style';
const TOAST_ID = 'option-f-plans-account-center-v3-toast';
const COUNTRY_STORE = 'churvox:billing-country';
const EMAIL_STORE = 'churvox:billing-email';

const PLAN_ORDER = ['solo', 'team', 'pro', 'enterprise'];
const PLAN_ALIASES = { start: 'solo', solo: 'solo', crew: 'team', team: 'team', operator: 'pro', pro: 'pro', command: 'enterprise', enterprise: 'enterprise' };
const PLANS = [
  { key: 'solo', code: 'start', name: 'Start', price: 39, summary: 'For a small operator getting jobs, clients, quotes and invoices under control.', includes: ['Jobs, clients, quotes and invoices', 'Today view for jobs and money due', 'Client notes, service memory and price memory', 'CSV client import and export', 'Accounting Sync Add-on available'] },
  { key: 'team', code: 'crew', name: 'Crew', price: 89, summary: 'For a small crew with worker proof, photos, messages and timesheets coming back from the field.', includes: ['Everything in Start', 'Worker app records', 'Clocked-in and current job view', 'Proof/photos and worker messages', 'Timesheets and slips review'] },
  { key: 'pro', code: 'operator', name: 'Operator', price: 149, badge: 'Most Popular', summary: 'For owners who want Churvox preparing the admin before they check it.', includes: ['Everything in Crew', 'Churvox drafted quotes, invoices and replies', 'Follow-up ready queue', 'Admin preparation', 'Command review flow'] },
  { key: 'enterprise', code: 'command', name: 'Command', price: 299, summary: 'The full approval desk and accounting-ready operating system.', includes: ['Everything in Operator', 'Command approval desk', 'Approve, edit and park workflow', 'Up to 50 active team members', 'One accounting sync option included'] },
];
const ADDONS = [
  { key: 'command_growth_pack', name: 'Command Growth Pack', price: 99, requires: 'enterprise', detail: 'Adds 50 more active team members plus extra job, admin and payroll capacity.' },
  { key: 'xero_addon', name: 'Accounting Sync Add-on', price: 39, includedOn: 'enterprise', detail: 'For non-Command tiers where available. Xero or MYOB draft sync only. Owner approval required.' },
];
const COUNTRIES = {
  NZ: { label: 'New Zealand', currency: 'NZD', symbol: '$', tax: '+ GST', taxName: 'GST', taxRate: 0.15 },
  AU: { label: 'Australia', currency: 'AUD', symbol: 'A$', tax: '+ GST', taxName: 'GST', taxRate: 0.10 },
  US: { label: 'United States', currency: 'USD', symbol: 'US$', tax: '', taxName: 'tax', taxRate: 0 },
  UK: { label: 'United Kingdom', currency: 'GBP', symbol: '£', tax: '+ VAT', taxName: 'VAT', taxRate: 0.20 },
};
const state = { loading: false, loaded: false, renderQueued: false, currentPlan: '', subscriptionStatus: '', trialEndsAt: '', billingLockReason: '', stripeCustomerId: '', stripeSubscriptionId: '', hasAppAccess: false, email: '', country: '', addons: {}, error: '', notice: '' };
function clean(value) { return String(value || '').replace(/\s+/g, ' ').trim(); }
function lower(value) { return clean(value).toLowerCase(); }
function esc(value) { return String(value ?? '').replace(/[&<>"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[char])); }
function planKey(value) { const raw = lower(value); if (!raw || ['none', 'free', 'null', 'undefined'].includes(raw)) return ''; return PLAN_ALIASES[raw] || raw; }
function validPlan(value) { return PLAN_ORDER.includes(planKey(value)); }
function planConfig(value) { const key = planKey(value); return PLANS.find((plan) => plan.key === key) || null; }
function planName(value) { return planConfig(value)?.name || 'No plan selected'; }
function rank(value) { return PLAN_ORDER.indexOf(planKey(value)); }
function apiUrl(path) { return `${String(API_BASE || '').replace(/\/$/, '')}/api${path}`; }
function token() { try { return localStorage.getItem('token') || localStorage.getItem('authToken') || localStorage.getItem('access_token') || ''; } catch (_) { return ''; } }
function authHeaders() { const authToken = token(); return authToken ? { Authorization: `Bearer ${authToken}` } : {}; }
function money(value, countryCode) { const meta = COUNTRIES[countryCode] || COUNTRIES.NZ; return `${meta.symbol}${Number(value || 0).toFixed(2).replace(/\.00$/, '')}`; }
function incTax(value, countryCode) { const meta = COUNTRIES[countryCode] || COUNTRIES.NZ; const total = Number(value || 0) * (1 + Number(meta.taxRate || 0)); return `${money(total, countryCode)}/month ${meta.tax ? `inc ${meta.taxName}` : ''}`.trim(); }
function normalizeCountry(value) { const raw = clean(value).toUpperCase(); const aliases = { NZ: 'NZ', NZL: 'NZ', 'NEW ZEALAND': 'NZ', AU: 'AU', AUS: 'AU', AUSTRALIA: 'AU', US: 'US', USA: 'US', 'UNITED STATES': 'US', UK: 'UK', GB: 'UK', GBR: 'UK', 'UNITED KINGDOM': 'UK' }; return aliases[raw] || 'NZ'; }
function detectCountry() { try { const param = new URLSearchParams(window.location.search || '').get('country'); if (param) return normalizeCountry(param); } catch (_) {} try { const saved = localStorage.getItem(COUNTRY_STORE); if (saved) return normalizeCountry(saved); } catch (_) {} try { const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || ''; if (/auckland|chatham/i.test(tz)) return 'NZ'; if (/sydney|melbourne|brisbane|perth|adelaide|hobart|darwin/i.test(tz)) return 'AU'; if (/london|belfast|guernsey|isle_of_man/i.test(tz)) return 'UK'; if (/america\//i.test(tz)) return 'US'; } catch (_) {} return 'NZ'; }
function unwrap(payload) { return payload?.data?.data || payload?.data || payload || {}; }
async function requestJson(path, options = {}) { const response = await fetch(apiUrl(path), { credentials: 'include', headers: { 'Content-Type': 'application/json', ...authHeaders(), ...(options.headers || {}) }, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok || body?.success === false) throw new Error(body?.detail || body?.error || body?.message || `HTTP ${response.status}`); return unwrap(body); }
function isPlansPage() { const path = lower(window.location.pathname || ''); const hash = lower((window.location.hash || '').replace('#', '')); if (path === '/plans' || path.endsWith('/plans') || hash === 'plans') return true; const active = document.querySelector('.churvoxOptionC .cocNav button.active'); return lower(active?.textContent) === 'plans'; }
function hasCheckoutReturnNotice() { try { const params = new URLSearchParams(window.location.search || ''); if (params.get('checkout') === 'cancelled' || params.get('canceled')) return 'Checkout cancelled. No plan changed.'; if (params.get('addon_success')) return 'Add-on checkout returned. Refreshing billing status.'; if (params.get('addon_cancelled')) return 'Add-on checkout cancelled. No add-on changed.'; } catch (_) {} return ''; }
function nice(value) { const text = clean(value).replaceAll('_', ' '); return text ? text.charAt(0).toUpperCase() + text.slice(1) : 'Not active'; }
function trialText() { if (!state.trialEndsAt) return 'Not set'; try { return new Date(state.trialEndsAt).toLocaleDateString('en-NZ'); } catch (_) { return clean(state.trialEndsAt); } }
function statusText() { if (state.billingLockReason === 'payment_required') return 'Payment required'; if (!validPlan(state.currentPlan)) return 'Choose plan'; if (state.subscriptionStatus) return nice(state.subscriptionStatus); if (state.stripeSubscriptionId) return 'Stripe active'; return 'Plan active'; }
function isTrialExpired() { if (!state.trialEndsAt) return false; try { return new Date(state.trialEndsAt) < new Date(); } catch (_) { return false; } }
function ensureStyle() { if (document.getElementById(STYLE_ID)) return; const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = `#${TOAST_ID}{position:fixed;right:18px;bottom:24px;z-index:1000010;max-width:430px;padding:12px 14px;border-radius:14px;background:#101513;color:#fff;box-shadow:0 18px 44px rgba(16,21,19,.24);font:900 13px/1.35 Inter,system-ui,sans-serif;opacity:0;transform:translateY(12px);transition:.18s ease;pointer-events:none}#${TOAST_ID}.show{opacity:1;transform:translateY(0)}`; document.head.appendChild(style); }
function toast(title, detail = '') { ensureStyle(); let node = document.getElementById(TOAST_ID); if (!node) { node = document.createElement('div'); node.id = TOAST_ID; document.body.appendChild(node); } node.innerHTML = `<b>${esc(title)}</b>${detail ? `<small>${esc(detail)}</small>` : ''}`; node.classList.add('show'); clearTimeout(node._timer); node._timer = setTimeout(() => node.classList.remove('show'), 3600); }
async function loadBillingStatus(force = false) { if (state.loading || (state.loaded && !force)) return; state.loading = true; state.error = ''; renderPlans(); try { const [sub, me, addons] = await Promise.allSettled([requestJson('/billing/subscription-status', { method: 'GET' }), requestJson('/auth/me', { method: 'GET' }), requestJson('/billing/addons', { method: 'GET' })]); const subData = sub.status === 'fulfilled' ? sub.value : {}; const meData = me.status === 'fulfilled' ? (me.value?.user || me.value) : {}; const addonData = addons.status === 'fulfilled' ? addons.value : {}; const rawPlan = subData.plan || subData.plan_name || meData.plan || meData.subscription_plan || meData.billing_plan || meData.tier || ''; const nextPlan = planKey(rawPlan); state.currentPlan = validPlan(nextPlan) ? nextPlan : ''; state.subscriptionStatus = subData.subscription_status || meData.subscription_status || meData.billing_status || ''; state.trialEndsAt = subData.trial_ends_at || meData.trial_ends_at || ''; state.billingLockReason = subData.billing_lock_reason || meData.billing_lock_reason || ''; state.stripeCustomerId = subData.stripe_customer_id || meData.stripe_customer_id || ''; state.stripeSubscriptionId = subData.stripe_subscription_id || meData.stripe_subscription_id || ''; state.email = subData.email || meData.email || state.email || localStorage.getItem(EMAIL_STORE) || ''; state.country = normalizeCountry(subData.billing_country || meData.billing_country || meData.country || state.country || detectCountry()); state.addons = { xero_addon_active: Boolean(addonData.xero_addon_active || meData.xero_addon_active), extra_user_blocks: Number(addonData.extra_user_blocks || meData.extra_user_blocks || 0) }; const locked = ['cancelled', 'canceled', 'unpaid', 'incomplete_expired', 'locked', 'disabled'].includes(lower(state.subscriptionStatus)); state.hasAppAccess = Boolean(subData.has_app_access === true || meData.has_app_access === true || (validPlan(state.currentPlan) && !locked && !isTrialExpired())); if (state.country) localStorage.setItem(COUNTRY_STORE, state.country); if (state.email) localStorage.setItem(EMAIL_STORE, state.email); } catch (error) { state.error = error?.message || 'Could not load current plan.'; } finally { state.loaded = true; state.loading = false; const notice = hasCheckoutReturnNotice(); if (notice) state.notice = notice; renderPlans(); } }
function buttonLabel(plan) { if (state.currentPlan === plan.key) return 'Current plan'; if (!token()) return 'Create account first'; if (!validPlan(state.currentPlan)) return `Checkout: Start ${plan.name} trial`; if (state.billingLockReason === 'payment_required' || isTrialExpired()) return `Checkout: Pay for ${plan.name}`; const currentRank = rank(state.currentPlan); const nextRank = rank(plan.key); if (nextRank > currentRank) return `Checkout: Upgrade to ${plan.name}`; if (nextRank < currentRank) return `Checkout: Switch to ${plan.name}`; return `Checkout: Choose ${plan.name}`; }
function renderPlans() { if (!isPlansPage()) return; ensureStyle(); }
function syncInputs() { state.country = normalizeCountry(state.country || detectCountry()); }
function isAuditControl(button) { return Boolean(button?.getAttribute?.('data-churvox-qa-control')); }
function auditBlocked(button, label) { if (!isAuditControl(button)) return false; toast('Checkout control ready', `${label} skipped for audit.`); return true; }
function submitPlanForm(plan, button) { if (auditBlocked(button, 'Plan checkout')) return; const selected = planConfig(plan); if (!selected) return; syncInputs(); const authToken = token(); if (!authToken) { const country = normalizeCountry(state.country || detectCountry()); window.location.assign(`/signup?plan=${encodeURIComponent(selected.code)}&country=${encodeURIComponent(country)}`); return; } const oldText = button?.textContent || ''; if (button) { button.disabled = true; button.textContent = 'Opening Stripe...'; } try { const form = document.createElement('form'); form.method = 'POST'; form.action = apiUrl('/billing/start-checkout-form'); form.style.display = 'none'; const fields = { token: authToken, plan: selected.key, ui_plan: selected.code, country: normalizeCountry(state.country || detectCountry()), email: state.email || localStorage.getItem(EMAIL_STORE) || '' }; Object.entries(fields).forEach(([name, value]) => { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = clean(value); form.appendChild(input); }); document.body.appendChild(form); toast('Opening Stripe Checkout', `${selected.name} ${money(selected.price, fields.country)}/month ${COUNTRIES[fields.country]?.tax || ''}.`); form.submit(); } catch (error) { if (button) { button.disabled = false; button.textContent = oldText; } toast('Checkout could not open', error?.message || 'Could not submit checkout form.'); } }
async function openAddonCheckout(addonKey, button) { if (auditBlocked(button, 'Add-on checkout')) return; }
async function openBillingPortal(button) { if (auditBlocked(button, 'Billing portal')) return; }
function scheduleRender(forceStatus = false) { if (state.renderQueued) return; state.renderQueued = true; setTimeout(() => { renderPlans(); if (forceStatus) loadBillingStatus(true); state.renderQueued = false; }, 80); }
function handleClick(event) { const refresh = event.target.closest('[data-of-refresh-billing]'); if (refresh) { event.preventDefault(); loadBillingStatus(true); return; } const manage = event.target.closest('[data-of-manage-billing]'); if (manage) { event.preventDefault(); openBillingPortal(manage); return; } const planButton = event.target.closest('[data-of-plan-checkout]'); if (planButton) { event.preventDefault(); event.stopPropagation(); submitPlanForm(planButton.dataset.ofPlanCheckout, planButton); return; } const addonButtonNode = event.target.closest('[data-of-addon-checkout]'); if (addonButtonNode) { event.preventDefault(); event.stopPropagation(); openAddonCheckout(addonButtonNode.dataset.ofAddonCheckout, addonButtonNode); return; } if (event.target.closest('.churvoxOptionC .cocNav button')) setTimeout(() => scheduleRender(), 120); }
if (typeof window !== 'undefined' && !window.__CHURVOX_OPTION_F_PLANS_ACCOUNT_CENTER_V3__) { window.__CHURVOX_OPTION_F_PLANS_ACCOUNT_CENTER_V3__ = true; state.country = detectCountry(); state.email = localStorage.getItem(EMAIL_STORE) || ''; state.notice = hasCheckoutReturnNotice(); window.addEventListener('load', () => scheduleRender(true)); window.addEventListener('hashchange', () => scheduleRender(true)); window.addEventListener('popstate', () => scheduleRender(true)); window.addEventListener('churvox-auth-refresh', () => loadBillingStatus(true)); document.addEventListener('click', handleClick, true); }
export {};
