import { useEffect, useState } from "react";
import { askBusiness, loadAiIntelligenceSnapshot, prepareDailyBriefing, updateAiMemory } from "../../ai/aiIntelligenceApi";

export default function AIIntelligencePanel({ onNav }) {
  const [data, setData] = useState({}); const [busy, setBusy] = useState(false); const [q, setQ] = useState(""); const [answer, setAnswer] = useState("");
  useEffect(() => { loadAiIntelligenceSnapshot().then(setData).catch(() => setData({})); }, []);
  const run = async (fn) => { setBusy(true); try { const r = await fn(); if (r?.briefing) setData((d) => ({ ...d, briefing: r.briefing })); if (r?.memory) setData((d) => ({ ...d, memory: r.memory })); } finally { setBusy(false); } };
  return <section className="op-panel op-ai-intelligence"><header><div><p>AI INTELLIGENCE</p><h2>Smart Hub</h2></div><div className="op-row-actions"><button disabled={busy} onClick={() => run(prepareDailyBriefing)}>Prepare briefing</button><button disabled={busy} onClick={() => run(updateAiMemory)}>Update memory</button><button onClick={() => onNav?.("queue")}>Open AI Queue</button></div></header><div className="op-intel-grid"><article className="op-intel-card"><h3>Daily briefing</h3>{(data.briefing?.summary_cards||[]).map((c,i)=><div key={i} className="op-intel-strip"><span>{c.label}</span><strong>{c.value}</strong></div>)}</article><article className="op-intel-card"><h3>Data quality</h3><div className="op-intel-issues">{(data.quality?.issues||[]).slice(0,3).map((i)=><p key={i.code}>{i.label}: {i.fix}</p>)||<p>No issues.</p>}</div></article><article className="op-intel-card"><h3>Business memory</h3><p>Approved actions: {data.memory?.counts?.approved_ai_actions||0}</p></article><article className="op-intel-card"><h3>Audit trail</h3><p>{(data.audit||[]).length} recent AI events logged.</p></article></div><div className="op-ask-business"><label>Ask your business</label><div className="op-row-actions"><input value={q} onChange={(e)=>setQ(e.target.value)} /><button disabled={busy||!q.trim()} onClick={async()=>{setBusy(true);const r=await askBusiness(q);setAnswer(r?.answer?.answer||JSON.stringify(r?.answer||{}));setBusy(false);}}>Ask AI</button></div><div className="op-ai-answer">{answer || "No answer yet."}</div></div></section>;
}
