import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { ChurvoxLogo } from "../../components/ChurvoxLogo";

const S = {
  page: { minHeight: "100vh", background: "linear-gradient(140deg,#0f1419,#171d24 48%,#222b35)", color: "#eef2f5", fontFamily: "Inter, system-ui, sans-serif" },
  nav: { minHeight: 72, display: "flex", alignItems: "center", gap: 22, padding: "0 clamp(16px,4vw,72px)", background: "linear-gradient(90deg,#11171d,#212a33)", borderBottom: "1px solid #3f4b57" },
  logo: { display: "flex", textDecoration: "none" }, links: { display: "flex", gap: 8, flex: 1 },
  link: { color: "#c6cfd6", textDecoration: "none", fontWeight: 700, fontSize: 13, padding: "10px 12px", borderRadius: 10 },
  wrap: { minHeight: "calc(100vh - 72px)", display: "grid", gridTemplateColumns: "minmax(340px,.86fr) minmax(0,1.14fr)", gap: 24, alignItems: "center", padding: "clamp(28px,6vw,68px) clamp(16px,4vw,72px)" },
  form: { background: "linear-gradient(180deg,#252f39,#1d252d)", border: "1px solid #3f4b57", borderRadius: 18, padding: "clamp(24px,4vw,42px)" },
  kicker: { margin: 0, color: "#70c6d2", textTransform: "uppercase", letterSpacing: ".15em", fontSize: 11, fontWeight: 900 },
  h1: { margin: "10px 0", fontFamily: "Outfit, Inter, sans-serif", fontSize: "clamp(30px,4vw,42px)", lineHeight: 1, letterSpacing: "-.03em", color: "#eef2f5" },
  input: { width: "100%", boxSizing: "border-box", border: "1px solid #3f4b57", borderRadius: 12, background: "#11171d", color: "#eef2f5", padding: "12px 14px", marginTop: 8, fontSize: 15 },
  btn: { width: "100%", border: "1px solid #e1bf81", borderRadius: 12, background: "linear-gradient(135deg,#d6a048,#ab7630)", color: "#1c1307", padding: "13px 16px", fontWeight: 900, marginTop: 18 },
  panel: { background: "linear-gradient(180deg,#252f39,#1d252d)", border: "1px solid #3f4b57", color: "#eef2f5", borderRadius: 18, padding: "clamp(24px,4vw,40px)" },
};

export default function SignupPage(){
const navigate=useNavigate();const {register}=useAuth();const [formData,setFormData]=useState({ name:"", email:"", password:"", confirmPassword:"", business_name:"" });const [error,setError]=useState("");const [loading,setLoading]=useState(false);
const handleChange=(e)=>setFormData({...formData,[e.target.name]:e.target.value});
const handleSubmit=async(e)=>{e.preventDefault();setError("");if(formData.password!==formData.confirmPassword)return setError("Passwords do not match");if(formData.password.length<6)return setError("Password must be at least 6 characters");setLoading(true);try{const result=await register({name:formData.name,email:formData.email,password:formData.password,business_name:formData.business_name||null});if(result?.token)navigate('/plans');else setError('Registration failed. Please try again.');}catch(err){setError(err?.response?.data?.detail||'Registration failed. Please try again.')}setLoading(false)};
return <main style={S.page}><header style={S.nav}><Link to="/" style={S.logo}><ChurvoxLogo/></Link><nav style={S.links}><Link to="/" style={S.link}>Home</Link><Link to="/features" style={S.link}>Features</Link><Link to="/pricing" style={S.link}>Pricing</Link><Link to="/login" style={S.link}>Log in</Link></nav></header><section style={S.wrap}><aside style={S.panel}><p style={{...S.kicker,color:"#bfe8ff"}}>Start the control system</p><h2 style={{fontFamily:"Outfit,Inter,sans-serif",fontSize:"clamp(32px,4vw,48px)",lineHeight:.82,letterSpacing:"-.08em",margin:"12px 0",color:"#fff"}}>Turn the business into prepared owner decisions.</h2><p style={{color:"rgba(255,255,255,.78)",fontSize:18,lineHeight:1.6}}>Create the account, choose a plan, then Churvox starts organising work into approval-first admin: jobs, workers, quotes, invoices and money.</p></aside><form style={S.form} onSubmit={handleSubmit}><p style={S.kicker}>Create account</p><h1 style={S.h1}>Build your approval control room.</h1>{error&&<p style={{color:"#b42318",fontWeight:800}}>{error}</p>}<label style={{display:"block",fontWeight:850,marginTop:16}}>Full name<input style={S.input} name="name" value={formData.name} onChange={handleChange} required data-testid="signup-name-input" /></label><label style={{display:"block",fontWeight:850,marginTop:14}}>Email<input style={S.input} name="email" type="email" value={formData.email} onChange={handleChange} required data-testid="signup-email-input" /></label><label style={{display:"block",fontWeight:850,marginTop:14}}>Business name<input style={S.input} name="business_name" value={formData.business_name} onChange={handleChange} data-testid="signup-business-input" /></label><label style={{display:"block",fontWeight:850,marginTop:14}}>Password<input style={S.input} name="password" type="password" value={formData.password} onChange={handleChange} required data-testid="signup-password-input" /></label><label style={{display:"block",fontWeight:850,marginTop:14}}>Confirm password<input style={S.input} name="confirmPassword" type="password" value={formData.confirmPassword} onChange={handleChange} required data-testid="signup-confirm-password-input" /></label><button style={S.btn} type="submit" disabled={loading} data-testid="signup-submit-button">{loading?'Creating account…':'Create account'}</button><p>Already have an account? <Link to="/login" data-testid="login-link">Sign in</Link></p></form></section></main>
}