import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";

export default function SignupPage(){
const navigate=useNavigate();const {register}=useAuth();const [formData,setFormData]=useState({ name:"", email:"", password:"", confirmPassword:"", business_name:"" });const [error,setError]=useState("");const [loading,setLoading]=useState(false);
const handleChange=(e)=>setFormData({...formData,[e.target.name]:e.target.value});
const handleSubmit=async(e)=>{e.preventDefault();setError("");if(formData.password!==formData.confirmPassword)return setError("Passwords do not match");if(formData.password.length<6)return setError("Password must be at least 6 characters");setLoading(true);try{const result=await register({name:formData.name,email:formData.email,password:formData.password,business_name:formData.business_name||null});if(result?.token)navigate('/plans');else setError('Registration failed. Please try again.');}catch(err){setError(err?.response?.data?.detail||'Registration failed. Please try again.')}setLoading(false)};
return <main className="cm-auth"><div className="cm-shell"><header className="cm-nav"><Link to="/">Churvox</Link><div><Link to="/features">Features</Link> <Link to="/pricing">Pricing</Link></div></header><section className="cm-auth-wrap"><form className="cm-form" onSubmit={handleSubmit}><p className="cm-kicker">Command Machine</p><h1>Start free</h1><p>Sign in to approve the work Churvox prepared.</p>{error&&<p>{error}</p>}<label>Full name<input name="name" value={formData.name} onChange={handleChange} required data-testid="signup-name-input" /></label><label>Email<input name="email" type="email" value={formData.email} onChange={handleChange} required data-testid="signup-email-input" /></label><label>Business name<input name="business_name" value={formData.business_name} onChange={handleChange} data-testid="signup-business-input" /></label><label>Password<input name="password" type="password" value={formData.password} onChange={handleChange} required data-testid="signup-password-input" /></label><label>Confirm password<input name="confirmPassword" type="password" value={formData.confirmPassword} onChange={handleChange} required data-testid="signup-confirm-password-input" /></label><button type="submit" disabled={loading} data-testid="signup-submit-button">{loading?'Creating account…':'Create account'}</button><p>Already have an account? <Link to="/login" data-testid="login-link">Sign in</Link></p></form><aside className="cm-panel cm-dark"><h2>Approve, edit, or dismiss.</h2><p className="cm-sub">Churvox prepares the admin queue and decision slips so the owner controls every critical move.</p></aside></section></div></main>
}
