import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";
import "./workBoardSystem.css";

const arr = (v) => Array.isArray(v) ? v : Array.isArray(v?.data) ? v.data : Array.isArray(v?.items) ? v.items : Array.isArray(v?.actions) ? v.actions : Array.isArray(v?.jobs) ? v.jobs : Array.isArray(v?.clients) ? v.clients : Array.isArray(v?.invoices) ? v.invoices : Array.isArray(v?.quotes) ? v.quotes : Array.isArray(v?.workers) ? v.workers : Array.isArray(v?.notifications) ? v.notifications : [];
const idOf = (v) => String(v?.id || v?._id || v?.uuid || "");
const low = (v) => String(v || "").toLowerCase();
const money = (v) => `$${Number(v || 0).toLocaleString("en-NZ", { maximumFractionDigits: 0 })}`;

const CONFIG = {
  jobs: { area: "FIELD WORK", title: "Job board", subtitle: "Needs fixing, today's work, in field and ready to bill.", primary: "New job", to: "/jobs/new", endpoints: { jobs: "/jobs" } },
  clients: { area: "CUSTOMERS", title: "Customer board", subtitle: "Active clients, missing info, recent work and follow-ups.", primary: "Add client", to: "/clients/new", endpoints: { clients: "/clients", jobs: "/jobs", quotes: "/quotes" } },
  invoices: { area: "MONEY", title: "Invoice board", subtitle: "Drafts, sent, overdue and paid invoices.", primary: "New invoice", to: "/invoices/new", endpoints: { invoices: "/invoices", jobs: "/jobs" } },
  quotes: { area: "SALES", title: "Quote board", subtitle: "Drafts, sent quotes, follow-ups and accepted work.", primary: "New quote", to: "/quotes/new", endpoints: { quotes: "/quotes", clients: "/clients" } },
  team: { area: "CREW", title: "Crew board", subtitle: "Workers, invites, role gaps and workload.", primary: "Open team", to: "/team", endpoints: { workers: "/team/workers", jobs: "/jobs" } },
  settings: { area: "CONTROL", title: "Settings board", subtitle: "Business setup, access, plan controls and integrations.", primary: "Main board", to: "/dashboard", endpoints: {} },
  reports: { area: "REPORTS", title: "Reports board", subtitle: "Money, jobs, quotes and exports in one view.", primary: "Main board", to: "/dashboard", endpoints: { jobs: "/jobs", invoices: "/invoices", quotes: "/quotes" } },
  payroll: { area: "PAYROLL", title: "Payroll board", subtitle: "Workers, completed jobs, review items and payroll handoff.", primary: "Main board", to: "/dashboard", endpoints: { workers: "/team/workers", jobs: "/jobs" } },
  automation: { area: "AUTOMATION", title: "Automation board", subtitle: "Rules, runs, approvals and prepared admin actions.", primary: "Main board", to: "/dashboard", endpoints: { actions: "/ai-operator/actions" } },
  sms: { area: "MESSAGES", title: "Message board", subtitle: "Credits, history, reminders and safe SMS controls.", primary: "Main board", to: "/dashboard", endpoints: { history: "/sms/history", balance: "/sms/balance", invoices: "/invoices" } },
  integrations: { area: "SYNC", title: "Integrations board", subtitle: "MYOB, accounting sync and invoice state.", primary: "Main board", to: "/dashboard", endpoints: { invoices: "/invoices" } },
  notifications: { area: "ALERTS", title: "Notifications board", subtitle: "Unread alerts, approvals and recent updates.", primary: "Main board", to: "/dashboard", endpoints: { notifications: "/notifications", actions: "/ai-operator/actions" } },
  dispatch: { area: "SCHEDULE", title: "Dispatch board", subtitle: "Crew, scheduled work, in-field movement and conflicts.", primary: "New job", to: "/jobs/new", endpoints: { jobs: "/jobs", workers: "/team/workers" } },
};

function job(j) { const s = low(j.status); const worker = j.assigned_worker_name || j.worker_name || ""; const unassigned = !worker && !j.assigned_worker_id; const complete = ["completed", "complete", "done"].includes(s); return { id: `job-${idOf(j)}`, title: j.title || j.job_name || j.client_name || "Job", detail: j.address || j.description || j.client_name || "Job record", label: unassigned ? "Unassigned" : complete ? "Completed" : s || "Job", to: `/jobs/${idOf(j)}`, amount: j.price || j.job_price || j.fixed_price || j.total || j.amount || 0, status: s, raw: j }; }
function client(c) { return { id: `client-${idOf(c)}`, title: c.name || c.client_name || c.customer_name || "Client", detail: c.email || c.phone || c.address || "Client record", label: c.email && c.phone ? "Complete" : "Missing info", to: `/clients/${idOf(c)}` }; }
function quote(q) { const s = low(q.status); return { id: `quote-${idOf(q)}`, title: q.title || q.customer_name || q.client_name || "Quote", detail: q.description || "Quote record", label: s || "Quote", to: `/quotes/${idOf(q)}`, amount: q.total || q.amount || q.price || 0, status: s }; }
function invoice(i) { const s = low(i.status); const amount = i.balance_due || i.balance || i.total || i.amount || 0; return { id: `invoice-${idOf(i)}`, title: i.customer_name || i.client_name || i.invoice_number || "Invoice", detail: i.description || "Invoice record", label: s || "Invoice", to: `/invoices/${idOf(i)}`, amount, status: s }; }
function worker(w) { return { id: `worker-${idOf(w)}`, title: w.name || w.full_name || w.email || "Worker", detail: w.role || w.email || w.phone || "Worker record", label: w.invite_status || w.status || w.role || "Worker", to: "/team" }; }
function simple(id, title, detail, label, to = "#") { return { id, title, detail, label, to }; }

function build(area, data) {
  const jobs = arr(data.jobs).map(job), clients = arr(data.clients).map(client), quotes = arr(data.quotes).map(quote), invoices = arr(data.invoices).map(invoice), workers = arr(data.workers).map(worker), actions = arr(data.actions).map((a) => simple(`action-${idOf(a)}`, a.title || a.summary || "Approval", a.reason || a.recommendation || "Prepared action", a.status || "Approval"));
  if (area === "jobs" || area === "dispatch") return [["Needs fixing", jobs.filter(j => j.label === "Unassigned"), "Missing workers or blocked work."], ["Today's work", jobs.filter(j => !["completed", "complete", "done", "cancelled"].includes(j.status)), "Scheduled and active jobs."], ["In field", jobs.filter(j => ["in_progress", "in progress", "started", "paused"].includes(j.status)), "Workers moving now."], ["Ready to bill", jobs.filter(j => ["completed", "complete", "done"].includes(j.status) && !(j.raw.invoice_id || j.raw.draft_invoice_id || j.raw.invoiced)), "Finished work waiting for invoice."]];
  if (area === "clients") return [["Active clients", clients, "All customer records."], ["Missing info", clients.filter(c => c.label === "Missing info"), "Phone, email or details missing."], ["Recent work", jobs.slice(0, 12), "Jobs linked to customers."], ["Quote follow-ups", quotes.filter(q => !["accepted", "approved", "lost", "declined"].includes(q.status)), "Sales follow-up work."]];
  if (area === "invoices") return [["Drafts", invoices.filter(i => ["draft", "pending"].includes(i.status)), "Not sent yet."], ["Sent", invoices.filter(i => ["sent", "open", "unpaid"].includes(i.status)), "Money waiting."], ["Overdue", invoices.filter(i => i.status === "overdue"), "Needs chasing."], ["Paid", invoices.filter(i => ["paid", "complete", "completed"].includes(i.status)), "Money received."]];
  if (area === "quotes") return [["Drafts", quotes.filter(q => ["draft", "pending", ""].includes(q.status)), "Quotes being prepared."], ["Sent", quotes.filter(q => ["sent", "open"].includes(q.status)), "With customers."], ["Follow-up due", quotes.filter(q => !["accepted", "approved", "lost", "declined"].includes(q.status)), "Quotes to chase."], ["Accepted", quotes.filter(q => ["accepted", "approved"].includes(q.status)), "Ready for jobs."]];
  if (area === "team") return [["Active crew", workers.filter(w => !["pending", "invited"].includes(low(w.label))), "Ready to assign."], ["Invites", workers.filter(w => ["pending", "invited"].includes(low(w.label))), "Still setting up."], ["Workload", jobs.filter(j => j.label !== "Unassigned"), "Assigned jobs."], ["Needs setup", workers.filter(w => !w.label || w.label === "Worker"), "Missing setup."]];
  if (["reports", "payroll", "integrations"].includes(area)) return [["Money records", invoices, "Invoice records."], ["Job records", jobs, "Job activity."], ["People", workers, "Worker records."], ["Exports", [simple("export", "Export handoff", "Prepare records for accountant, payroll or admin.", "Export")], "Handoff work."]];
  if (area === "automation") return [["Approvals", actions, "Prepared AI actions."], ["Rules", [simple("rules", "Automation rules", "Create and manage rules here.", "Rules")], "Rules."], ["Runs", [simple("runs", "Automation runs", "Recent run history appears here.", "Runs")], "Runs."], ["Templates", [simple("templates", "Smart templates", "Reminder, invoice and job admin templates.", "Template")], "Templates."]];
  if (area === "sms") return [["Credits", [simple("credits", "SMS credits", data.balance?.balance !== undefined ? `${data.balance.balance} credits available` : "Credit balance loads here.", "Balance")], "Credits."], ["History", arr(data.history).map((h) => simple(`sms-${idOf(h)}`, h.to || h.client_name || "Message", h.message || h.body || "Message history", h.status || "Sent")), "Messages."], ["Reminders", invoices.filter(i => ["sent", "open", "overdue", "unpaid"].includes(i.status)), "Invoices needing reminders."], ["Safe mode", [simple("safe", "SMS controlled", "SMS stays approval-first until stable.", "Safe")], "Control."]];
  if (area === "notifications") return [["Unread", arr(data.notifications).filter(n => !n.read).map(n => simple(`n-${idOf(n)}`, n.title || "Notification", n.message || n.body || "Update", "Unread")), "Needs attention."], ["All updates", arr(data.notifications).map(n => simple(`n-${idOf(n)}`, n.title || "Notification", n.message || n.body || "Update", n.read ? "Read" : "Unread")), "Feed."], ["Approvals", actions, "Prepared actions."], ["History", [], "Recent alerts."]];
  return [["Business setup", [simple("biz", "Business profile", "Trade, business details and defaults.", "Control")], "Setup."], ["Access", [simple("access", "Users and roles", "Owner, Manager, Worker, Office Admin and Payroll.", "Roles")], "Access."], ["Plan", [simple("plan", "Plan controls", "Plan, limits and billing.", "Billing", "/plans")], "Billing."], ["Integrations", [simple("sync", "Connected tools", "MYOB, SMS and future sync.", "Sync", "/integrations")], "Tools."]];
}

function Ticket({ item }) { const body = <><span>{item.label}</span><strong>{item.title}</strong><em>{item.amount ? `${money(item.amount)} · ${item.detail}` : item.detail}</em></>; return item.to && item.to !== "#" ? <Link className="wba-ticket" to={item.to}>{body}</Link> : <button className="wba-ticket" type="button">{body}</button>; }
function Lane({ title, items, detail, index }) { return <section className={`wba-lane wba-lane-${index + 1}`}><div className="wba-lane-head"><div><p>{title}</p><span>{detail}</span></div><strong>{items.length}</strong></div><div className="wba-ticket-list">{items.length ? items.slice(0, 10).map(item => <Ticket key={item.id} item={item} />) : <div className="wba-clear"><strong>Clear</strong><span>Nothing sitting here right now.</span></div>}</div></section>; }

export default function WorkBoardAreaPage({ area }) {
  const config = CONFIG[area] || CONFIG.jobs;
  const { get } = useApi();
  const [data, setData] = useState({});
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const next = {}; await Promise.all(Object.entries(config.endpoints || {}).map(async ([key, path]) => { try { const res = await get(path); next[key] = res?.data ?? res?.[key] ?? res ?? []; } catch { next[key] = []; } })); setData(next); setLoading(false); }, [config, get]);
  useEffect(() => { load(); }, [load]);
  const lanes = useMemo(() => build(area, data), [area, data]);
  const total = lanes.reduce((s, l) => s + l[1].length, 0);
  const amount = lanes.flatMap(l => l[1]).reduce((s, i) => s + Number(i.amount || 0), 0);
  return <main className="wba" data-version="CHURVOX_WORK_BOARD_AREA_PAGES_20260524"><header className="wba-hero"><div><p>{config.area}</p><h1>{config.title}</h1><span>{config.subtitle}</span></div><div className="wba-hero-actions"><Link className="wba-primary" to={config.to}>{config.primary}</Link><Link to="/dashboard">Main Work Board</Link></div></header><section className="wba-stats"><button className="wba-stat"><span>On board</span><strong>{total}</strong><em>records visible</em></button><button className="wba-stat"><span>Needs attention</span><strong>{lanes[0]?.[1]?.length || 0}</strong><em>{lanes[0]?.[0] || "work"}</em></button><button className="wba-stat"><span>Money shown</span><strong>{money(amount)}</strong><em>visible amount</em></button><button className="wba-stat"><span>Mode</span><strong>{loading ? "Loading" : "Live"}</strong><em>real app data</em></button></section><section className="wba-board">{lanes.map(([title, items, detail], index) => <Lane key={title} title={title} items={items} detail={detail} index={index} />)}</section></main>;
}
