export const WORLD_LEDGER_PRESETS = [
  {
    code: "NZ",
    country: "New Zealand",
    currency: "NZD",
    locale: "en-NZ",
    taxName: "GST",
    defaultTaxRate: "15",
    invoiceTitle: "Taxable supply information",
    businessIdLabel: "NZBN",
    businessIdHint: "NZBN or GST number if registered",
    paymentTerms: "7 days",
    quoteExpiry: "14 days",
    dateFormat: "DD/MM/YYYY",
    addressFormat: "Street, suburb, city, postcode",
    exportPackName: "NZ bookkeeper pack",
    invoiceNumberPrefix: "INV-NZ",
    taxMode: "Tax added or included, owner selectable",
  },
  {
    code: "AU",
    country: "Australia",
    currency: "AUD",
    locale: "en-AU",
    taxName: "GST",
    defaultTaxRate: "10",
    invoiceTitle: "Tax invoice",
    businessIdLabel: "ABN",
    businessIdHint: "Australian Business Number",
    paymentTerms: "7 days",
    quoteExpiry: "14 days",
    dateFormat: "DD/MM/YYYY",
    addressFormat: "Street, suburb, state, postcode",
    exportPackName: "AU bookkeeper pack",
    invoiceNumberPrefix: "INV-AU",
    taxMode: "Tax added or included, owner selectable",
  },
  {
    code: "GB",
    country: "United Kingdom",
    currency: "GBP",
    locale: "en-GB",
    taxName: "VAT",
    defaultTaxRate: "20",
    invoiceTitle: "VAT invoice",
    businessIdLabel: "VAT number",
    businessIdHint: "VAT number or company number if used",
    paymentTerms: "14 days",
    quoteExpiry: "14 days",
    dateFormat: "DD/MM/YYYY",
    addressFormat: "Street, town/city, county, postcode",
    exportPackName: "UK accountant pack",
    invoiceNumberPrefix: "INV-UK",
    taxMode: "VAT standard/manual rate, owner selectable",
  },
  {
    code: "US",
    country: "United States",
    currency: "USD",
    locale: "en-US",
    taxName: "Sales tax",
    defaultTaxRate: "0",
    invoiceTitle: "Invoice",
    businessIdLabel: "Business ID / EIN",
    businessIdHint: "EIN, state tax ID or local business ID if used",
    paymentTerms: "14 days",
    quoteExpiry: "14 days",
    dateFormat: "MM/DD/YYYY",
    addressFormat: "Street, city, state, ZIP",
    exportPackName: "US bookkeeper pack",
    invoiceNumberPrefix: "INV-US",
    taxMode: "Manual state/local sales tax",
  },
  {
    code: "CA",
    country: "Canada",
    currency: "CAD",
    locale: "en-CA",
    taxName: "GST/HST/PST",
    defaultTaxRate: "5",
    invoiceTitle: "Tax invoice",
    businessIdLabel: "Business number",
    businessIdHint: "CRA business number / GST/HST account if registered",
    paymentTerms: "14 days",
    quoteExpiry: "14 days",
    dateFormat: "YYYY-MM-DD",
    addressFormat: "Street, city, province, postal code",
    exportPackName: "Canada bookkeeper pack",
    invoiceNumberPrefix: "INV-CA",
    taxMode: "Province-aware manual GST/HST/PST",
  },
  {
    code: "ZA",
    country: "South Africa",
    currency: "ZAR",
    locale: "en-ZA",
    taxName: "VAT",
    defaultTaxRate: "15",
    invoiceTitle: "Tax invoice",
    businessIdLabel: "VAT number / registration number",
    businessIdHint: "VAT number if registered, company registration if used",
    paymentTerms: "7 days",
    quoteExpiry: "14 days",
    dateFormat: "YYYY/MM/DD",
    addressFormat: "Street, suburb, city, postal code",
    exportPackName: "SA bookkeeper pack",
    invoiceNumberPrefix: "INV-ZA",
    taxMode: "VAT standard/manual rate, owner selectable",
  },
];

export const WORLD_LEDGER_GUARDRAILS = [
  "Draft invoices only until the owner approves.",
  "No automatic invoice sending.",
  "No tax filing or government submission.",
  "No bank payout files.",
  "Payments are marked paid only after confirmed records are refreshed.",
  "Bookkeeper exports stay reviewable before handoff.",
];

export function findWorldLedgerPreset(code) {
  const wanted = String(code || "NZ").toUpperCase();
  return WORLD_LEDGER_PRESETS.find((preset) => preset.code === wanted) || WORLD_LEDGER_PRESETS[0];
}

export function buildWorldLedgerSettings(preset, overrides = {}) {
  return {
    country_code: preset.code,
    country: preset.country,
    currency: preset.currency,
    locale: preset.locale,
    tax_name: overrides.tax_name || preset.taxName,
    tax_rate: String(overrides.tax_rate ?? preset.defaultTaxRate),
    invoice_title: overrides.invoice_title || preset.invoiceTitle,
    business_id_label: preset.businessIdLabel,
    business_id_value: overrides.business_id_value || "",
    business_id_hint: preset.businessIdHint,
    payment_terms: overrides.payment_terms || preset.paymentTerms,
    quote_expiry: overrides.quote_expiry || preset.quoteExpiry,
    date_format: preset.dateFormat,
    address_format: preset.addressFormat,
    export_pack_name: preset.exportPackName,
    invoice_number_prefix: overrides.invoice_number_prefix || preset.invoiceNumberPrefix,
    tax_mode: preset.taxMode,
    admin_ledger_mode: "draft_export_owner_approved",
    owner_approval_required: true,
    accounting_handoff: "draft_sync_or_export_only",
    guardrails: WORLD_LEDGER_GUARDRAILS,
  };
}
