import React from "react";
import { Link, useLocation } from "react-router-dom";
import { toast } from "sonner";
import { useApi } from "../hooks/useApi";

const nav=[["Command Board","/dashboard"],["Jobs","/jobs"],["Dispatch","/dispatch"],["Crew Map","/crew-map"],["Clients","/clients"],["Quotes","/quotes"],["Invoices","/invoices"],["Team","/team"],["Plans","/plans"],["Settings","/settings"],["Support","/support"]];
function val(x){return x!==undefined&&x!==null&&String(x).trim()!=="";}
function typeOf(a){return String(a?.action_type||a?.type||"").replaceAll("-","_").toLowerCase();}
function payload(a){return {...(a?.payload||{}),...(a?.draft_payload||{})};}
function name(t){if(t.includes("quote"))return"Quote follow-up";if(t.includes("invoice"))return t.includes("reminder")?"Payment reminder":"Invoice slip";if(t.includes("worker")||t.includes("assign"))return"Assign worker";if(t.includes("job"))return"Job review";return"Prepared slip";}
function missing(a){const t=typeOf(a),p=payload(a),m=[];if(t.includes("quote")){if(!val(p.quote_id||a.related_entity_id))m.push("quote");if(!val(p.customer_email))m.push("customer email");}else if(t.includes("invoice")){if(!val(p.invoice_id||a.related_entity_id||p.job_id))m.push("invoice/job");if(!val(p.customer_email)&&!t.includes("draft"))m.push("customer email");if(t.includes("draft")&&!val(p.description))m.push("description");}else if(t.includes("worker")||t.includes("assign")){if(!val(p.job_id||a.related_entity_id))m.push("job");if(!val(p.worker_id))m.push("worker");}else if(t.includes("job")){if(!val(p.job_id||a.related_entity_id))m.push("job");}else m.push("real action type");return m;}
function Side(){const {pathname}=useLocation();return <aside className="hidden w-[260px] shrink-0 bg-[#0f1722] p-4 text-white lg:block"><div className="mb-6 font-black">CHURVOX<br/><span className="text-xs text-slate-400">Command Desk</span></div>{nav.map(([l,h])=><Link key={h} to={h} className={`mb-1 block rounded-xl px-3 py-2 text-sm font-black ${pathname===h?"bg-cyan-300 text-slate-950":"text-slate-300 hover:bg-white/10"}`}>{l}</Link>)}</aside>}
export default function CommandDeskQueuePage(){const {get,post}=useApi();const [rows,setRows]=React.useState([]);const [busy,setBusy]=React.useState(false);const load=React.useCallback(async()=>{const r=await get("/ai/operator/approval-items");const data=Array.isArray(r?.data?.data)?r.data.data:Array.isArray(r?.data?.actions)?r.data.actions:[];setRows(data.filter(x=>!["completed","rejected","dismissed"].includes(String(x.status||"").toLowerCase())));},[get]);React.useEffect(()=>{load()},[load]);const scan=async()=>{setBusy(true);let r=await post("/ai/operator/scan-deep",{});if(!r?.success)r=await post("/ai/operator/scan",{});setBusy(false);if(r?.success){toast.success("AI scan complete");load()}else toast.error(r?.error||"AI scan failed")};return <main className="fixed inset-0 z-[2147483000] overflow-y-auto bg-[#f5f7f1]"><div className="flex min-h-screen"><Side/><section className="flex-1 p-6"><header className="mb-5 flex items-center justify-between rounded-3xl bg-white p-5"><div><div className="text-xs font-black uppercase tracking-widest text-slate-500">Command Board · prepared slips</div><h1 className="text-3xl font-black">Show slips, block bad approvals.</h1><p className="text-sm font-bold text-slate-500">Needs-detail slips stay visible so you can see what Churvox is missing.</p></div><button onClick={scan} disabled={busy} className="rounded-full bg-emerald-500 px-5 py-3 text-sm font-black text-white">{busy?"Scanning…":"Run AI scan"}</button></header><div className="grid gap-4 md:grid-cols-2">{rows.map(a=>{const m=missing(a),t=typeOf(a),p=payload(a);return <div key={a.id||a._id||a.title} className={`rounded-3xl border p-5 ${m.length?"border-amber-200 bg-amber-50":"border-emerald-200 bg-white"}`}><div className={`text-xs font-black uppercase tracking-widest ${m.length?"text-amber-700":"text-emerald-700"}`}>{m.length?"Needs details":"Ready"} · {name(t)}</div><h2 className="mt-2 text-xl font-black">{a.title||name(t)}</h2><p className="mt-2 text-sm font-bold text-slate-600">{m.length?`Missing: ${m.join(", ")}`:(a.summary||"Ready to check.")}</p><div className="mt-4 rounded-2xl bg-slate-950 p-3 text-xs font-bold text-white">{p.client_name||p.customer_name||p.job_title||p.quote_number||p.invoice_number||a.related_entity_id||"Open the source record to add details."}</div></div>})}</div>{!rows.length&&<div className="rounded-3xl bg-amber-50 p-6 font-black text-amber-900">No slips found. Run AI scan, then add a job, quote or invoice if none appear.</div>}</section></div></main>}
