import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Layout from "../components/Layout";
import { useApi } from "../hooks/useApi";

const TABS = [{k:"today",l:"Today"},{k:"tomorrow",l:"Tomorrow"},{k:"week",l:"This week"},{k:"all",l:"All"}];
const COLUMNS = ["unassigned","scheduled","in_progress","paused","completed","overdue"];

export default function DispatchBoardPage() {
  const api = useApi();
  const [jobs, setJobs] = useState([]); const [workers, setWorkers] = useState([]);
  const [filters, setFilters] = useState({ tab: "today", worker: "", status: "", date: "", q: "" });
  const [loading, setLoading] = useState(false); const [msg, setMsg] = useState("");
  const [reschedule, setReschedule] = useState({ id: "", date: "", time: "" }); const [busy, setBusy] = useState({});
  const load = async () => { setLoading(true); setMsg(""); const r = await api.get("/dispatch/summary"); if (r.success) { setJobs(r.data?.data?.jobs || []); setWorkers(r.data?.data?.workers || []);} else setMsg(r.error||"Failed to load dispatch."); setLoading(false); };
  useEffect(()=>{load();},[]);
  const statuses = useMemo(()=>Array.from(new Set(jobs.map((j)=>j.status).filter(Boolean))),[jobs]);
  const filtered = useMemo(()=>jobs.filter((j)=>{
    const q = filters.q.toLowerCase();
    return (!q || [j.title,j.type,j.customer_name,j.address].join(" ").toLowerCase().includes(q)) && (!filters.worker || (j.assigned_worker_id||"")===filters.worker) && (!filters.status || j.status===filters.status);
  }),[jobs,filters]);
  const byCol=(col)=>filtered.filter((j)=>(j.dispatch_status||j.status||"unassigned")===col);
  const action = async (k, fn) => { if (busy[k]) return; setBusy((b)=>({...b,[k]:true})); await fn(); setBusy((b)=>({...b,[k]:false})); };
  return <Layout><div className="cx-page"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black text-slate-950">Dispatch Board</h1><p className="text-slate-700">Assign, schedule, and track field work from one board.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border px-3 py-2 text-sm font-bold text-slate-700">Refresh</button><Link to="/jobs/new" className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-bold text-white">Create job</Link></div></div>
  {msg && <p className="mt-3 text-sm text-slate-700">{msg}</p>}
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[{l:"Unassigned",v:byCol("unassigned").length},{l:"Scheduled today",v:byCol("scheduled").length},{l:"In progress",v:byCol("in_progress").length},{l:"Overdue",v:byCol("overdue").length},{l:"Completed",v:byCol("completed").length}].map((s)=><div key={s.l} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-bold text-slate-700">{s.l}</p><p className="text-xl font-black text-slate-950">{s.v}</p></div>)}</div>
  <input className="mt-4 w-full rounded-xl border border-slate-300 p-2" placeholder="Search jobs, clients, address" value={filters.q} onChange={(e)=>setFilters(f=>({...f,q:e.target.value}))}/>
  <div className="mt-3 flex flex-wrap gap-2">{TABS.map((t)=><button key={t.k} onClick={()=>setFilters((f)=>({...f,tab:t.k}))} className={`rounded-full border px-3 py-1 text-sm ${filters.tab===t.k?"bg-blue-600 text-white":"text-slate-700"}`}>{t.l}</button>)}</div>
  <div className="mt-3 grid gap-2 md:grid-cols-3"><select className="rounded-xl border p-2" value={filters.worker} onChange={(e)=>setFilters((f)=>({...f,worker:e.target.value}))}><option value="">All workers</option>{workers.length?workers.map((w)=><option key={w.id||w._id} value={w.id||w._id}>{w.name||w.email}</option>):<option disabled>Worker list unavailable</option>}</select><select className="rounded-xl border p-2" value={filters.status} onChange={(e)=>setFilters((f)=>({...f,status:e.target.value}))}><option value="">All status</option>{statuses.map((s)=><option key={s} value={s}>{s}</option>)}</select><input type="date" className="rounded-xl border p-2" value={filters.date} onChange={(e)=>setFilters((f)=>({...f,date:e.target.value}))}/></div>
  <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{COLUMNS.map((col)=><div key={col} className="rounded-3xl border border-slate-200 p-3"><h2 className="font-bold text-slate-900 capitalize">{col.replaceAll("_"," ")}</h2>{byCol(col).length===0?<p className="text-sm text-slate-700">No jobs</p>:byCol(col).map((j)=><div key={j.id||j._id} className="mt-2 rounded-2xl border p-3"><p className="font-bold text-slate-900">{j.title||j.type||"Untitled"}</p><p className="text-sm text-slate-700">{j.customer_name||"Unknown customer"}</p><p className="text-sm text-slate-700">{j.address||"No address"}</p><p className="text-sm text-slate-700">{j.scheduled_date||"Unscheduled"} • {j.assigned_worker_name||"Unassigned"}</p>{j.conflict?<p className="mt-1 text-xs text-amber-700">Schedule conflict flagged for this job.</p>:null}
  <div className="mt-2 flex flex-wrap gap-2"><select className="rounded border p-1 text-xs" defaultValue="" disabled={!workers.length||busy[j.id]} onChange={(e)=>action(j.id||j._id, async()=>{ if(!e.target.value) return; const r=await api.post(`/dispatch/jobs/${j.id||j._id}/assign`,{worker_id:e.target.value}); setMsg(r.success?"Worker assigned.":(r.error||"Assign failed.")); if(r.success) load();})}><option value="">Quick assign</option>{workers.map((w)=><option key={w.id||w._id} value={w.id||w._id}>{w.name||w.email}</option>)}</select><button className="rounded border px-2 py-1 text-xs" onClick={()=>setReschedule({id:j.id||j._id,date:j.scheduled_date?.slice(0,10)||"",time:""})}>Reschedule</button><Link className="rounded border px-2 py-1 text-xs" to={`/jobs/${j.id || j._id}`}>Open job</Link></div></div>)}</div>)}</div></div>
  {reschedule.id && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-4"><h3 className="font-black text-slate-900">Reschedule job</h3><div className="mt-2 grid grid-cols-2 gap-2"><input type="date" className="rounded border p-2" value={reschedule.date} onChange={(e)=>setReschedule((v)=>({...v,date:e.target.value}))}/><input type="time" className="rounded border p-2" value={reschedule.time} onChange={(e)=>setReschedule((v)=>({...v,time:e.target.value}))}/></div><div className="mt-3 flex justify-end gap-2"><button className="rounded border px-3 py-2" onClick={()=>setReschedule({id:"",date:"",time:""})}>Cancel</button><button className="rounded bg-blue-600 px-3 py-2 text-white" disabled={!reschedule.date} onClick={async()=>{const scheduled_date=`${reschedule.date}${reschedule.time?`T${reschedule.time}`:""}`; const r=await api.post(`/dispatch/jobs/${reschedule.id}/reschedule`,{scheduled_date}); setMsg(r.success?"Job rescheduled.":(r.error||"Reschedule failed.")); setReschedule({id:"",date:"",time:""}); if(r.success) load();}}>Save</button></div></div></div>}
  </div></Layout>;
}
