import React, { useEffect, useMemo, useState } from "react";
import Layout from "../components/Layout";
import { useApi } from "../hooks/useApi";

export default function RecurringJobsPage(){const api=useApi(); const [items,setItems]=useState([]); const [workers,setWorkers]=useState([]); const [msg,setMsg]=useState(""); const [q,setQ]=useState(""); const [status,setStatus]=useState(""); const [freq,setFreq]=useState(""); const [busy,setBusy]=useState(false);
const [form,setForm]=useState({title:"",client_name:"",address:"",assigned_worker_id:"",start_date:"",frequency:"weekly",custom_interval_days:"",notes:""});
const load=()=>api.get('/recurring-jobs').then(r=>{if(r.success){setItems(r.data?.data?.items||r.data?.data||[]); setWorkers(r.data?.data?.workers||[]);}else setMsg(r.error||"Failed to load.")}); useEffect(()=>{load();},[]);
const filtered=useMemo(()=>items.filter(i=>(!q||`${i.title} ${i.client_name} ${i.address}`.toLowerCase().includes(q.toLowerCase()))&&(!status||i.status===status)&&(!freq||i.frequency===freq)),[items,q,status,freq]);
const create=async()=>{if(!form.title.trim()) return setMsg("Title is required."); if(busy) return; setBusy(true); const payload={...form,custom_interval_days:form.frequency==="custom"?Number(form.custom_interval_days||0):undefined}; const r=await api.post('/recurring-jobs',payload); setBusy(false); setMsg(r.success?"Recurring job created.":(r.error||"Create failed.")); if(r.success){setForm({...form,title:""}); load();}};
return <Layout><div className="cx-page"><div className="rounded-3xl border bg-white p-6 shadow-sm"><h1 className="text-2xl font-black text-slate-950">Recurring Jobs</h1><p className="text-slate-700">Manage repeat work without creating jobs by hand every time.</p>
<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[{l:"Active",v:items.filter(i=>i.status==="active").length},{l:"Paused",v:items.filter(i=>i.status==="paused").length},{l:"Due this week",v:items.filter(i=>i.due_this_week).length},{l:"Generated jobs",v:items.reduce((a,b)=>a+(b.generated_count||0),0)}].map((s)=><div key={s.l} className="rounded-2xl border bg-slate-50 p-3"><p className="text-xs font-bold text-slate-700">{s.l}</p><p className="text-xl font-black text-slate-950">{s.v}</p></div>)}</div>
{msg&&<p className="mt-2 text-sm text-slate-700">{msg}</p>}
<div className="mt-4 rounded-2xl border p-3"><p className="font-bold text-slate-900">Create recurring job</p><div className="mt-2 grid gap-2 md:grid-cols-2"><input className="rounded border p-2" placeholder="Title" value={form.title} onChange={(e)=>setForm(f=>({...f,title:e.target.value}))}/><input className="rounded border p-2" placeholder="Client" value={form.client_name} onChange={(e)=>setForm(f=>({...f,client_name:e.target.value}))}/><input className="rounded border p-2" placeholder="Address" value={form.address} onChange={(e)=>setForm(f=>({...f,address:e.target.value}))}/><select className="rounded border p-2" value={form.assigned_worker_id} onChange={(e)=>setForm(f=>({...f,assigned_worker_id:e.target.value}))}><option value="">Assigned worker</option>{workers.map((w)=><option key={w.id||w._id} value={w.id||w._id}>{w.name||w.email}</option>)}</select><input type="date" className="rounded border p-2" value={form.start_date} onChange={(e)=>setForm(f=>({...f,start_date:e.target.value}))}/><select className="rounded border p-2" value={form.frequency} onChange={(e)=>setForm(f=>({...f,frequency:e.target.value}))}><option value="weekly">weekly</option><option value="fortnightly">fortnightly</option><option value="monthly">monthly</option><option value="custom">custom interval days</option></select>{form.frequency==="custom"&&<input type="number" className="rounded border p-2" placeholder="Custom interval days" value={form.custom_interval_days} onChange={(e)=>setForm(f=>({...f,custom_interval_days:e.target.value}))}/>}<textarea className="rounded border p-2 md:col-span-2" placeholder="Notes" value={form.notes} onChange={(e)=>setForm(f=>({...f,notes:e.target.value}))}/></div><button className="mt-3 rounded-xl bg-blue-600 px-3 py-2 font-bold text-white disabled:opacity-60" disabled={busy||!form.title.trim()} onClick={create}>Create recurring job</button></div>
<div className="mt-3 grid gap-2 md:grid-cols-3"><input className="rounded border p-2" placeholder="Search" value={q} onChange={(e)=>setQ(e.target.value)}/><select className="rounded border p-2" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">All status</option><option value="active">Active</option><option value="paused">Paused</option></select><select className="rounded border p-2" value={freq} onChange={(e)=>setFreq(e.target.value)}><option value="">All frequency</option><option value="weekly">weekly</option><option value="fortnightly">fortnightly</option><option value="monthly">monthly</option><option value="custom">custom</option></select></div>
{filtered.map(i=><div key={i.id||i._id} className="mt-2 rounded-2xl border p-3"><p className="font-black text-slate-900">{i.title}</p><p className="text-sm text-slate-700">{i.client_name||"-"} • {i.address||"-"}</p><p className="text-sm text-slate-700">{i.frequency} • next {i.next_run_date||"-"} • {i.assigned_worker_name||"Unassigned"}</p><p className="text-xs text-slate-700">Status: {i.status||"active"} • Last generated: {i.last_generated_date||"-"} • Generated: {i.generated_count||0}</p><div className="mt-2 flex flex-wrap gap-2"><button className="rounded border px-2 py-1 text-xs" onClick={()=>api.post(`/recurring-jobs/${i.id||i._id}/pause`,{}).then(load)}>Pause</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>api.post(`/recurring-jobs/${i.id||i._id}/resume`,{}).then(load)}>Resume</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>api.patch(`/recurring-jobs/${i.id||i._id}`,{title:i.title}).then(load)}>Edit</button><button className="rounded bg-blue-600 px-2 py-1 text-xs text-white" onClick={()=>window.confirm('Generate the next job now?')&&api.post(`/recurring-jobs/${i.id||i._id}/generate-next`,{}).then(load)}>Generate next</button></div></div>)}
</div></div></Layout>}
