import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Layout from "../components/Layout";
import { useApi } from "../hooks/useApi";

export default function RoutePlannerPage(){const api=useApi();const [date,setDate]=useState("");const [workerId,setWorkerId]=useState("");const [workers,setWorkers]=useState([]);const [jobs,setJobs]=useState([]);const [msg,setMsg]=useState("");
const load=async()=>{const r=await api.get(`/route-planner/day?date=${encodeURIComponent(date)}&worker_id=${encodeURIComponent(workerId)}`); if(r.success){setJobs(r.data?.data?.jobs||[]); setWorkers(r.data?.data?.workers||[]);} else setMsg(r.error||"Failed to load");};
useEffect(()=>{load();},[]); const move=(i,d)=>{const n=[...jobs];const j=n[i];n.splice(i,1);n.splice(i+d,0,j);setJobs(n);};
const mapsLink = useMemo(()=>{const a=jobs.map(j=>j.address).filter(Boolean); return a.length?`https://www.google.com/maps/dir/${a.map(encodeURIComponent).join('/')}`:"";},[jobs]);
return <Layout><div className="cx-page"><div className="rounded-3xl border bg-white p-6 shadow-sm"><h1 className="text-2xl font-black text-slate-950">Route Planner</h1><p className="text-slate-700">Plan a worker’s job order for the day.</p><p className="mt-2 rounded-xl border border-blue-100 bg-blue-50 p-2 text-sm text-slate-700">Manual route planning only. This is not live tracking.</p><div className="mt-3 grid gap-2 md:grid-cols-4"><input type="date" className="rounded-xl border p-2" value={date} onChange={(e)=>setDate(e.target.value)}/><select className="rounded-xl border p-2" value={workerId} onChange={(e)=>setWorkerId(e.target.value)}><option value="">Select worker</option>{workers.map((w)=><option key={w.id||w._id} value={w.id||w._id}>{w.name||w.email}</option>)}</select><button className="rounded-xl border px-3 py-2" onClick={load}>Refresh/load</button><button className="rounded-xl bg-blue-600 px-3 py-2 font-bold text-white disabled:opacity-60" disabled={!jobs.length} onClick={async()=>{const r=await api.post('/route-planner/sequence',{date,worker_id:workerId,jobs:jobs.map((j,i)=>({job_id:j.id||j._id,position:i+1}))});setMsg(r.success?"Sequence saved.":(r.error||"Save failed."));}}>Save sequence</button></div>
<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[{l:"Jobs selected",v:jobs.length},{l:"Stops with address",v:jobs.filter(j=>j.address).length},{l:"Unscheduled jobs",v:jobs.filter(j=>!j.scheduled_date).length},{l:"Manual order status",v:jobs.length?"Ready":"Empty"}].map((s)=><div key={s.l} className="rounded-2xl border bg-slate-50 p-3"><p className="text-xs font-bold text-slate-700">{s.l}</p><p className="font-black text-slate-950">{s.v}</p></div>)}</div>
{msg&&<p className="mt-2 text-sm text-slate-700">{msg}</p>}
{!jobs.length?<p className="mt-4 rounded-xl border p-3 text-slate-700">No jobs found for this worker/date.</p>:jobs.map((j,i)=><div key={j.id||j._id} className="mt-3 rounded-2xl border p-3"><p className="font-black text-slate-900">Stop {i+1}: {j.title||"Untitled"}</p><p className="text-sm text-slate-700">{j.customer_name||"Unknown client"} • {j.address||"No address"}</p><p className="text-sm text-slate-700">{j.scheduled_date||"Unscheduled"} • {j.status||"scheduled"}</p><div className="mt-2 flex gap-2"><button className="rounded border px-2 py-1 text-xs" disabled={i===0} onClick={()=>move(i,-1)}>Move up</button><button className="rounded border px-2 py-1 text-xs" disabled={i===jobs.length-1} onClick={()=>move(i,1)}>Move down</button><Link className="rounded border px-2 py-1 text-xs" to={`/jobs/${j.id||j._id}`}>Open job</Link></div></div>)}
{mapsLink && <a className="mt-4 inline-block rounded-xl border px-3 py-2 text-sm font-bold text-slate-700" href={mapsLink} target="_blank" rel="noreferrer">Open multi-stop in Google Maps</a>}
<p className="mt-3 text-sm text-slate-700">Advanced route optimisation is not configured. Manual ordering is available.</p></div></div></Layout>;}
