import React, { useEffect, useState } from "react";
import Layout from "../components/Layout";
import { useApi } from "../hooks/useApi";
const keys=["backend","database","stripe","sms","myob","email","ai","push"];
export default function SystemHealthPage(){const api=useApi(); const [s,setS]=useState({}); const [events,setEvents]=useState([]); const [checked,setChecked]=useState("");
const load=async()=>{const [a,b,c]=await Promise.all([api.get('/system-health/summary'),api.get('/system-health/events'),api.get('/system-health/integration-status')]); if(a.success) setS({...a.data?.data,...(c.data?.data||{})}); if(b.success) setEvents(b.data?.data||[]); setChecked(new Date().toISOString());}; useEffect(()=>{load();},[]);
return <Layout><div className="cx-page"><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-slate-950">System Health</h1><p className="text-slate-700">Check app, integration, and automation health.</p></div><button className="rounded-xl bg-blue-600 px-3 py-2 text-white" onClick={load}>Refresh</button></div><p className="mt-2 text-sm text-slate-700">Last checked: {checked||"-"}</p>
<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{keys.map((k)=><div key={k} className="rounded-2xl border p-3"><p className="font-bold capitalize text-slate-900">{k}</p><p className="text-sm text-slate-700">{s[k]?.status||"not_configured"}</p><p className="text-xs text-slate-700">{s[k]?.message||"Configuration status only."}</p></div>)}</div>
<div className="mt-4 rounded-2xl border p-3"><p className="font-bold text-slate-900">Operational issues</p><ul className="mt-2 list-disc pl-5 text-sm text-slate-700"><li>Failed automation runs: {s.failed_automation_runs||0}</li><li>MYOB sync failures: {s.myob_sync_failures||0}</li><li>SMS failures: {s.sms_failures||0}</li><li>Email failures: {s.email_failures||0}</li><li>Support tickets: {s.support_tickets||0}</li><li>Overdue invoices: {s.overdue_invoices||0}</li></ul></div>
<div className="mt-4 rounded-2xl border p-3"><p className="font-bold text-slate-900">Recent events</p>{events.length?events.map((e,idx)=><div key={idx} className="mt-2 rounded-xl border p-2 text-sm text-slate-700">{e.type||"event"}: {e.message||"-"} • {e.timestamp||"-"}</div>):<p className="mt-2 text-sm text-slate-700">No recent events.</p>}</div>
<div className="mt-4 flex flex-wrap gap-2">{[{l:"Automation Runs",to:"/automation/runs"},{l:"Integrations",to:"/integrations"},{l:"SMS",to:"/sms"},{l:"Reports",to:"/reports"},{l:"Support",to:"/support"}].map(x=><a key={x.to} href={x.to} className="rounded-xl border px-3 py-2 text-sm font-bold text-slate-700">{x.l}</a>)}</div>
</div></div></Layout>;}
