import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Link}from"react-router-dom";
import{useApi}from"../hooks/useApi";
import"./conceptC.css";
import"./conceptCCommandV2.css";
import"./conceptCCommandV21.css";
import"./conceptCCommandV22Target.css";
import"./conceptCCommandV23Logo.css";
import"./conceptCCommandV24SafeStatus.css";
import"./conceptCCommandV25RealStatus.css";
import"./conceptCCommandV26Breathe.css";
import"./conceptCCommandV27CrewMap.css";
import"./conceptCCommandV26WorkReviewSlip.css";

const arr=v=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:Array.isArray(v?.items)?v.items:Array.isArray(v?.jobs)?v.jobs:Array.isArray(v?.clients)?v.clients:Array.isArray(v?.invoices)?v.invoices:Array.isArray(v?.quotes)?v.quotes:Array.isArray(v?.workers)?v.workers:Array.isArray(v?.actions)?v.actions:Array.isArray(v?.notifications)?v.notifications:[];
const str=v=>String(v||""),low=v=>str(v).toLowerCase(),idOf=v=>str(v?.id||v?._id||v?.uuid||""),cash=v=>`$${Number(v||0).toLocaleString("en-NZ",{maximumFractionDigits:0})}`;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const pick=(r,...ks)=>{for(const k of ks){const v=r?.[k];if(v!==undefined&&v!==null&&String(v).trim()!=="")return v}return""};
const niceDate=v=>{if(!v)return"Not saved";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-NZ",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})};
const niceMins=v=>{const n=num(v);if(n===null)return"Not saved";const h=Math.floor(n/60),m=Math.round(n%60);return h?`${h}h ${m}m`:`${m}m`};
const countPhotos=r=>arr(r?.photos||r?.job_photos||r?.uploaded_photos||r?.completion_photos||r?.images||r?.attachments).length;
const locOf=r=>{const raw=r?.raw||r||{};const lat=num(raw.start_lat??raw.started_lat??raw.worker_lat??raw.current_lat??raw.location_lat??raw.lat??raw.latitude??raw.last_lat??raw.last_known_lat??raw.gps_lat);const lng=num(raw.start_lng??raw.started_lng??raw.worker_lng??raw.current_lng??raw.location_lng??raw.lng??raw.longitude??raw.last_lng??raw.last_known_lng??raw.gps_lng);return lat!==null&&lng!==null?{lat,lng}:null};
const reviewed=x=>{const r=x?.raw||{};const s=low(r.work_review_status||r.review_status||r.owner_review_status||r.approval_status);return Boolean(r.reviewed||r.owner_approved||r.work_approved||r.job_approved||r.approved_at||["approved","reviewed","accepted"].includes(s))};
const mapUrl=loc=>loc?`https://maps.google.com/maps?q=${encodeURIComponent(`${loc.lat},${loc.lng}`)}&z=15&output=embed`:"";
const mapLink=loc=>loc?`https://www.google.com/maps?q=${encodeURIComponent(`${loc.lat},${loc.lng}`)}`:"#";
const API={dashboard:{jobs:"/jobs",clients:"/clients",invoices:"/invoices",quotes:"/quotes",workers:"/team/workers",actions:"/ai-operator/actions",notifications:"/notifications"},jobs:{jobs:"/jobs",workers:"/team/workers",invoices:"/invoices",actions:"/ai-operator/actions"},dispatch:{jobs:"/jobs",workers:"/team/workers",actions:"/ai-operator/actions"},clients:{clients:"/clients",jobs:"/jobs",quotes:"/quotes",invoices:"/invoices"},quotes:{quotes:"/quotes",clients:"/clients",jobs:"/jobs",actions:"/ai-operator/actions"},invoices:{invoices:"/invoices",jobs:"/jobs",clients:"/clients",actions:"/ai-operator/actions"},team:{workers:"/team/workers",jobs:"/jobs",actions:"/ai-operator/actions"},sms:{history:"/sms/history",invoices:"/invoices",clients:"/clients",actions:"/ai-operator/actions"},notifications:{notifications:"/notifications",actions:"/ai-operator/actions",jobs:"/jobs"},reports:{jobs:"/jobs",invoices:"/invoices",quotes:"/quotes",clients:"/clients"},integrations:{invoices:"/invoices",actions:"/ai-operator/actions"},payroll:{workers:"/team/workers",jobs:"/jobs",actions:"/ai-operator/actions"},automation:{actions:"/ai-operator/actions",jobs:"/jobs",invoices:"/invoices"},settings:{actions:"/ai-operator/actions"}};
const P={dashboard:["Command Floor","The owner view for jobs, crew, money and admin."],jobs:["Jobs","Simple job workspace."],dispatch:["Dispatch","Assign and move work."],clients:["Clients","Customer records."],quotes:["Quotes","Quote follow-up."],invoices:["Invoices","Invoice control."],team:["Live Crew","Crew and roles."],sms:["Messages","Customer communication."],notifications:["Alerts","Updates and risks."],reports:["Reports","Completed records."],integrations:["Sync","Connected tools."],payroll:["Payroll","Crew summaries."],automation:["Automation","Rules and AI actions."],settings:["Settings","Business setup."]};
function useLive(area,get){const[data,setData]=useState({}),[loading,setLoading]=useState(true),endpoints=API[area]||API.dashboard;const load=useCallback(async()=>{setLoading(true);const next={};await Promise.all(Object.entries(endpoints).map(async([k,u])=>{try{const r=await get(u);next[k]=r?.data??r?.[k]??r??[]}catch{next[k]=[]}}));setData(next);setLoading(false)},[get,endpoints]);useEffect(()=>{load()},[load]);return{data,loading}}
function toItem(type,r){const id=idOf(r),status=low(r.status),base={type,id,raw:r,status,amount:0,href:"#"};if(type==="job"){const assigned=r.assigned_worker_id||r.assigned_worker_name||r.worker_name;return{...base,code:r.job_number||r.reference||`JOB-${id.slice(-4)||"000"}`,title:r.title||r.job_name||r.client_name||"Job",meta:r.address||r.description||r.client_name||"Job record",state:!assigned?"Unassigned":r.status||"Job",amount:r.price||r.job_price||r.fixed_price||r.total||r.amount||0,href:id?`/jobs/${id}`:"/jobs"}}if(type==="invoice")return{...base,code:r.invoice_number||`INV-${id.slice(-4)||"000"}`,title:r.customer_name||r.client_name||"Invoice",meta:r.description||r.email||"Invoice record",state:r.status||"Invoice",amount:r.balance_due||r.balance||r.total||r.amount||0,href:id?`/invoices/${id}`:"/invoices"};if(type==="quote")return{...base,code:r.quote_number||`QTE-${id.slice(-4)||"000"}`,title:r.title||r.customer_name||r.client_name||"Quote",meta:r.description||"Quote record",state:r.status||"Quote",amount:r.total||r.amount||r.price||0,href:id?`/quotes/${id}`:"/quotes"};if(type==="client")return{...base,code:"CLIENT",title:r.name||r.client_name||r.customer_name||"Client",meta:r.email||r.phone||r.address||"Client record",state:r.email&&r.phone?"Good":"Missing details",href:id?`/clients/${id}`:"/clients"};if(type==="worker"){const job=r.current_job_title||r.active_job_title||r.current_job_id||r.active_job_id;return{...base,code:"CREW",title:r.name||r.full_name||r.email||"Worker",meta:job?`On site · ${job}`:(r.role||r.email||"Worker record"),state:locOf(r)?"GPS captured":(job?"On job":"Worker"),href:"/team"}}return{...base,code:type==="alert"?"ALERT":"AI",title:r.title||r.summary||r.subject||"Prepared action",meta:r.message||r.reason||r.description||r.body||"Prepared for review.",state:r.status||"Review",href:r.target_url||r.url||"#"}}
function build(d){const jobs=arr(d.jobs).map(x=>toItem("job",x)),invoices=arr(d.invoices).map(x=>toItem("invoice",x)),quotes=arr(d.quotes).map(x=>toItem("quote",x)),clients=arr(d.clients).map(x=>toItem("client",x)),crew=arr(d.workers).map(x=>toItem("worker",x)),actions=arr(d.actions).map(x=>toItem("action",x)),alerts=arr(d.notifications).map(x=>toItem("alert",x)),messages=arr(d.history).map(x=>toItem("message",x));const doneJobs=jobs.filter(x=>["completed","complete","done"].includes(x.status)),workReview=doneJobs.filter(x=>!reviewed(x)).map(x=>({...x,type:"work_review",state:locOf(x)?"GPS verified":"Needs review",meta:`${x.meta} · finished work`})),openJobs=jobs.filter(x=>!["completed","complete","done","cancelled"].includes(x.status)),active=jobs.filter(x=>["in_progress","in progress","started","paused"].includes(x.status)),unassigned=jobs.filter(x=>x.state==="Unassigned"),bill=doneJobs.filter(x=>!(x.raw.invoice_id||x.raw.draft_invoice_id||x.raw.invoiced)),owing=invoices.filter(x=>["sent","open","unpaid","overdue"].includes(x.status)),overdue=invoices.filter(x=>x.status==="overdue"),draftInvoices=invoices.filter(x=>["draft","pending",""] .includes(x.status)),draftQuotes=quotes.filter(x=>["draft","pending",""] .includes(x.status)),quoteFollow=quotes.filter(x=>!["accepted","approved","lost","declined"].includes(x.status)),accepted=quotes.filter(x=>["accepted","approved"].includes(x.status)),clientWatch=clients.filter(x=>x.state==="Missing details"),done=[...doneJobs,...invoices.filter(x=>["paid","complete","completed"].includes(x.status)),...accepted],actionQueue=actions,dispatch=[...unassigned,...openJobs.filter(x=>!active.includes(x))],issues=[...overdue,...unassigned,...clientWatch],money=[...owing,...bill,...draftInvoices],live=[...active.map(x=>({...x,state:locOf(x)?"GPS captured":(x.state||"On job")})),...crew.filter(x=>locOf(x)||["gps captured","on job"].includes(low(x.state))),...crew].slice(0,10),needs=[...actionQueue,...workReview,...issues,...quoteFollow];return{jobs,invoices,quotes,clients,crew,actions,alerts,messages,doneJobs,workReview,openJobs,active,unassigned,bill,owing,overdue,draftInvoices,draftQuotes,quoteFollow,accepted,clientWatch,done,actionQueue,needs,issues,money,live,dispatch}}
const sum=a=>a.reduce((n,x)=>n+Number(x.amount||0),0);
function Sidebar(){return <aside className="cc-side"><Link className="cc-side-brand" to="/dashboard"><b>Churvox</b><span>Command Floor</span></Link><nav>{[["dashboard","Command Floor"],["jobs","Jobs"],["team","Live Crew"],["clients","Clients"],["invoices","Invoices"],["quotes","Quotes"],["dispatch","Dispatch"],["notifications","Issues"],["reports","Reports"],["settings","Settings"]].map(([p,l])=><Link key={p} to={p==="dashboard"?"/dashboard":`/${p}`}>{l}</Link>)}</nav><div className="cc-service"><b>Churvox Services</b><span>Business workspace</span></div></aside>}
function Top({loading}){return <header className="cc-top"><div className="cc-search">Search jobs, clients, invoices… <em>⌘ K</em></div><nav><Link to="/ai-operator/approvals">Take Action</Link><Link to="/jobs/new">+ Job</Link><Link to="/clients/new">+ Client</Link><Link to="/invoices">Money Desk</Link></nav><div className="cc-user"><b>{loading?"Syncing":"Live"}</b><span>Owner</span></div></header>}
function Stat({label,value,note,tone}){return <article className={`cc-stat ${tone||""}`}><span>{label}</span><b>{value}</b><small>{note}</small></article>}
function ActionRow({x,onPick,i}){const tags=["Review","Action","Approve","Follow Up","Fix"];return <button className={`cc-action-row tone-${i%5}`} onClick={()=>onPick(x)} type="button"><i/><div><b>{x.title}</b><span>{x.meta}</span></div><em>{tags[i%tags.length]}</em><small>{x.state}</small></button>}
function MiniRow({x,onPick,live}){return <button className={live?"cc-mini live":"cc-mini"} type="button" onClick={()=>onPick(x)}><i/><div><b>{x.title}</b><span>{x.code} · {x.meta}</span></div><em>{Number(x.amount||0)>0?cash(x.amount):x.state}</em></button>}
function Panel({title,kicker,items,onPick,children,className="",value,link,note}){return <section className={`cc-panel ${className}`}><header><div><p>{kicker}</p><h2>{title}</h2></div>{value!==undefined&&<strong>{value}</strong>}{link&&<Link to={link}>View all</Link>}</header>{children||<div className="cc-list">{items?.length?items.slice(0,5).map((x,i)=><MiniRow key={`${title}-${i}`} x={x} onPick={onPick}/>):<div className="cc-empty">Clear right now.</div>}</div>}{note&&<small className="cc-category-note">{note}</small>}</section>}
function MoneyPanel({m,onPick}){return <Panel title="Money Desk / Cashflow" kicker="Invoices only" className="cc-money" value={cash(sum(m.money))} link="/invoices" note="Only ready-to-bill, owing and invoice money appears here."><div className="cc-money-main"><div><span>Net cashflow</span><b>{cash(sum(m.owing)+sum(m.bill))}</b><small>Ready to bill and owing now</small></div><svg viewBox="0 0 160 60" aria-hidden="true"><polyline points="0,50 18,34 34,40 50,22 66,30 82,18 98,25 116,12 132,20 150,8" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg></div><div className="cc-money-stats"><Stat label="Ready" value={cash(sum(m.bill))} note={`${m.bill.length} jobs`} tone="blue"/><Stat label="Owing" value={cash(sum(m.owing))} note={`${m.owing.length} invoices`} tone="gold"/><Stat label="Overdue" value={cash(sum(m.overdue))} note={`${m.overdue.length} risks`} tone="red"/></div><div className="cc-list compact">{m.money.slice(0,4).map((x,i)=><MiniRow key={`money-${i}`} x={x} onPick={onPick}/>)}</div></Panel>}
function LivePanel({m,onPick}){return <Panel title="Live Crew / On Job Now" kicker="Workers only" className="cc-live" value={m.live.length} link="/team" note="Only worker/on-job status and GPS evidence appears here."><div className="cc-live-grid"><button className="cc-live-map-open" type="button" onClick={()=>onPick({type:"crew_map",title:"Live Crew Map",meta:"Owner view of worker/job GPS evidence.",state:"Owner map",raw:{crew:m.live},href:"#"})}><i/></button><div className="cc-list compact">{m.live.slice(0,5).map((x,i)=><MiniRow key={`live-${i}`} x={x} onPick={onPick} live/>)}</div></div><footer>Tap the map area to open the owner crew map.</footer></Panel>}
function CrewMapSlip({x}){const crew=arr(x?.raw?.crew),withGps=crew.map(c=>({c,loc:locOf(c)})).filter(x=>x.loc),first=withGps[0]?.loc;return <div className="cc-crew-map-slip"><div className="cc-crew-map-box">{first?<iframe title="Live crew map" src={mapUrl(first)} loading="lazy"/>:<div className="cc-crew-map-empty"><div><b>No crew GPS captured yet</b><span>When a worker starts a job and location evidence is saved, the owner map will show the real worker/job position here. Churvox will not fake map pins.</span></div></div>}</div><div className="cc-crew-map-list">{crew.length?crew.slice(0,10).map((c,i)=>{const loc=locOf(c);return <div className="cc-crew-map-row" key={`crew-map-${i}`}><div><b>{c.title}</b><span>{c.meta} · {loc?`${loc.lat.toFixed(5)}, ${loc.lng.toFixed(5)}`:"No GPS captured"}</span></div>{loc?<a href={mapLink(loc)} target="_blank" rel="noreferrer">Open map</a>:<em>No GPS</em>}</div>}):<div className="cc-crew-map-row"><div><b>No live crew yet</b><span>Workers will appear here when they are invited, active, or on jobs.</span></div><em>Clear</em></div>}</div></div>}
function WorkReviewDetails({x}){const r=x?.raw||{},pc=countPhotos(r),price=x.amount||r.price||r.job_price||r.fixed_price||r.total||r.amount||0;const details=[["Worker",pick(r,"assigned_worker_name","worker_name","completed_by_name","finished_by_name")||"Not saved"],["Client",pick(r,"client_name","customer_name")||"Not saved"],["Address",pick(r,"address","site_address","job_address","property_address")||"Not saved"],["Started",niceDate(pick(r,"started_at","start_time","actual_start_time","timer_started_at"))],["Finished",niceDate(pick(r,"completed_at","finished_at","actual_end_time","end_time","updated_at"))],["Total time",niceMins(pick(r,"total_minutes","worked_minutes","duration_minutes","net_minutes","time_spent_minutes"))],["Paused time",niceMins(pick(r,"paused_minutes","total_paused_minutes","pause_minutes"))],["Photos",pc?`${pc} uploaded`:"None saved"],["Invoice readiness",Number(price)>0?"Ready to bill":"Price missing"]];const notes=pick(r,"completion_notes","worker_notes","job_notes","notes","description")||"No worker notes saved.";return <div className="cc-work-extra">{details.map(([k,v],i)=><div key={k} className={i===2?"wide":""}><span>{k}</span><b>{v}</b></div>)}<article><span>Worker notes</span><p>{notes}</p></article></div>}
function StatusStrip({m}){return <footer className="cc-status-strip"><span className="green"><i/>Active Crew <b>{m.live.length}</b></span><span className="gold"><i/>Owing <b>{cash(sum(m.owing))}</b></span><span><i/>Completed <b>{m.doneJobs.length}</b></span><span><i/>In Progress <b>{m.active.length}</b></span><span className={m.needs.length?"red":"green"}><i/>AI Waiting <b>{m.actionQueue.length}</b></span><span><i/>Operator <b>Live</b></span></footer>}
function Dashboard({m,onPick,loading}){return <main className="cc-app" data-version="CHURVOX_COMMAND_FLOOR_V31_WORK_REVIEW_DETAILS_20260525"><div className="cc-bg"/><Sidebar/><section className="cc-main"><Top loading={loading}/><section className="cc-snapshot"><p>Today's operating position</p><Stat label="Take Action" value={m.actionQueue.length} note="prepared for approval" tone="red"/><Stat label="Work Review" value={m.workReview.length} note="finished jobs" tone="green"/><Stat label="Unassigned Jobs" value={m.unassigned.length} note="need a worker" tone="blue"/><Stat label="Crew On Job" value={m.live.length} note="worker status" tone="green"/><Stat label="Ready To Bill" value={cash(sum(m.bill))} note={`${m.bill.length} jobs ready`} tone="blue"/><Stat label="Owing" value={cash(sum(m.owing))} note="invoice money" tone="gold"/></section><section className="cc-grid"><Panel title="Take Action" kicker="AI prepared" className="cc-actions" value={m.actionQueue.length} link="/ai-operator/approvals" note="Only AI/operator actions appear here."><div className="cc-action-list">{m.actionQueue.length?m.actionQueue.slice(0,6).map((x,i)=><ActionRow key={`act-${i}`} x={x} onPick={onPick} i={i}/>):<div className="cc-empty">No priority actions waiting.</div>}</div><footer>AI Operator is working for you.</footer></Panel><LivePanel m={m} onPick={onPick}/><MoneyPanel m={m} onPick={onPick}/><Panel title="Dispatch / Today" kicker="Jobs only" className="cc-dispatch" items={m.dispatch} onPick={onPick} link="/dispatch" note="Only unassigned and scheduled/open jobs appear here."/><Panel title="Work Review" kicker="Finished work" className="cc-quotes cc-work-review" items={m.workReview} onPick={onPick} link="/jobs" note="Finished jobs waiting for owner review appear here."/><Panel title="Client Watch" kicker="Clients only" className="cc-clients" items={m.clientWatch} onPick={onPick} link="/clients" note="Only client records needing attention appear here."/><Panel title="Issues / Risks" kicker="Fix first" className="cc-risks" items={m.issues} onPick={onPick} link="/notifications" note="Only overdue, missing info and operational risks appear here."/></section></section><StatusStrip m={m}/></main>}
function SimplePage({area,m,onPick,loading}){const title=P[area]?.[0]||"Workspace",sub=P[area]?.[1]||"Simple workspace";const map={jobs:m.jobs,dispatch:m.dispatch,clients:m.clients,quotes:m.quotes,invoices:m.invoices,team:m.crew,sms:m.messages,notifications:[...m.alerts,...m.issues],reports:m.done,integrations:m.invoices,payroll:[...m.crew,...m.doneJobs],automation:m.actionQueue,settings:m.issues};const rows=map[area]||m.actionQueue;return <main className="cc-app cc-simple" data-version="CHURVOX_COMMAND_FLOOR_V31_WORK_REVIEW_DETAILS_20260525"><div className="cc-bg"/><Sidebar/><section className="cc-main"><Top loading={loading}/><section className="cc-page-head"><p>Workspace</p><h1>{title}</h1><span>{sub}</span></section><section className="cc-page-list">{rows.slice(0,30).map((x,i)=><MiniRow key={`${area}-${i}`} x={x} onPick={onPick}/>)}</section></section></main>}
function drawerLinks(x){if(!x)return[];if(x.type==="crew_map")return[["/team","Open Live Crew"],["/dispatch","Open Dispatch"]];const id=x.id,open=x.href&&x.href!=="#"?[x.href,"Open record"]:null,edit=id&&x.href&&x.href!=="#"?[`${x.href}/edit`,"Edit record"]:null;if(x.type==="work_review")return[open,["/jobs","Review work"],["/invoices/new","Create invoice"],["/dispatch","Send back"]].filter(Boolean);if(x.type==="job")return[open,x.state==="Unassigned"?["/dispatch","Assign worker"]:null,edit,["/invoices/new","Create invoice"]].filter(Boolean);if(x.type==="invoice")return[open,["/invoices/new","Create invoice"],["/invoices","Money desk"]].filter(Boolean);if(x.type==="quote")return[open,edit,["/jobs/new","Turn into job"],["/quotes","Quote follow-up"]].filter(Boolean);if(x.type==="client")return[open,edit,["/jobs/new","Add job"],["/quotes/new","Create quote"]].filter(Boolean);if(x.type==="worker")return[["/team","Open team"],["/jobs/new","Assign job"],["/dispatch","Dispatch board"]];if(x.type==="action"||x.type==="alert")return[open,["/ai-operator/approvals","Take Action"],["/notifications","View issues"]].filter(Boolean);return[open,["/dashboard","Back to command"]].filter(Boolean)}
function Drawer({x,onClose,m}){const links=drawerLinks(x);return x?<aside className={`cc-drawer ${x.type==="crew_map"?"cc-map-drawer":""}`}><button type="button" onClick={onClose}>Close</button><p>{x.type==="crew_map"?"Owner map":(x.type==="work_review"?"Work review":(x.type==="action"||x.type==="alert"?"Prepared action":"Selected work"))}</p><h2>{x.title}</h2><span>{x.meta}</span>{x.type==="crew_map"?<CrewMapSlip x={x}/>:<><dl><div><dt>Type</dt><dd>{x.type==="work_review"?"work review":x.type}</dd></div><div><dt>Status</dt><dd>{x.state}</dd></div><div><dt>Value</dt><dd>{Number(x.amount||0)>0?cash(x.amount):"—"}</dd></div><div><dt>Owing</dt><dd>{cash(sum(m.owing))}</dd></div></dl>{x.type==="work_review"&&<WorkReviewDetails x={x}/>}<section>{links.map(([to,label])=><Link key={`${to}-${label}`} to={to}>{label}</Link>)}</section></>}</aside>:null}
export default function ConceptCPage({area="dashboard"}){const{get}=useApi(),{data,loading}=useLive(area,get),m=useMemo(()=>build(data),[data]),[picked,setPicked]=useState(null);return <>{area==="dashboard"?<Dashboard m={m} onPick={setPicked} loading={loading}/>:<SimplePage area={area} m={m} onPick={setPicked} loading={loading}/>}<Drawer x={picked} onClose={()=>setPicked(null)} m={m}/></>}