import API_BASE from '../lib/apiBase';
const ROOT=`${String(API_BASE||'').replace(/\/$/,'')}/api`;let memo={t:0,d:null};
function txt(v){return String(v||'').replace(/\s+/g,' ').trim()}
function arr(x,k){return Array.isArray(x)?x:Array.isArray(x?.[k])?x[k]:Array.isArray(x?.data)?x.data:Array.isArray(x?.items)?x.items:Array.isArray(x?.actions)?x.actions:[]}
function isTodayPage(){const p=window.location.pathname||'';const h=(window.location.hash||'').replace('#','');const title=txt(document.querySelector('.cvxTopTitle h1')?.textContent);return p.startsWith('/dashboard')&&(h==='today'||(!h&&(!title||/today/i.test(title))))}
function removeCoach(){document.querySelector('[data-churvox-setup-coach]')?.remove()}
function go(hash){removeCoach();window.location.hash=hash;window.dispatchEvent(new Event('hashchange'))}
async function get(path){try{const r=await fetch(`${ROOT}${path}`,{credentials:'include'});return await r.json().catch(()=>({}))}catch{return {}}}
async function data(){if(Date.now()-memo.t<15000&&memo.d)return memo.d;const a=await Promise.all([get('/clients'),get('/jobs'),get('/team'),get('/invoices')]);memo={t:Date.now(),d:{clients:arr(a[0],'clients'),jobs:arr(a[1],'jobs'),team:arr(a[2],'team'),invoices:arr(a[3],'invoices')}};return memo.d}
function finished(jobs){return jobs.some(j=>/complete|done|finished/i.test(txt(j.status||j.job_status||j.workflow_status)))}
function steps(d){return[{label:'Add your first client',note:'Save the person or site you work for.',done:d.clients.length>0,target:'#clients',button:'Add client'},{label:'Add your first job',note:'Turn that client into real work.',done:d.jobs.length>0,target:'#jobs',button:'Add job'},{label:'Add a team member',note:'Set up who can help with the work.',done:d.team.length>0,target:'#team',button:'Open team'},{label:'Finish one job',note:'Close the first work loop.',done:finished(d.jobs),target:'#jobs',button:'Open jobs'},{label:'Open Command',note:'See where owner decisions live.',done:false,target:'#command',button:'Open Command'},{label:'Create invoice draft',note:'Finish the first admin loop.',done:d.invoices.length>0,target:'#invoices',button:'Open invoices'}]}
function setupCoachHtml(d){const s=steps(d);const done=s.filter(x=>x.done).length;const pct=Math.max(16,Math.round(done/s.length*100));const next=s.find(x=>!x.done)||s[s.length-1];const list=s.map((x,i)=>`<div class="cvxSetupCoachStep ${x.done?'done':''}"><b>${x.done?'✓':i+1}</b><div><span>${x.label}</span><em>${x.note}</em></div></div>`).join('');return `<section class="cvxSetupCoach" data-churvox-setup-coach="true"><div class="cvxSetupCoachInner"><div><small>Setup coach · ${done}/${s.length} complete</small><h3>${next.label}</h3><p>Churvox guides the first setup in a simple order: client, job, team, Command and invoice. One next move at a time.</p><div class="cvxSetupCoachAction"><button type="button" data-setup-go="${next.target}">${next.button}</button><button type="button" class="secondary" data-setup-close="true">Dismiss</button></div><div class="cvxSetupCoachProgress" style="--setup-progress:${pct}%"><i></i></div></div><div class="cvxSetupCoachSteps">${list}</div></div></section>`}
function bind(node){node.querySelectorAll('[data-setup-go]').forEach((button)=>button.addEventListener('click',()=>go(button.getAttribute('data-setup-go')||'#today')));node.querySelector('[data-setup-close]')?.addEventListener('click',()=>node.remove())}
async function apply(){if(typeof window==='undefined')return;if(!isTodayPage()){removeCoach();return}if(document.querySelector('[data-churvox-setup-coach]'))return;const page=document.querySelector('.cvxPage');if(!page)return;const hero=page.querySelector('.cvxHero');const wrap=document.createElement('div');wrap.innerHTML=setupCoachHtml(await data());const node=wrap.firstElementChild;if(hero?.nextSibling)page.insertBefore(node,hero.nextSibling);else page.prepend(node);bind(node)}
function schedule(){[0,350,900,1800].forEach((delay)=>setTimeout(apply,delay))}
schedule();window.addEventListener('hashchange',schedule);window.addEventListener('popstate',schedule);window.addEventListener('churvox-owner-app-ready',schedule);window.addEventListener('churvox:data-refresh',()=>{memo={t:0,d:null};removeCoach();schedule()});
