const STYLE_ID = 'churvox-public-auth-style-runtime';

function inject() {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style');
  style.id = STYLE_ID;
  style.textContent = `
    .cvPublicAuth,.cvPublicAuth *{box-sizing:border-box!important}
    .cvPublicAuth{min-height:100vh!important;background:radial-gradient(circle at 12% 0%,rgba(239,85,60,.22),transparent 28rem),radial-gradient(circle at 88% 6%,rgba(16,21,19,.13),transparent 26rem),linear-gradient(180deg,#fffaf2 0%,#f6f1e7 58%,#fff7ed 100%)!important;color:#101513!important;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif!important;overflow-x:hidden!important}
    .cvPublicAuth .publicNav{position:sticky!important;top:0!important;z-index:20!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:18px!important;width:calc(100% - clamp(22px,5vw,80px))!important;margin:14px auto 0!important;padding:12px 14px!important;border:1px solid rgba(16,21,19,.09)!important;border-radius:24px!important;background:rgba(255,250,242,.92)!important;backdrop-filter:blur(18px)!important;box-shadow:0 18px 52px rgba(16,21,19,.08)!important}
    .cvPublicAuth .publicBrand{display:flex!important;align-items:center!important;gap:10px!important;color:#101513!important;text-decoration:none!important}.cvPublicAuth .publicBrand b{display:block!important;font-size:17px!important;font-weight:1000!important;color:#101513!important}.cvPublicAuth .publicBrand small{display:block!important;color:#9e3f1f!important;font-size:10px!important;font-weight:1000!important;letter-spacing:.12em!important;text-transform:uppercase!important}.cvPublicAuth .publicLinks{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;flex-wrap:wrap!important}.cvPublicAuth .publicLinks a,.cvPublicAuth .publicPrimary{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:42px!important;border-radius:999px!important;padding:0 16px!important;text-decoration:none!important;font-weight:1000!important;font-size:13px!important;color:#334155!important}.cvPublicAuth .publicPrimary{background:#ef553c!important;color:#fff!important;box-shadow:0 14px 30px rgba(239,85,60,.24)!important}
    .cvPublicAuthShell{width:calc(100% - clamp(22px,5vw,80px))!important;max-width:1320px!important;margin:0 auto!important;padding:clamp(34px,6vw,82px) 0 clamp(42px,6vw,90px)!important;display:grid!important;grid-template-columns:minmax(320px,.56fr) minmax(340px,.44fr)!important;gap:clamp(20px,4vw,54px)!important;align-items:stretch!important}
    .cvPublicAuthCard,.cvPublicAuthPanel{border:1px solid rgba(16,21,19,.09)!important;border-radius:32px!important;background:rgba(255,255,255,.86)!important;box-shadow:0 28px 80px rgba(16,21,19,.11)!important;backdrop-filter:blur(16px)!important;padding:clamp(22px,3.4vw,46px)!important;color:#101513!important}
    .cvPublicAuthCard{display:grid!important;gap:15px!important}.cvPublicAuthKicker{display:inline-flex!important;width:max-content!important;max-width:100%!important;min-height:32px!important;align-items:center!important;border-radius:999px!important;background:#101513!important;color:#ffded0!important;padding:0 12px!important;font-size:10px!important;font-weight:1000!important;letter-spacing:.14em!important;text-transform:uppercase!important;margin:0!important}.cvPublicAuthCard h1{margin:0!important;color:#101513!important;font-size:clamp(42px,6vw,82px)!important;line-height:.86!important;letter-spacing:-.08em!important;font-weight:1000!important}.cvPublicAuthIntro{margin:0!important;color:#53605b!important;font-size:16px!important;font-weight:830!important;line-height:1.45!important;max-width:720px!important}
    .cvPublicAuthCard label{display:grid!important;gap:7px!important;color:#303936!important;font-size:12px!important;font-weight:1000!important;text-transform:uppercase!important;letter-spacing:.08em!important}.cvPublicNativeInput{width:100%!important;min-height:52px!important;border-radius:16px!important;border:1px solid rgba(16,21,19,.13)!important;background:#fff!important;color:#101513!important;padding:0 15px!important;font-size:15px!important;font-weight:850!important;outline:none!important}.cvPublicNativeInput:focus{border-color:#ef553c!important;box-shadow:0 0 0 4px rgba(239,85,60,.14)!important}.password-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;gap:8px!important}.cvPublicAuthGhost{min-width:70px!important;border:1px solid rgba(16,21,19,.12)!important;border-radius:999px!important;background:#fff!important;color:#101513!important;font-weight:1000!important;cursor:pointer!important}.cvPublicAuthSubmit{min-height:54px!important;border:0!important;border-radius:999px!important;background:#ef553c!important;color:#fff!important;font-size:15px!important;font-weight:1000!important;cursor:pointer!important;box-shadow:0 16px 32px rgba(239,85,60,.25)!important}.cvPublicAuthSubmit:disabled{opacity:.65!important;cursor:wait!important}.cvPublicAuthError{border-radius:16px!important;background:#fff1f0!important;border:1px solid rgba(239,85,60,.25)!important;color:#9e3f1f!important;padding:12px 14px!important;font-weight:900!important}.cvPublicAuthBottom{margin:0!important;color:#53605b!important;font-weight:850!important}.cvPublicAuthBottom a{color:#9e3f1f!important;font-weight:1000!important;text-decoration:none!important}
    .cvPublicAuthPanel{display:grid!important;align-content:center!important;gap:16px!important;color:#fff!important;background:radial-gradient(circle at 86% 18%,rgba(239,85,60,.34),transparent 30%),linear-gradient(135deg,#101513 0%,#17201e 58%,#4b2618 100%)!important}.cvPublicAuthPanel p{display:inline-flex!important;width:max-content!important;max-width:100%!important;border-radius:999px!important;background:rgba(255,255,255,.12)!important;color:#ffd6c7!important;padding:8px 12px!important;font-size:10px!important;font-weight:1000!important;letter-spacing:.12em!important;text-transform:uppercase!important;margin:0!important}.cvPublicAuthPanel h2{margin:0!important;color:#fff!important;font-size:clamp(32px,4vw,58px)!important;line-height:.9!important;letter-spacing:-.065em!important;font-weight:1000!important}.cvPublicAuthPanel ul{margin:0!important;padding-left:20px!important;display:grid!important;gap:10px!important}.cvPublicAuthPanel li{color:#e9edf0!important;font-size:15px!important;font-weight:850!important;line-height:1.35!important}
    @media(max-width:920px){.cvPublicAuthShell{grid-template-columns:1fr!important}.cvPublicAuth .publicLinks a:not(.publicPrimary){display:none!important}}
    @media(max-width:560px){.cvPublicAuth .publicBrand small{display:none!important}.cvPublicAuthShell,.cvPublicAuth .publicNav{width:calc(100% - 24px)!important}.cvPublicAuthShell{padding-top:26px!important}.cvPublicAuthCard,.cvPublicAuthPanel{border-radius:24px!important;padding:20px!important}.cvPublicAuthCard h1{font-size:44px!important}.cvPublicAuthPanel{display:none!important}}
  `;
  document.head.appendChild(style);
}

if (typeof window !== 'undefined') {
  inject();
  window.addEventListener('DOMContentLoaded', inject);
  window.addEventListener('load', inject);
  window.addEventListener('popstate', inject);
}

export {};
