const CONTRACTS={today:['Owner control room','Run sheet','Checks','Messages','Money'],command:['Approval desk','Filled slips','Owner decision','Edit path','Park unclear'],jobs:['Job truth board','Client','Site','Worker','Time','Price','Proof'],clients:['Client memory','Contact','Site notes','Usual work','Price','Next job'],workers:['Field team','Current job','Status','Map','Proof','Problem'],messages:['Message sorter','Client','Worker','Job update','Review'],quotes:['Quote builder','Client','Scope','Price','Follow-up','Convert'],invoices:['Money desk','Completed work','Proof','Amount','Review','Draft'],team:['Team setup','Invite','Role','Access','Active'],payroll:['Pay review','Hours','Adjustments','Period','Export'],xero:['Accounting guard','Connection','Drafts','Refresh','Review'],settings:['Business setup','Logo','Details','Brand','Preferences'],plans:['Plan fit','Current plan','Capacity','Locked pricing'],help:['Support guide','First job','Worker app','Invoice','Command']};
function t(v){return String(v||'').replace(/\s+/g,' ').trim()}
function key(){const h=t((window.location.hash||'').replace('#','')).toLowerCase();if(CONTRACTS[h])return h;const title=t(document.querySelector('.cvxTopTitle h1')?.textContent||document.querySelector('h1')?.textContent).toLowerCase();for(const k of Object.keys(CONTRACTS)){if(title.includes(k))return k}if(/account/.test(title))return 'xero';return 'today'}
function remove(){document.querySelectorAll('[data-churvox-page-contract]').forEach(n=>n.remove())}
function demoClean(){document.querySelectorAll('.cvxRow').forEach(row=>{const copy=t(row.textContent).toLowerCase();if(/\bdemo\b|\bsample\b|\bplaceholder\b|lorem/.test(copy))row.classList.add('cvxHiddenDemoRow')})}
function buttonClean(k){document.querySelectorAll('button').forEach(btn=>{const label=t(btn.textContent).toLowerCase();if(k!=='command'&&(label==='approve'||label==='park'))btn.classList.add('cvxHiddenApproveOutsideCommand');if(k!=='command'&&label==='open command')btn.textContent='Owner review'})}
function html(k){const data=CONTRACTS[k]||CONTRACTS.today;return `<section class="cvxPageContract" data-churvox-page-contract="true"><b>${data[0]}</b><div>${data.slice(1).map(x=>`<span>${x}</span>`).join('')}</div></section>`}
function apply(){if(typeof window==='undefined')return;const p=window.location.pathname||'';if(!p.startsWith('/dashboard')&&p!=='/plans'&&p!=='/guide'&&p!=='/setup'&&p!=='/setup-guide')return;const page=document.querySelector('.cvxPage');if(!page)return;const k=key();demoClean();buttonClean(k);remove();const hero=page.querySelector('.cvxHero');const wrap=document.createElement('div');wrap.innerHTML=html(k);const node=wrap.firstElementChild;if(hero?.nextSibling)page.insertBefore(node,hero.nextSibling);else page.prepend(node)}
function schedule(){[0,180,420,900,1800].forEach(d=>setTimeout(apply,d))}
schedule();window.addEventListener('hashchange',schedule);window.addEventListener('popstate',schedule);window.addEventListener('churvox-owner-app-ready',schedule);window.addEventListener('churvox:data-refresh',schedule);
