/* Churvox worker smart profiles: worker facts for better Smart Assign. */
const ID="churvoxWorkerSmartProfileRoot";
const STYLE="churvoxWorkerSmartProfileStyle";
const STORE="churvox_worker_smart_profiles_v1";
const API=String(process.env.REACT_APP_BACKEND_URL||process.env.VITE_BACKEND_URL||"").replace(/\/$/,"");
const clean=(v)=>String(v??"").replace(/\s+/g," ").trim();
const keyOf=(v)=>clean(v).toLowerCase().replace(/[^a-z0-9]/g,"");
const apiUrl=(p)=>`${(API||window.location.origin).replace(/\/$/,"")}/api${String(p).startsWith("/")?p:`/${p}`}`;
function headers(extra={}){let t="";try{t=localStorage.getItem("token")||localStorage.getItem("authToken")||""}catch{}return{Accept:"application/json","Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{ }),...extra}}
async function json(path,opts={}){const r=await fetch(apiUrl(path),{credentials:"include",...opts,headers:headers(opts.headers||{})});const d=await r.json().catch(()=>({}));if(!r.ok||d?.success===false)throw new Error(d?.detail||d?.error||d?.message||`Request failed: ${r.status}`);return d}
function rows(payload,key="team"){const d=payload?.data?.data??payload?.data??payload;if(Array.isArray(d))return d;if(Array.isArray(d?.[key]))return d[key];for(const n of["team","workers","users","items","records","results","data"])if(Array.isArray(d?.[n]))return d[n];return[]}
function idOf(r){const raw=r?.id||r?._id||r?.user_id||r?.worker_id||r?.team_member_id||r?.email||"";return typeof raw==="object"?clean(raw.$oid||raw.oid||raw.id||raw._id):clean(raw)}
function pick(r,...ks){for(const k of ks){const v=r?.[k];if(v!==undefined&&v!==null&&clean(v))return v}return""}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||"{}")||{}}catch{return{}}}
function saveAll(p){try{localStorage.setItem(STORE,JSON.stringify(p||{}))}catch{}}
function mergeWorker(w){const p=load();const id=idOf(w);return{...w,...(p[id]||p[keyOf(w?.email)]||{})}}
function mergePayload(payload){const d=payload?.data?.data??payload?.data??payload;if(Array.isArray(d))return{...payload,data:d.map(mergeWorker)};for(const k of["team","workers","users","items","records","results","data"]){if(Array.isArray(d?.[k])){const nd={...d,[k]:d[k].map(mergeWorker)};if(payload?.data?.data)return{...payload,data:{...payload.data,data:nd}};if(payload?.data)return{...payload,data:nd};return nd}}return payload}
function installFetchMerge(){if(window.__CHURVOX_WORKER_SMART_PROFILE_FETCH__)return;window.__CHURVOX_WORKER_SMART_PROFILE_FETCH__=true;const native=window.fetch.bind(window);window.fetch=async(input,init={})=>{const res=await native(input,init);try{const url=typeof input==="string"?input:input?.url||"";const method=String(init?.method||"GET").toUpperCase();if(method==="GET"&&/\/api\/team(\?|$|\/)/.test(url)){const data=await res.clone().json();return new Response(JSON.stringify(mergePayload(data)),{status:res.status,statusText:res.statusText,headers:res.headers})}}catch{}return res}}
function page(){const path=keyOf((window.location.pathname||"").split("/")[1]||"dashboard");const hash=keyOf((window.location.hash||"").replace(/^#/,"").split("?")[0]);return hash||({dashboard:"today",smarthub:"today",setupguide:"support",accounting:"xero"}[path])||path||"today"}
function show(){return page()==="workers"}
function style(){if(document.getElementById(STYLE))return;const s=document.createElement("style");s.id=STYLE;s.textContent=`#${ID}{grid-column:1/-1}.cvWorkerProfilePanel{display:grid;gap:14px;border:1px solid rgba(16,21,19,.11);border-radius:28px;background:#fffaf2;padding:16px;box-shadow:0 18px 48px rgba(16,21,19,.08)}.cvWorkerProfilePanel header{display:flex;justify-content:space-between;gap:14px;border:0;padding:0;margin:0}.cvWorkerProfilePanel h3{margin:0;font-size:22px;letter-spacing:-.05em}.cvWorkerProfilePanel p{margin:4px 0 0;color:#59635c;font-size:13px;font-weight:750;line-height:1.45}.cvWorkerProfilePanel button{border:0;border-radius:999px;background:#101513;color:white;padding:9px 12px;font-size:12px;font-weight:1000;cursor:pointer}.cvWorkerProfilePanel button.orange{background:linear-gradient(135deg,#f36b21,#ff9b45);color:#211006}.cvWorkerProfileList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.cvWorkerSmartCard{display:grid;gap:10px;border:1px solid rgba(16,21,19,.09);border-radius:22px;background:white;padding:12px}.cvWorkerSmartGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cvWorkerSmartGrid label{display:grid;gap:5px;font-size:11px;font-weight:1000;color:#59635c;text-transform:uppercase;letter-spacing:.04em}.cvWorkerSmartGrid input,.cvWorkerSmartGrid textarea{width:100%;border:1px solid rgba(16,21,19,.12);border-radius:14px;background:#faf7ef;padding:9px 10px;color:#101513;font:inherit;font-size:13px;font-weight:750;outline:0}.cvWorkerSmartGrid textarea{resize:vertical;min-height:64px}.cvWorkerSmartGrid .wide{grid-column:1/-1}.cvWorkerSmartMeta{display:flex;gap:8px;flex-wrap:wrap}.cvWorkerSmartMeta span{border-radius:999px;background:#f4efe6;color:#4d5851;padding:6px 8px;font-size:11px;font-weight:900}.cvWorkerProfileNotice{border-radius:16px;background:#e9f8ef;color:#15522d;padding:10px;font-size:12px;font-weight:900}.cvWorkerProfileNotice.bad{background:#fff0ef;color:#8b1e13}@media(max-width:900px){.cvWorkerProfileList{grid-template-columns:1fr}.cvWorkerSmartGrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function root(){let r=document.getElementById(ID);if(!r){r=document.createElement("section");r.id=ID}const p=document.querySelector(".cvxPage");const anchor=[...document.querySelectorAll(".cvxPanel")].find(x=>clean(x.querySelector("h3")?.textContent)==="GPS map")||p?.querySelector(".cvxHero")?.nextElementSibling;if(p&&r.parentElement!==p)p.insertBefore(r,anchor||p.firstChild?.nextSibling||p.firstChild||null);return r}
let state={loading:true,workers:[],notice:null,expanded:false};
function esc(v){const d=document.createElement("div");d.textContent=clean(v);return d.innerHTML}
function profile(w){const m=mergeWorker(w);return{skills:pick(m,"skills","skill_tags","trade","service_skills","service"),service_areas:pick(m,"service_areas","service_area","areas","area","region","gps","location"),equipment:pick(m,"equipment","tools","gear","vehicle"),normal_availability:pick(m,"normal_availability","availability","work_days","usual_hours"),max_jobs_per_day:pick(m,"max_jobs_per_day","max_jobs","daily_capacity")}}
function field(label,name,value,ph,type="text",wide=false){return`<label class="${wide?"wide":""}"><span>${esc(label)}</span>${type==="textarea"?`<textarea name="${esc(name)}" rows="3" placeholder="${esc(ph)}">${esc(value)}</textarea>`:`<input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" placeholder="${esc(ph)}" />`}</label>`}
function card(w,i){const id=idOf(w);const p=profile(w);const name=pick(w,"name","full_name","display_name","email")||`Worker ${i+1}`;return`<article class="cvWorkerSmartCard" data-worker-profile-id="${esc(id)}"><strong>${esc(name)}</strong><div class="cvWorkerSmartMeta"><span>${esc(pick(w,"role")||"Worker")}</span><span>${esc(pick(w,"status","clock_status")||"Status not set")}</span></div><div class="cvWorkerSmartGrid">${field("Skills","skills",p.skills,"Lawn mowing, hedges, spraying")}${field("Service areas","service_areas",p.service_areas,"Naenae, Lower Hutt")}${field("Equipment","equipment",p.equipment,"Trailer, hedge trimmer, mower")}${field("Availability","normal_availability",p.normal_availability,"Mon-Fri 8-4")}${field("Max jobs/day","max_jobs_per_day",p.max_jobs_per_day||"4","4","number")}${field("Notes","smart_profile_notes",pick(mergeWorker(w),"smart_profile_notes","notes"),"Anything Churvox should remember","textarea",true)}</div><button type="button" class="orange" data-worker-profile-save>Save worker profile</button></article>`}
function render(){style();const r=root();if(!show()){r.innerHTML="";return}const list=state.expanded?state.workers:state.workers.slice(0,3);r.innerHTML=`<section class="cvWorkerProfilePanel"><header><div><h3>Smart worker profiles</h3><p>Give Churvox the facts it needs for better worker fit: skills, areas, equipment, availability and daily capacity.</p></div><div class="cvWorkerSmartMeta"><span>${state.workers.length} workers</span><span>Used by Smart Assign</span><span>Owner still approves</span></div></header>${state.notice?`<div class="cvWorkerProfileNotice ${state.notice.bad?"bad":""}">${state.notice.text}</div>`:""}${state.loading?`<div class="cvWorkerProfileNotice">Loading worker profiles…</div>`:""}<div class="cvWorkerProfileList">${list.map(card).join("")||`<div class="cvWorkerProfileNotice bad">No workers found yet. Add workers first, then fill their smart profile.</div>`}</div>${state.workers.length>3?`<button type="button" data-worker-profile-toggle>${state.expanded?"Show less":`Show all ${state.workers.length}`}</button>`:""}</section>`;r.querySelector("[data-worker-profile-toggle]")?.addEventListener("click",()=>{state.expanded=!state.expanded;render()});r.querySelectorAll("[data-worker-profile-save]").forEach(b=>b.addEventListener("click",()=>saveProfile(b.closest("[data-worker-profile-id]"))))}
async function saveProfile(c){const id=c?.getAttribute("data-worker-profile-id")||"";if(!id)return;const values={};c.querySelectorAll("input,textarea").forEach(f=>values[f.name]=clean(f.value));const p=load();p[id]={...(p[id]||{}),...values,updated_at:new Date().toISOString()};saveAll(p);state.workers=state.workers.map(w=>idOf(w)===id?mergeWorker(w):w);state.notice={text:"Worker profile saved. Smart Actions will use it on the next refresh."};render();try{await patchWorker(id,values);window.dispatchEvent(new Event("churvox:data-refresh"))}catch(e){state.notice={text:`Saved on this device. Backend did not accept the profile yet: ${e?.message||"try again later"}`,bad:true};render()}}
async function patchWorker(id,values){const payload={...values,smart_profile_enabled:true};let last=null;for(const call of[()=>json(`/team/workers/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(payload)}),()=>json(`/team/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(payload)}),()=>json(`/workers/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(payload)})]){try{return await call()}catch(e){last=e}}throw last||new Error("Could not save worker profile")}
async function refresh(){if(!show()){render();return}state.loading=true;render();try{state.workers=rows(await json("/team"),"team").map(mergeWorker);state.loading=false;render()}catch(e){state.loading=false;state.notice={text:e?.message||"Could not load worker profiles.",bad:true};render()}}
function start(){if(window.__CHURVOX_WORKER_SMART_PROFILE_RUNTIME__)return;window.__CHURVOX_WORKER_SMART_PROFILE_RUNTIME__=true;installFetchMerge();setTimeout(refresh,900);window.addEventListener("hashchange",()=>setTimeout(refresh,120));window.addEventListener("popstate",()=>setTimeout(refresh,120));window.addEventListener("churvox:data-refresh",()=>setTimeout(refresh,350))}
if(typeof window!=="undefined")start();
