import React from "react";
import { Link } from "react-router-dom";
import { PublicNav,PublicFooter,serviceTypes } from "./ChurvoxPublicShell";
import "./ChurvoxPremiumScenes.css";

const ROOMS=[["01","Today","The morning handover","What changed, what is blocked and the one move worth making first."],["02","Jobs","The work record","Schedule, recurrence, scope, notes, proof and price remain one business story."],["03","Clients","The memory room","Preferences, access notes, promises and history stay with the relationship."],["04","Workers","The field link","Simple updates return to the office without making workers run the owner system."],["05","Money","The value room","Quotes, completed work, extras and invoice drafts stay connected."],["06","Command","The owner desk","Approve, edit, park or ask with the evidence and consequences visible."]];
function ProductBuilding(){return <aside className="cpProductCutaway" aria-label="Churvox connected office cutaway"><div className="cpProductBrain"><small>Churvox</small><b>Office brain</b><span>checks the connected business</span></div><div className="cpProductRoom r1"><small>Bookings room</small><b>Requests prepared</b><p>Timing, recurrence and client intent.</p></div><div className="cpProductRoom r2"><small>Field room</small><b>Workers moving</b><p>Status, proof and problems.</p></div><div className="cpProductRoom r3"><small>Money room</small><b>Value protected</b><p>Quotes, invoices and extras.</p></div><div className="cpProductRoom r4"><small>Owner room</small><b>Real decisions only</b><p>Approve, edit, park or ask.</p></div><i className="cpProductSignal s1"/><i className="cpProductSignal s2"/><i className="cpProductSignal s3"/><i className="cpProductSignal s4"/></aside>}
export default function ExecutiveFeaturesPage(){return <main className="cp26Site cpWorld cvPremiumPage" data-room="product" data-version="CHURVOX_PREMIUM_SCENES_PRODUCT_20260724"><PublicNav active="/product"/>
  <section className="cvSceneHero"><div className="cvSceneHeroCopy"><span className="cvSceneKicker">Product · connected office</span><h1>Six rooms. <em>One business story.</em></h1><p>Churvox is not a dashboard with the same cards repeated everywhere. Each room has one operating responsibility, while the office brain keeps the records connected as work changes.</p><div className="cvSceneActions"><Link className="cp26Button" to="/demo">Run a workday</Link><Link className="cp26Button cp26ButtonGhost" to="/signup?plan=operator">Start free trial</Link></div><div className="cvSceneFacts"><span>Connected records</span><span>Field handover</span><span>Owner approval</span></div></div><ProductBuilding/></section>

  <section className="cvProductSpine"><div className="cvProductSticky"><div className="cvSceneIntro"><small>The operating spine</small><h2>Different rooms. No broken handovers.</h2><p>The visual language changes around the job each room performs, but the client, job, worker, promise and money records stay connected.</p></div></div><div className="cvRoomSpine">{ROOMS.map(([n,title,sub,text])=><article className="cvRoomEntry" data-room={n} key={n}><small>{sub}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="cvCommandStage"><div className="cvSceneIntro"><small>Command · the owner desk</small><h2>The system prepares. The owner decides.</h2><p>Every decision slip explains what changed, which records were checked, what is still missing and what happens next.</p><strong>Nothing important disappears into automation.</strong><ul><li>Messages remain editable.</li><li>Money actions stay deliberate.</li><li>Accounting handoff stays owner-controlled.</li><li>Every approval leaves a trail.</li></ul></div><div className="cvCommandConsole"><header><span>Prepared decision / extra work</span><b>4 records checked</b></header><div className="cvCommandBody"><div className="cvCommandQueue"><button className="active" type="button"><small>Quality</small><b>Extra work found</b></button><button type="button"><small>Client</small><b>Promise due</b></button><button type="button"><small>Money</small><b>Invoice check</b></button></div><div className="cvDecisionPane"><small>Prepared owner move</small><h3>Add the variation. Hold the invoice.</h3><p>The completed extra section is visible in worker time, notes and photos but is not yet represented in the quote or invoice.</p><div className="cvDecisionFacts"><div><span>Value at risk</span><b>$680</b></div><div><span>Next safe move</span><b>Variation</b></div></div><div className="cvDecisionActions"><span>Approve</span><span>Edit amount</span><span>Park</span><span>Ask</span></div></div></div></div></section>

  <section className="cvFieldStage"><div className="cvFieldDevice"><div className="cvFieldScreen"><header><span>9:41</span><b>Churvox Field</b><span>●</span></header><div className="cvFieldJob"><small>Assigned · ready</small><h3>Riverside tidy</h3><p>Client access, scope and latest office direction are attached.</p></div><div className="cvFieldSteps"><span>Acknowledge</span><span>Start work</span><span>Add proof</span><span>Complete</span></div></div></div><div className="cvFieldCopy"><div className="cvSceneIntro"><small>The worker experience</small><h2>The field app stays focused because the office does the joining.</h2><p>Workers receive the work, update what happened and return proof. Churvox connects that handover to the rest of the business.</p></div><div className="cvHandoffLine"><h3>One update can affect the whole office.</h3><p>A completion note can prepare an invoice, surface an extra, update a client promise and create an owner decision—without four people retyping it.</p></div></div></section>

  <section className="cvIndustryFrequency"><div className="cvSceneIntro"><small>Business frequency</small><h2>Same operating brain. The business’s own language.</h2><p>Jobs, visits, appointments, cleaners, stylists and technicians can use wording that fits the work.</p></div><div className="cvFrequencyTrack">{serviceTypes.map((type,index)=><Link key={type} to={`/demo?industry=${encodeURIComponent(type.toLowerCase().replace(/[^a-z0-9]+/g,"-"))}`}><small>Route {String(index+1).padStart(2,"0")}</small><b>{type}</b><span>Open workday →</span></Link>)}</div></section>

  <section className="cvSceneClose"><div><small>Next · workday simulator</small><h2>Watch the connected office respond to one job.</h2><p>The demo uses clearly labelled sample information. Nothing is sent or added to an account.</p></div><div><Link className="cp26Button" to="/demo">Run the simulator</Link><Link className="cp26Button cp26ButtonGhost" to="/pricing">Open pricing</Link></div></section><PublicFooter/></main>}
