import React from "react";
import { Link } from "react-router-dom";
import { PublicNav, PublicFooter } from "./ChurvoxPublicShell";
const channels=[["01","Product and trial help","Tell us what business you run, what admin is slowing you down and what you want to test.","mailto:hello@churvox.com?subject=Churvox%20trial%20help","Email trial support"],["02","Tester access","Include the invited email and where setup stopped.","mailto:hello@churvox.com?subject=Churvox%20tester%20access","Email tester support"],["03","Technical issue","Send the route, what you clicked, what happened and a screenshot when useful.","mailto:hello@churvox.com?subject=Churvox%20technical%20issue","Report an issue"]];
const routes=[["Product demo","/demo","See the connected office without signing in."],["Pricing","/pricing","Open the capacity switchboard."],["Start trial","/signup?plan=operator","Create an owner account with no card upfront."],["Log in","/login","Open the Churvox access gate."]];
export default function ExecutiveContactPage(){return <main className="cp26Site cpWorld cpWorldContact" data-room="contact" data-version="CHURVOX_PUBLIC_WORLD_CONTACT_20260724"><PublicNav active="/contact"/><section className="cpWorldHero"><div className="cpWorldLead"><span className="cpWorldRouteCode">Room 06 · Radio room</span><h1>Send the signal with the detail that <em>actually helps.</em></h1><p>Setup question, tester access, product fit or a technical problem—tell us the business, the page and what you expected. Email only. No forced sales call.</p><div className="cpWorldActions"><a className="cp26Button" href="mailto:hello@churvox.com">Email hello@churvox.com</a><Link className="cp26Button cp26ButtonGhost" to="/demo">Open the workday</Link></div><div className="cpWorldFacts"><span>Email support</span><span>Business context first</span><span>Never send passwords or full card details</span></div></div><aside className="cpRadioRoom"><header><span>Radio room listening</span><b>hello@churvox.com</b></header><div className="cpRadioWave">{Array.from({length:7}).map((_,i)=><i key={i}/>)}</div><div className="cpRadioInbox"><article><i/><b>Trial fit question</b><span>Ready for context</span></article><article><i/><b>Tester access check</b><span>Invited email needed</span></article><article><i/><b>Visual or technical fault</b><span>Route + screenshot</span></article></div></aside></section>
  <section className="cpWorldSection"><header className="cpWorldSectionHead"><span>Choose a channel</span><h2>One clean first message beats five follow-ups.</h2></header><div className="cpContactChannels">{channels.map(([n,title,text,href,label])=><article className="cpContactChannel" key={title}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div><a href={href}>{label}</a></article>)}</div></section>
  <section className="cpWorldSection cpRecordRiver"><header className="cpWorldSectionHead"><span>Building directory</span><h2>Go straight to the room you need.</h2></header><div className="cpQuickDirectory">{routes.map(([title,to,text],index)=><Link to={to} key={title}><em>Room 0{index+1}</em><b>{title}</b><span>{text}</span></Link>)}</div></section>
  <section className="cpWorldClosing"><div><span>Still not sure?</span><h2>Run the workday first.</h2><p>The demo usually answers the product question. Email the part that still does not make sense.</p></div><div><Link className="cp26Button" to="/demo">Open demo</Link><a className="cp26Button cp26ButtonGhost" href="mailto:hello@churvox.com">Email Churvox</a></div></section><PublicFooter/></main>}
