import React from "react";
import { Link } from "react-router-dom";
import { ChurvoxLogo } from "../../components/ChurvoxLogo";
import "./ExecutivePublicSite.css";

function Nav(){return <header className="ex-nav"><Link to="/" className="ex-brand"><ChurvoxLogo variant="mark" size="sm" tone="light"/><span>Churvox</span></Link><nav className="ex-nav-links"><Link to="/">Home</Link><Link to="/features">Features</Link><Link to="/pricing">Pricing</Link></nav><div className="ex-nav-actions"><Link to="/login" className="ex-login">Log in</Link><Link to="/signup" className="ex-btn ex-btn--primary">Start free</Link></div></header>}
function Footer(){return <footer className="ex-footer"><div><Link to="/" className="ex-brand ex-brand--footer"><ChurvoxLogo variant="mark" size="sm" tone="light"/><span>Churvox</span></Link><p>AI command software for trade and service owners.</p></div><div className="ex-footer-links"><Link to="/features">Features</Link><Link to="/pricing">Pricing</Link><Link to="/login">Log in</Link><Link to="/signup">Start free</Link></div></footer>}

export { Nav, Footer };

const actions=["Send payment reminder","Assign worker to job","Approve draft invoice","Follow up accepted quote"];
const liveCrew=["Crew lead · On site","Field worker · GPS verified","Apprentice · Started 8:12","Service tech · On job"];
const stats=[["Needs Action","12","8 overdue"],["Live Crew","9","On job now"],["Ready To Bill","$4.8k","5 invoices"],["Owing","$23.6k","14 invoices"]];

export default function ExecutiveHomePage(){return <main className="ex-site" data-version="CHURVOX_DARK_LANDING_COMMAND_CENTER_20260524"><Nav/><section className="ex-hero"><div className="ex-hero-copy"><p className="ex-kicker">AI Command Center for trade businesses</p><h1>Run jobs, crew and money from one command floor.</h1><p className="ex-lead">Churvox turns daily trade admin into a clear operating screen. AI prepares the next actions, live crew stays visible, invoices surface when money is waiting, and the owner approves what matters.</p><div className="ex-actions"><Link to="/signup" className="ex-btn ex-btn--primary">Start free</Link><Link to="/features" className="ex-btn ex-btn--quiet">See how it works</Link></div><div className="ex-notes"><span>AI prepares admin</span><span>Owner approves</span><span>Live crew view</span><span>Money desk</span></div></div><aside className="ex-product-shot"><div className="ex-window-top"><b>Churvox</b><span>Command Floor</span></div><div className="ex-kpi-row">{stats.map(([label,value,note])=><article key={label}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</div><div className="ex-dashboard-grid"><section className="ex-shot-panel ex-shot-actions"><header><span>Smart priorities</span><b>AI Action Queue</b></header>{actions.map((item,i)=><div key={item} className={`ex-shot-row tone-${i}`}><i/><p>{item}</p><em>{i===2?"Approve":"Review"}</em></div>)}</section><section className="ex-shot-panel ex-shot-live"><header><span>Field live</span><b>Live Crew</b></header><div className="ex-map"><i/><i/><i/><i/></div>{liveCrew.slice(0,3).map((item)=><div key={item} className="ex-live-row"><span/><p>{item}</p><em>GPS</em></div>)}</section><section className="ex-shot-panel ex-shot-money"><header><span>Cashflow</span><b>Money Desk</b></header><strong>$28,510</strong><p>Ready to bill and owing now</p><div className="ex-money-line"/></section></div></aside></section><section className="ex-proof"><article><span>01</span><h2>AI finds the work.</h2><p>Unassigned jobs, missing details, quote follow-ups, draft invoices and overdue reminders appear in one owner queue.</p></article><article><span>02</span><h2>Crew stays visible.</h2><p>See who is on a job, what they are working on, and what needs attention without hunting through pages.</p></article><article><span>03</span><h2>Money gets surfaced.</h2><p>Completed work, invoices owing and payment reminders stay close to the owner’s next decision.</p></article></section><section className="ex-command-story"><p className="ex-kicker">Why Churvox feels different</p><h2>It is not another dashboard. It is the daily operating floor.</h2><p>Most job apps make owners click through screens to find work. Churvox brings the business position forward first: actions, live crew, cashflow, issues, quotes and clients. Then the owner opens details only when needed.</p><Link to="/pricing" className="ex-btn ex-btn--primary">View pricing</Link></section><Footer/></main>}
