import React from "react";
import { Link } from "react-router-dom";
import { PublicNav, PublicFooter, serviceTypes } from "./ChurvoxPublicShell";
import PublicFeaturesPage from "./PublicFeaturesPage";
import "./ChurvoxPremiumScenes.css";

const ROOMS = [["01", "Today", "Daily overview", "See today's jobs, anything blocked and what needs attention first."], ["02", "Jobs", "Work management", "Keep schedule, recurring work, scope, notes, proof and price together."], ["03", "Clients", "Client history", "Keep contact details, access notes, preferences and past work in one place."], ["04", "Workers", "Field updates", "Workers receive jobs and return status, notes, photos and time."], ["05", "Money", "Quotes and invoices", "Keep quotes, completed work, extras and invoice drafts connected."], ["06", "Command", "Owner approval", "Approve, edit, park or ask with the evidence and next effect visible."]];

function ProductBuilding() { return <aside className="cpProductCutaway" aria-label="Churvox product overview"><div className="cpProductBrain"><small>Churvox</small><b>Admin centre</b><span>checks the connected business</span></div><div className="cpProductRoom r1"><small>Bookings</small><b>Requests ready</b><p>Timing, recurrence and client needs.</p></div><div className="cpProductRoom r2"><small>Workers</small><b>Jobs moving</b><p>Status, proof and problems.</p></div><div className="cpProductRoom r3"><small>Money</small><b>Value protected</b><p>Quotes, invoices and extras.</p></div><div className="cpProductRoom r4"><small>Owner approval</small><b>Real decisions only</b><p>Approve, edit, park or ask.</p></div><i className="cpProductSignal s1" /><i className="cpProductSignal s2" /><i className="cpProductSignal s3" /><i className="cpProductSignal s4" /></aside>; }

export default function ExecutiveFeaturesPage() {
  const path = typeof window === "undefined" ? "/product" : window.location.pathname.replace(/\/+$/, "") || "/";
  if (path === "/features") return <PublicFeaturesPage />;

  return <main className="cp26Site cpWorld cvPremiumPage" data-room="product" data-version="CHURVOX_PLAIN_PRODUCT_20260726"><PublicNav active="/product" />
    <section className="cvSceneHero"><div className="cvSceneHeroCopy"><span className="cvSceneKicker">Product</span><h1>Every part of the job. <em>Connected.</em></h1><p>Churvox brings jobs, clients, workers, messages, quotes and invoices into one operating system without repeating the same generic dashboard everywhere.</p><div className="cvSceneActions"><Link className="cp26Button" to="/demo">View demo</Link><Link className="cp26Button cp26ButtonGhost" to="/signup?plan=operator">Start free trial</Link></div><div className="cvSceneFacts"><span>Connected records</span><span>Worker handover</span><span>Owner approval</span></div></div><ProductBuilding /></section>

    <section className="cvProductSpine"><div className="cvProductSticky"><div className="cvSceneIntro"><small>Main areas</small><h2>Different jobs. One connected system.</h2><p>Each area is built for a clear purpose, while the client, job, worker and money records stay connected.</p></div></div><div className="cvRoomSpine">{ROOMS.map(([n, title, sub, text]) => <article className="cvRoomEntry" data-room={n} key={n}><small>{sub}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="cvCommandStage"><div className="cvSceneIntro"><small>Command · owner approval</small><h2>Churvox prepares. The owner decides.</h2><p>Every decision explains what changed, what records were checked, what is still missing and what happens next.</p><strong>Nothing important disappears into automation.</strong><ul><li>Messages remain editable.</li><li>Money actions stay deliberate.</li><li>Accounting sync stays owner-controlled.</li><li>Every approval leaves a history.</li></ul></div><div className="cvCommandConsole"><header><span>Decision waiting / extra work</span><b>4 records checked</b></header><div className="cvCommandBody"><div className="cvCommandQueue" aria-label="Example Command decision queue"><button className="active" type="button" disabled title="Example decision"><small>Quality</small><b>Extra work found</b></button><button type="button" disabled title="Example decision"><small>Client</small><b>Follow-up due</b></button><button type="button" disabled title="Example decision"><small>Money</small><b>Invoice check</b></button></div><div className="cvDecisionPane"><small>Recommended next step</small><h3>Add the extra work. Hold the invoice.</h3><p>The extra work appears in worker time, notes and photos but is not yet included in the quote or invoice.</p><div className="cvDecisionFacts"><div><span>Value at risk</span><b>$680</b></div><div><span>Next safe step</span><b>Variation</b></div></div><div className="cvDecisionActions"><span>Approve</span><span>Edit amount</span><span>Park</span><span>Ask</span></div></div></div></div></section>

    <section className="cvFieldStage"><div className="cvFieldDevice"><div className="cvFieldScreen"><header><span>9:41</span><b>Churvox Worker</b><span>●</span></header><div className="cvFieldJob"><small>Assigned · ready</small><h3>Riverside tidy</h3><p>Client access, scope and latest owner direction are attached.</p></div><div className="cvFieldSteps"><span>Acknowledge</span><span>Start work</span><span>Add proof</span><span>Complete</span></div></div></div><div className="cvFieldCopy"><div className="cvSceneIntro"><small>Worker app</small><h2>Workers see only what they need.</h2><p>Workers receive the job, update what happened and return proof. Churvox connects that handover to the rest of the business.</p></div><div className="cvHandoffLine"><h3>One update can move the whole job forward.</h3><p>A completion note can prepare an invoice, surface extra work, update a client promise and create an owner decision without retyping.</p></div></div></section>

    <section className="cvIndustryFrequency"><div className="cvSceneIntro"><small>Built for service businesses</small><h2>Use wording that fits your work.</h2><p>Jobs, visits, appointments, cleaners, stylists and technicians can use language that matches the business.</p></div><div className="cvFrequencyTrack">{serviceTypes.map((type, index) => <Link key={type} to={`/demo?industry=${encodeURIComponent(type.toLowerCase().replace(/[^a-z0-9]+/g, "-"))}`}><small>Example {String(index + 1).padStart(2, "0")}</small><b>{type}</b><span>View demo →</span></Link>)}</div></section>

    <section className="cvSceneClose"><div><small>Next · product demo</small><h2>See how one job moves through Churvox.</h2><p>The demo uses clearly labelled sample information. Nothing is sent or added to an account.</p></div><div><Link className="cp26Button" to="/demo">View demo</Link><Link className="cp26Button cp26ButtonGhost" to="/pricing">View pricing</Link></div></section><PublicFooter /></main>;
}
