import React from "react";
import { Link } from "react-router-dom";
import { PublicNav, PublicFooter } from "./ChurvoxPublicShell";
import "./ChurvoxLivingOfficeHome.css";
import "./ChurvoxPremiumPublic.css";
import "./ChurvoxPremiumScenes.css";

const DESKS=[["Bookings","Requests, timing and recurring work","3 prepared"],["Field","Workers, progress and proof","6 active"],["Clients","Promises and follow-ups","2 watched"],["Money","Quotes, invoices and missed revenue","$4.2k ready"],["Quality","Photos, extras and exceptions","1 check"]];
const SIGNALS=[["01","Event","A request, update, problem or payment enters the business."],["02","Connect","The right client, job, worker, promise and money records are joined."],["03","Check","Churvox compares the ripple before preparing anything."],["04","Prepare","One editable move is assembled with the reasons attached."],["05","Approve","The owner decides what actually happens."]];
const CONTROLS=[["01","Nothing sends","Client and worker communication stays editable until the owner approves it."],["02","Nothing moves money","No charge, payout or accounting action happens silently."],["03","Nothing hides the reason","Every suggestion keeps the records and consequences visible."]];

function OfficeVisual(){return <div className="clhOffice" aria-label="Churvox connected office"><div className="clhOfficeTop"><span><i/>Live office</span><b>Everything connected</b></div><div className="clhFloor"><div className="clhBrain"><span/><small>Churvox</small><b>Office brain</b><p>Checks the whole business</p></div>{DESKS.map(([name,note,state],index)=><article key={name} className={`clhDesk desk-${index+1}`}><i/><small>{name} desk</small><b>{state}</b><p>{note}</p></article>)}<article className="clhOwnerDesk"><small>Owner desk</small><b>3 decisions</b><p>Approve · Edit · Park</p><span>Nothing sends without you</span></article><div className="clhPath path-a"/><div className="clhPath path-b"/><div className="clhPath path-c"/></div><div className="clhOfficeBottom"><span>Churvox prepared the work.</span><b>You make the decision.</b></div></div>}

export const Nav=PublicNav; export const Footer=PublicFooter;
export default function ExecutiveHomePage(){return <main className="clhSite cvPremiumPage" data-version="CHURVOX_PREMIUM_SCENES_HOME_20260724"><PublicNav/>
  <section className="cvSceneHero"><div className="cvSceneHeroCopy"><span className="cvSceneKicker">The office working behind the owner</span><h1>Your business moves. <em>Churvox sees the whole move.</em></h1><p>Jobs, workers, client promises, messages and money stop living in separate boxes. Churvox connects the story, checks the ripple and prepares the one decision that needs you.</p><div className="cvSceneActions"><Link className="cp26Button" to="/signup?plan=operator">Start 14-day trial</Link><Link className="cp26Button cp26ButtonGhost" to="/demo">Run a workday</Link></div><div className="cvSceneFacts"><span>No card upfront</span><span>Owner approval</span><span>No silent sends</span></div></div><OfficeVisual/></section>

  <section className="cvSignalStage"><div className="cvSceneIntro"><small>One connected signal</small><h2>One event travels through the office—without becoming five separate alerts.</h2><p>The business story stays connected from the moment something changes to the moment the owner approves the response.</p></div><div className="cvSignalRail">{SIGNALS.map(([n,title,text])=><article className="cvSignalNode" key={n}><div className="cvSignalDot">{n}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="cvCommandStage"><div className="cvSceneIntro"><small>Command · owner desk</small><h2>Stop managing software. Make the decision.</h2><p>Churvox does the connecting, checking and preparing first. Command shows the owner what changed, why it matters and the safest next move.</p><strong>Every decision keeps four honest options.</strong><ul><li>Approve the prepared move.</li><li>Edit any detail before it changes.</li><li>Park it without losing the trail.</li><li>Ask for the missing fact instead of guessing.</li></ul></div><div className="cvCommandConsole"><header><span>Command / live decision</span><b>Owner control on</b></header><div className="cvCommandBody"><div className="cvCommandQueue"><button className="active" type="button"><small>Money</small><b>Riverside variation</b></button><button type="button"><small>Schedule</small><b>Worker absence</b></button><button type="button"><small>Client</small><b>Friday booking</b></button></div><div className="cvDecisionPane"><small>Best move right now</small><h3>Protect $680 before invoicing.</h3><p>Worker notes and photos show completed extra work. Churvox checked the quote, time, proof and client messages before preparing the variation.</p><div className="cvDecisionFacts"><div><span>Money protected</span><b>$680</b></div><div><span>Records checked</span><b>4</b></div></div><div className="cvDecisionActions"><span>Approve variation</span><span>Edit</span><span>Park</span><span>Ask worker</span></div></div></div></div></section>

  <section className="cvFieldStage"><div className="cvFieldDevice"><div className="cvFieldScreen"><header><span>9:41</span><b>Churvox Field</b><span>●</span></header><div className="cvFieldJob"><small>Today · next job</small><h3>Riverside tidy</h3><p>Scope, access note and latest owner direction are already attached.</p></div><div className="cvFieldSteps"><span>Acknowledge job</span><span>Start work</span><span>Add note or photo</span><span>Complete and return proof</span></div></div></div><div className="cvFieldCopy"><div className="cvSceneIntro"><small>Field to office</small><h2>Small in the worker’s hand. Complete in the owner’s office.</h2><p>The worker sees the job and returns what happened. Churvox connects that update to clients, timing, proof and money without making the worker operate the whole system.</p></div><div className="cvHandoffLine"><h3>A clean handover—not another admin job.</h3><p>Status, notes, photos and time return to the right record. The owner only sees what needs a decision.</p></div></div></section>

  <section className="cvControlStage"><div className="cvSceneIntro"><small>Control is the product</small><h2>Prepared does not mean automatic.</h2><p>The office can be fast without taking control away from the person who owns the promises, money and reputation.</p></div><div className="cvControlLines">{CONTROLS.map(([n,title,text])=><article className="cvControlLine" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="cvSceneClose"><div><small>14-day trial · no card upfront</small><h2>Put a connected office behind the business.</h2><p>Use one real job, one worker update and one owner decision to see whether Churvox removes work.</p></div><div><Link className="cp26Button" to="/signup?plan=operator">Start free trial</Link><Link className="cp26Button cp26ButtonGhost" to="/pricing">View pricing</Link></div></section><PublicFooter/></main>}
