import React from "react";
import { Link } from "react-router-dom";
import { PublicNav, PublicFooter } from "./ChurvoxPublicShell";

const EMAIL = "hello@churvox.com";
const pageInfo = {
  about: ["About Churvox", "Connected records", "Owner control", "Service business focus"],
  security: ["Security", "Authenticated access", "Business isolation", "No silent actions"],
  support: ["Support", "Login help", "Tester help", "Technical reports"],
  billing: ["Billing", "Trial terms", "Cancellation help", "Refund review"],
};

function Page({ active, type, title, intro, children, closingTitle, closingText }) {
  const info = pageInfo[type];
  return <main className="cp26Site cpWorld cpTrustRoom" data-room={type}><PublicNav active={active} />
    <section className="cpWorldHero"><div className="cpWorldLead"><span className="cpWorldRouteCode">{info[0]}</span><h1>{title}</h1><p>{intro}</p><div className="cpWorldActions"><a className="cp26Button" href={`mailto:${EMAIL}`}>Email {EMAIL}</a><Link className="cp26Button cp26ButtonGhost" to="/pricing">View pricing</Link></div></div><aside className="cpTrustInstrument"><header><span>{info[0]}</span><b>Current controls</b></header><div className="dial"><div><small>Status</small><b>Active</b></div></div><ul>{info.slice(1).map((item) => <li key={item}><span>{item}</span><b>On</b></li>)}</ul></aside></section>
    {children}
    <section className="cpWorldClosing"><div><span>Clear before checkout</span><h2>{closingTitle}</h2><p>{closingText}</p></div><div><Link className="cp26Button" to="/signup?plan=operator">Start free trial</Link><Link className="cp26Button cp26ButtonGhost" to="/contact">Contact Churvox</Link></div></section><PublicFooter />
  </main>;
}

export function AboutPage() {
  return <Page active="/about" type="about" title="Job management built around real service work." intro="Churvox reduces the admin between finishing the work and running the business. Jobs, clients, workers, messages and money stay connected, while Command keeps important decisions with the owner." closingTitle="See the product before creating an account." closingText="The public demo uses clearly labelled sample records and does not add anything to an account."><section className="cpWorldSection"><header className="cpWorldSectionHead"><span>What Churvox is for</span><h2>Less double handling. Fewer scattered decisions.</h2></header><div className="cpBlueprintGrid"><article><b>Built for service businesses</b><span>Churvox follows the work across jobs, people, client promises, messages and money.</span></article><article><b>Connected records</b><span>Client, job, worker, proof, quote and invoice information remains connected.</span></article><article><b>Prepared admin</b><span>Routine next steps are prepared from real records instead of guessed or silently completed.</span></article><article><b>Owner approval</b><span>Command keeps important decisions visible, editable and deliberate.</span></article><article><b>Business language</b><span>Jobs, visits, appointments, cleaners, stylists and technicians can use wording that fits.</span></article></div></section></Page>;
}

export function SecurityPage() {
  return <Page active="/security" type="security" title="Security and control should be clear." intro="Churvox combines authenticated access, business isolation, careful money handling and deliberate owner approval." closingTitle="Have a security or privacy question?" closingText="Send the page, concern and expected behaviour to hello@churvox.com so it can be checked properly."><section className="cpWorldSection"><header className="cpWorldSectionHead"><span>Practical controls</span><h2>Security for a working service business.</h2></header><div className="cpGuardGrid"><article><b>Account access</b><span>Owner, office, payroll and worker experiences use authenticated, role-aware routes.</span></article><article><b>Business isolation</b><span>Business records are filtered by the authenticated business context.</span></article><article><b>Stripe checkout</b><span>Stripe handles card entry. Churvox receives subscription status rather than raw card details.</span></article><article><b>Owner approval</b><span>Command is the approval desk for decisions that need deliberate review.</span></article><article><b>Accounting control</b><span>Draft invoice sync remains owner-controlled. Churvox does not file tax.</span></article><article><b>Payroll limits</b><span>Payroll review does not submit to government agencies or create bank payout files.</span></article></div></section></Page>;
}

export function PublicSupportPage() {
  return <Page active="/support" type="support" title="Get help with the exact problem." intro="Use public support for signup, billing, tester access, login, password reset or a fault that blocks the owner or worker app." closingTitle="Still deciding whether Churvox fits?" closingText="Open the demo and pricing first, then send the question that remains."><section className="cpWorldSection"><header className="cpWorldSectionHead"><span>Help options</span><h2>Go straight to the right support path.</h2></header><div className="cpSupportBoard"><article><b>Login or password</b><span>Use password reset first. Contact support if the email does not arrive or the link fails.</span><Link to="/forgot-password">Reset password →</Link></article><article><b>Billing or cancellation</b><span>Check the cancellation information and send the account email if billing status does not update.</span><Link to="/refunds-cancellations">Billing help →</Link></article><article><b>Tester access</b><span>Use the exact invited email and include it when asking for help.</span><a href={`mailto:${EMAIL}?subject=Churvox%20tester%20access`}>Email tester support →</a></article><article><b>Technical problem</b><span>Include a screenshot, page, click and expected result. Remove private client details where possible.</span><a href={`mailto:${EMAIL}?subject=Churvox%20technical%20issue`}>Report a problem →</a></article></div></section></Page>;
}

export function RefundsCancellationsPage() {
  const rows = [["01", "Trial", "The selected trial length and price are shown before Stripe checkout is completed."], ["02", "Cancellation", "Request cancellation before renewal using the account email."], ["03", "Refund review", "Requests are reviewed against the billing record, timing, access and applicable law."], ["04", "Checkout cancelled", "Leaving Stripe before completion should not activate or change the plan."], ["05", "Incorrect charge", "Contact Churvox promptly with the date, amount and business name—never full card details."], ["06", "Plan changes", "Plans and add-ons remain visible and should not silently alter the published base price."]];
  return <Page active="/refunds-cancellations" type="billing" title="Billing, cancellation and refunds in plain language." intro="Trial, cancellation, plan changes and refund review stay visible. Use the account email so the correct billing record can be identified." closingTitle="Need a billing record checked?" closingText="Email hello@churvox.com from the account email and include the business name and plan involved."><section className="cpWorldSection"><header className="cpWorldSectionHead"><span>Billing information</span><h2>Know what happens before starting checkout.</h2></header><div className="cpLedgerRows">{rows.map(([n, title, text]) => <article key={n}><i>{n}</i><div><b>{title}</b><span>{text}</span></div></article>)}</div></section></Page>;
}
