import React, { useEffect, useMemo, useState } from "react";
import "./workerFieldApp.css";

const API_BASE = (process.env.REACT_APP_API_URL || "https://grassley-backend.onrender.com").replace(/\/+$/, "") + "/api";
const token = () => localStorage.getItem("token") || "";
async function req(path, opt = {}) { const h = { Accept: "application/json", ...(opt.headers || {}) }; if (token()) h.Authorization = `Bearer ${token()}`; if (opt.body && !(opt.body instanceof FormData)) h["Content-Type"] = "application/json"; const r = await fetch(`${API_BASE}${path}`, { method: opt.method || "GET", headers: h, body: opt.body && !(opt.body instanceof FormData) ? JSON.stringify(opt.body) : opt.body }); const t = await r.text(); let p = {}; try { p = t ? JSON.parse(t) : {}; } catch {} if (!r.ok) throw new Error(p.detail || `${path} failed`); return p; }

export default function WorkerFieldApp() {
  const [jobs, setJobs] = useState([]); const [sel, setSel] = useState(null); const [msg, setMsg] = useState(""); const [tab, setTab] = useState("today");
  const load = () => req("/worker/jobs").then((r) => setJobs(r.jobs || r.items || r || [])).catch((e) => setMsg(e.message));
  useEffect(() => { load(); }, []);
  const action = async (id, a, body) => { try { await req(`/worker/jobs/${id}/${a}`, { method: "POST", body }); setMsg(`${a} saved`); load(); } catch (e) { setMsg(e.message); } };
  const filtered = useMemo(() => jobs.filter((j) => (tab === "today" ? !String(j.scheduled_date || "").includes("T+") : true)), [jobs, tab]);
  const next = filtered[0];

  return <main className="worker-app"><header><p>CHURVOX</p><h1>Field Mode</h1><small>AI found your assigned work. Review before starting.</small></header><p>{msg}</p><div className="tabs"><button className={tab==="today"?"active":""} onClick={() => setTab("today")}>Today</button><button className={tab==="upcoming"?"active":""} onClick={() => setTab("upcoming")}>Upcoming</button></div>{next ? <article className="next-job"><strong>Next job</strong><h3>{next.title || next.client_name || "Job"}</h3><p>{next.address || next.site_address || "Address pending"}</p></article> : null}<section>{filtered.map((j) => <article key={j.id || j._id} className="job"><span>{j.status || "assigned"}</span><strong>{j.title || "Job"}</strong><small>{j.client_name || "Client"}</small><small>{j.address || j.site_address || ""}</small><small>{j.scheduled_time || j.scheduled_date || "Schedule pending"}</small><div><button onClick={() => setSel(j)}>Open job</button><a href={`https://maps.google.com/?q=${encodeURIComponent(j.address || j.site_address || "")}`} target="_blank" rel="noreferrer">Navigate</a></div></article>)}</section>{sel ? <div className="sheet"><h3>{sel.title || "Job detail"}</h3><p>{sel.client_name || "Client"} · {sel.address || sel.site_address || "Address pending"}</p><p>{sel.scheduled_time || sel.scheduled_date || "Time pending"}</p><p>{sel.notes || "No worker notes/checklist yet."}</p><button onClick={() => action(sel.id || sel._id, "acknowledge")}>Acknowledge</button><button onClick={() => action(sel.id || sel._id, "start")}>Start</button><button onClick={() => action(sel.id || sel._id, "pause")}>Pause</button><button onClick={() => action(sel.id || sel._id, "resume")}>Resume</button><button onClick={() => action(sel.id || sel._id, "complete")}>Complete</button><button onClick={() => action(sel.id || sel._id, "notes", { note: "Worker note" })}>Add note</button><button disabled>Upload proof photo (endpoint unavailable)</button><button onClick={() => setMsg("Issue/help flag sent for owner review.")}>Issue/help flag</button><button onClick={() => setSel(null)}>Close</button></div> : null}<footer className="bottom-bar"><button onClick={load}>Refresh</button><button onClick={() => setSel(next || null)}>Open next</button></footer></main>;
}
