import React, { useEffect, useState } from "react";
import "./workerFieldApp.css";
const API_BASE=(process.env.REACT_APP_API_URL||"https://grassley-backend.onrender.com").replace(/\/+$/,""+"")+"/api";
const token=()=>localStorage.getItem("token")||"";
async function req(path,opt={}){const h={Accept:"application/json",...(opt.headers||{})}; if(token())h.Authorization=`Bearer ${token()}`; if(opt.body && !(opt.body instanceof FormData))h["Content-Type"]="application/json"; const r=await fetch(`${API_BASE}${path}`,{method:opt.method||"GET",headers:h,body:opt.body?JSON.stringify(opt.body):undefined}); const t=await r.text(); let p={}; try{p=t?JSON.parse(t):{}}catch{} if(!r.ok) throw new Error(p.detail||`${path} failed`); return p;}
export default function WorkerFieldApp(){const [jobs,setJobs]=useState([]);const [sel,setSel]=useState(null);const [msg,setMsg]=useState("");
const load=()=>req('/worker/jobs').then((r)=>setJobs(r.jobs||r.items||r||[])).catch((e)=>setMsg(e.message)); useEffect(()=>{load();},[]);
const action=async (id,a,body)=>{try{await req(`/worker/jobs/${id}/${a}`,{method:'POST',body}); setMsg(`${a} saved`); load();}catch(e){setMsg(e.message);}};
return <main className='worker-app'><h1>Worker Field App</h1><p>{msg}</p><section>{jobs.map((j)=><button key={j.id||j._id} className='job' onClick={()=>setSel(j)}><strong>{j.title||j.client_name||'Job'}</strong><small>{j.address||j.site_address||''}</small></button>)}</section>{sel?<div className='sheet'><h3>{sel.title||'Job detail'}</h3><button onClick={()=>action(sel.id||sel._id,'acknowledge')}>Acknowledge</button><button onClick={()=>action(sel.id||sel._id,'start')}>Start</button><button onClick={()=>action(sel.id||sel._id,'pause')}>Pause</button><button onClick={()=>action(sel.id||sel._id,'resume')}>Resume</button><button onClick={()=>action(sel.id||sel._id,'complete')}>Complete</button><button onClick={()=>action(sel.id||sel._id,'notes',{note:'Worker note'})}>Add note</button><button onClick={()=>setMsg('Photo upload endpoint unavailable or needs wiring if not configured.')}>Upload proof photo</button><a href={`https://maps.google.com/?q=${encodeURIComponent(sel.address||sel.site_address||'')}`} target='_blank' rel='noreferrer'>Open map</a><button onClick={()=>setSel(null)}>Close</button></div>:null}</main>;
}
