import React, { useEffect, useMemo, useState } from "react";
import "./workerFieldApp.css";

const API_BASE = (() => { const raw = process.env.REACT_APP_API_URL || process.env.REACT_APP_BACKEND_URL || process.env.VITE_BACKEND_URL || "https://grassley-backend.onrender.com"; const clean = String(raw).replace(/\/+$/, ""); return clean.endsWith('/api') ? clean : `${clean}/api`; })();
const tok=()=>localStorage.getItem('token')||localStorage.getItem('authToken')||localStorage.getItem('access_token')||'';
const user=()=>{for(const k of ['user','currentUser','authUser']){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v)return v;}catch{}} return {};};
async function req(path,opt={}){const h={Accept:'application/json',...(opt.headers||{})}; if(tok()) h.Authorization=`Bearer ${tok()}`; if(opt.body && !(opt.body instanceof FormData)) h['Content-Type']='application/json'; const r=await fetch(`${API_BASE}${path}`,{method:opt.method||'GET',credentials:'include',headers:h,body:opt.body && !(opt.body instanceof FormData)?JSON.stringify(opt.body):opt.body}); const t=await r.text(); let p={}; try{p=t?JSON.parse(t):{}}catch{} if(!r.ok) throw new Error(p.detail||`${path} failed`); return p; }

export default function WorkerFieldApp(){const [jobs,setJobs]=useState([]),[tab,setTab]=useState('today'),[sel,setSel]=useState(null),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
const me=user(); const ids=[me.id,me._id,me.user_id,me.worker_id,me.team_member_id].map(String).filter(Boolean); const email=String(me.email||'').toLowerCase();
const mine=(j)=>{const vals=[j.assigned_worker_id,j.worker_id,j.assigned_to,j['assigned_worker.id'],j['assigned_worker._id'],j.assigned_worker?.id,j.assigned_worker?._id].map(v=>String(v||'')); const em=[j.worker_email,j.assigned_worker_email,j.assigned_worker?.email].map(v=>String(v||'').toLowerCase()); return vals.some(v=>ids.includes(v)) || (!!email && em.includes(email));};
const load=async()=>{setLoading(true);setMsg(''); try{const a=await req('/worker/jobs'); setJobs((a.jobs||a.items||a||[]));}catch{try{const b=await req('/jobs'); const all=(b.jobs||b.items||b||[]); setJobs(all.filter(mine)); setMsg('Worker endpoint unavailable — filtered assigned jobs loaded.');}catch(e){setMsg(e.message); setJobs([]);}} finally{setLoading(false);}};
useEffect(()=>{load();},[]);
const filtered=useMemo(()=>jobs.filter((j)=>tab==='completed'?['completed','done'].includes(String(j.status||'').toLowerCase()):tab==='upcoming'? !['completed','done'].includes(String(j.status||'').toLowerCase()):true),[jobs,tab]);
const action=async(id,a,body)=>{for(const p of [`/worker/jobs/${id}/${a}`,`/jobs/${id}/${a}`]){try{await req(p,{method:'POST',body}); setMsg(`${a} saved to backend.`); load(); return;}catch{}} setMsg('Failed — please review endpoint');};
const next=filtered[0];
return <main className='worker-app'><header><p>CHURVOX</p><h1>Field Mode</h1></header><div className='tabs'><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>Today</button><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Upcoming</button><button className={tab==='completed'?'active':''} onClick={()=>setTab('completed')}>Completed</button></div>{msg?<p>{msg}</p>:null}{loading?<p>Loading assigned jobs…</p>:null}{next?<article className='next-job'><strong>Next job</strong><h3>{next.title||'Job'}</h3><p>{next.address||next.site_address||'Address pending'}</p></article>:null}<section>{filtered.map(j=><article key={j.id||j._id} className='job'><span>{j.status||'assigned'}</span><strong>{j.title||'Job'}</strong><small>{j.client_name||j.customer_name||'Client'}</small><small>{j.address||j.site_address||''}</small><small>{j.scheduled_time||j.scheduled_date||'Schedule pending'}</small><div><button onClick={()=>setSel(j)}>Open job</button><a href={`https://maps.google.com/?q=${encodeURIComponent(j.address||j.site_address||'')}`} target='_blank' rel='noreferrer'>Navigate</a></div></article>)}</section>{sel?<div className='sheet'><h3>{sel.title||'Job detail'}</h3><p>{sel.client_name||sel.customer_name||'Client'}</p><p>{sel.address||sel.site_address||'Address pending'}</p><p>{sel.scheduled_time||sel.scheduled_date||'Time pending'}</p><p>{sel.worker_notes||sel.notes||'No worker notes yet.'}</p><button onClick={()=>action(sel.id||sel._id,'acknowledge')}>Acknowledge</button><button onClick={()=>action(sel.id||sel._id,'start')}>Start</button><button onClick={()=>action(sel.id||sel._id,'pause')}>Pause</button><button onClick={()=>action(sel.id||sel._id,'resume')}>Resume</button><button onClick={()=>action(sel.id||sel._id,'complete')}>Complete</button><button onClick={()=>action(sel.id||sel._id,'notes',{note:'Worker note'})}>Add note</button><button disabled>Upload proof photo (only when endpoint exists)</button><button onClick={()=>setMsg('Issue/help flag saved locally for owner review.')}>Issue/help flag</button><button onClick={()=>setSel(null)}>Close</button></div>:null}<footer className='bottom-bar'><button onClick={load}>Refresh</button><button onClick={()=>setSel(next||null)}>Open next</button></footer></main>
}
