import React from "react";
export function TradieAppShell({ sidebar, header, mobileNav, children }) { return <div className="min-h-screen bg-slate-100 text-slate-900"><div className="mx-auto flex min-h-screen w-full max-w-[1680px]">{sidebar}<div className="flex min-h-screen min-w-0 flex-1 flex-col">{header}<div className="flex-1">{children}</div></div></div>{mobileNav}</div>; }
export function TradiePage({ children, className = "" }) { return <section className={`mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8 ${className}`}>{children}</section>; }
export function TradieHeader({ title, subtitle, primaryAction, secondaryActions }) { return <div className="mb-6 flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold text-slate-900">{title}</h1>{subtitle ? <p className="mt-1 text-sm text-slate-600">{subtitle}</p> : null}</div><div className="flex flex-wrap items-center gap-2">{secondaryActions}{primaryAction}</div></div>; }
export function TradiePanel({ children, className = "" }) { return <div className={`rounded-3xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</div>; }
export function TradieGrid({ children, className = "" }) { return <div className={`grid gap-4 md:grid-cols-2 xl:grid-cols-3 ${className}`}>{children}</div>; }
export function TradieList({ children, className = "" }) { return <div className={`overflow-hidden rounded-2xl border border-slate-200 bg-white ${className}`}>{children}</div>; }
export function TradieBadge({ tone = "default", children }) { const tones = { success: "bg-emerald-100 text-emerald-700", progress: "bg-blue-100 text-blue-700", warning: "bg-amber-100 text-amber-700", neutral: "bg-slate-100 text-slate-700", danger: "bg-rose-100 text-rose-700", default: "bg-slate-100 text-slate-700" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone] || tones.default}`}>{children}</span>; }
export function TradieActions({ primary, secondary, danger }) { return <div className="flex flex-wrap items-center gap-2">{primary}{secondary}<div className="ml-auto">{danger}</div></div>; }
export function TradieEmptyState({ title, text, action }) { return <TradiePanel className="text-center"><h3 className="text-lg font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-600">{text}</p><div className="mt-4">{action}</div></TradiePanel>; }
export function TradieLoadingState({ title = "Loading" }) { return <TradiePanel><div className="animate-pulse space-y-3"><div className="h-5 w-48 rounded bg-slate-200" /><div className="h-4 w-full rounded bg-slate-100" /><div className="h-4 w-5/6 rounded bg-slate-100" /></div><p className="mt-3 text-sm text-slate-500">{title}</p></TradiePanel>; }
