export const commandFloorTestingDeployMarker = "CHURVOX_COMMAND_FLOOR_TESTING_DEPLOY_MARKER_20260527_RUNTIME_PUSHED_BY_CHATGPT";

if (typeof window !== "undefined") {
  window.__CHURVOX_COMMAND_FLOOR_TESTING_DEPLOY_MARKER__ =
    "CHURVOX_COMMAND_FLOOR_TESTING_DEPLOY_MARKER_20260527_RUNTIME_PUSHED_BY_CHATGPT";
}
