export const commandFloorRuntimeMarkers = {
  beenApproved: "CHURVOX_COMMAND_FLOOR_BEEN_APPROVED_CLEAN_CARD_20260527_RUNTIME",
  workSlip: "CHURVOX_COMMAND_FLOOR_REAL_APPROVAL_SLIP_REPLACEMENT_20260527_RUNTIME",
  tallCards: "CHURVOX_COMMAND_FLOOR_REAL_SCROLL_TALL_CARDS_20260527_RUNTIME",
  testingDeploy: "CHURVOX_COMMAND_FLOOR_TESTING_DEPLOY_MARKER_20260527_RUNTIME",
  realApprovalSlip: "CHURVOX_REAL_APPROVAL_SLIP_REPLACEMENT_20260527"
};

if (typeof window !== "undefined") {
  window.__CHURVOX_COMMAND_FLOOR_RUNTIME_MARKERS__ = commandFloorRuntimeMarkers;
}
